import type { CraftReelDocument } from '../models/types.ts';

export const INITIAL_CRAFT_REELS_DB: CraftReelDocument[] = [
  {
    id: 'reel-qena-pottery',
    title: 'سحر تشكيل القلة القناوية على الدولاب التراثي',
    artisanName: 'الأسطى حسني القناوي',
    artisanAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    workshopName: 'ورشة فخار القناوي الأصيل',
    sellerId: 'seller-1',
    governorate: 'قنا',
    craftType: 'فخار وخزف طمي النيل',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-potter-shaping-a-clay-vase-41717-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    duration: '0:24',
    likesCount: 384,
    viewsCount: 4120,
    sharesCount: 92,
    productId: 'prod-1',
    productTitle: 'قلة قناوية فخار مسامي أصيل لتبريد المياه',
    productPrice: 140,
    productOriginalPrice: 180,
    productImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80',
    productRating: 4.9,
    inStock: true,
    description: 'سر القلة القناوية في مسامية طمي النيل الطبيعي وسرعة حركة الدولاب اليدوي.. كل حركة يد تحدد برودة ونقاء المياه وعذوبتها الطبيعية! 🏺🌿',
    hashtags: ['#فخار_قنا', '#طمي_النيل', '#صنع_في_مصر', '#تراث_الصعيد', '#قلة_قناوية'],
    musicTrack: 'نغم الربابة الصعيدي التراثي • مقام حجاز',
    isVerifiedArtisan: true,
    isFeatured: true,
    createdAt: '2026-08-20',
    comments: [
      {
        id: 'c1',
        userName: 'م. أحمد الشاذلي',
        userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        governorate: 'القاهرة',
        comment: 'ما شاء الله تسلم إيد الأسطى حسني، اشتريت القلة المرة اللي فاتت والمياه طالعة منها ساقعة كأنها في تلاجة وطعمها يجنن!',
        createdAt: 'منذ يومين',
        likesCount: 24
      },
      {
        id: 'c2',
        userName: 'سارة عبد الرحمن',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
        governorate: 'الإسكندرية',
        comment: 'فيديو ممتع جداً بيوضح عظمة الصنعة اليدوية.. طلبت اتنين هدايا لوالدتي.',
        createdAt: 'منذ 3 أيام',
        likesCount: 16
      }
    ]
  },
  {
    id: 'reel-akhmeem-loom',
    title: 'غزل خيوط الصوف على نول أخميم اليدوي العريق',
    artisanName: 'الحاجة فاطمة السوهاجية',
    artisanAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    workshopName: 'أنوال الحرير والكليم السوهاجي',
    sellerId: 'seller-akhmeem-loom',
    governorate: 'سوهاج',
    craftType: 'كليم وسجاد نول يدوي',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-weaving-fabric-on-a-loom-41724-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    duration: '0:28',
    likesCount: 520,
    viewsCount: 5890,
    sharesCount: 145,
    productId: 'prod-2',
    productTitle: 'سجادة كليم أخميمي صوف طبيعي 100% بنقوش هندسية',
    productPrice: 850,
    productOriginalPrice: 1100,
    productImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
    productRating: 5.0,
    inStock: true,
    description: 'كل خيط على نول أخميم بيتشد بحب وصبر، بأصباغ نباتية طبيعية وألوان تدوم لعشرات السنين بدون بهتان! 🧶🧵',
    hashtags: ['#كليم_أخميم', '#نول_يدوي', '#صوف_طبيعي', '#سوهاج', '#ديكور_صعيدي'],
    musicTrack: 'إيقاع الدف والنول الصعيدي الأصيل',
    isVerifiedArtisan: true,
    isFeatured: true,
    createdAt: '2026-08-22',
    comments: [
      {
        id: 'c3',
        userName: 'د. منى كمال',
        userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        governorate: 'الجيزة',
        comment: 'أخميم عاصمة النسيج في التاريخ، وفخورة جداً بوجود منصة بتعرض شغل الحاجة فاطمة بالشكل المشرّف ده!',
        createdAt: 'منذ يوم',
        likesCount: 31
      }
    ]
  },
  {
    id: 'reel-luxor-brass',
    title: 'دق ونقش الصواني النحاسية الأقصرية بالمطرقة والأزميل',
    artisanName: 'المعلم ربيع الأقصري',
    artisanAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    workshopName: 'خان المشغولات النحاسية التراثية',
    sellerId: 'seller-luxor-brass',
    governorate: 'الأقصر',
    craftType: 'نقش نحاس أحمر وأصفر',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-blacksmith-working-with-hammer-and-anvil-41719-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    duration: '0:20',
    likesCount: 298,
    viewsCount: 3200,
    sharesCount: 68,
    productId: 'prod-3',
    productTitle: 'صينية نحاس أحمر منقوشة يدوياً بزخارف فاطمية وإسلامية',
    productPrice: 650,
    productOriginalPrice: 780,
    productImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    productRating: 4.8,
    inStock: true,
    description: 'صوت الدق بالمطرقة والأزميل على النحاس الأحمر المعتق سيمفونية صعيدية تعيش في خانات الأقصر منذ مئات السنين! 🔨✨',
    hashtags: ['#نحاس_الأقصر', '#نقش_يدوي', '#زخارف_إسلامية', '#أصالة', '#تحف_مصرية'],
    musicTrack: 'تقاسيم العود الصعيدي مع الناي الحزين',
    isVerifiedArtisan: true,
    createdAt: '2026-08-25',
    comments: []
  },
  {
    id: 'reel-aswan-wicker',
    title: 'تضفير حلفا النخيل وسعف النوبة في صواني ملونة',
    artisanName: 'أم كلثوم الأسوانية',
    artisanAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    workshopName: 'مشغولات الخوص والحلفا النوبية',
    sellerId: 'seller-aswan-wicker',
    governorate: 'أسوان',
    craftType: 'خوص وحلفا طبيعية',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-crafting-a-wicker-basket-41718-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1528458909336-e7a0adfed0a5?auto=format&fit=crop&w=800&q=80',
    duration: '0:22',
    likesCount: 440,
    viewsCount: 4900,
    sharesCount: 110,
    productId: 'prod-4',
    productTitle: 'طبق خوص نوبي ملون معلق لديكور الحوائط والضيافة',
    productPrice: 220,
    productOriginalPrice: 280,
    productImage: 'https://images.unsplash.com/photo-1528458909336-e7a0adfed0a5?auto=format&fit=crop&w=600&q=80',
    productRating: 4.9,
    inStock: true,
    description: 'ألوان النوبة المبهجة المستوحاة من شمس وقمر أسوان، مجدولة بعيدان الحلفا وسعف النخيل المجفف بيئياً 100%! 🌴☀️',
    hashtags: ['#خوص_أسوان', '#تراث_نوبي', '#صديق_للبيئة', '#سعف_نخيل', '#ديكور_ريفي'],
    musicTrack: 'إيقاعات الدف والطنبورة النوبية التراثية',
    isVerifiedArtisan: true,
    createdAt: '2026-08-27',
    comments: []
  }
];
