import dotenv from 'dotenv';
dotenv.config();
import { MongoClient } from 'mongodb';

export const AUTHENTIC_WAH_PEOPLE = [
  // ==========================================
  // 1. قنا (gov-qena)
  // ==========================================
  {
    id: 'person-abnoudi',
    name: 'عبد الرحمن الأبنودي (الخال)',
    slug: 'abdelrahman-el-abnoudi-qena',
    titleOrRole: 'شاعر العامية الكبرى وحارس السيرة الهلالية',
    craftOrSkill: 'شعر العامية وحفظ التراث الشفاهي الصعيدي',
    craftTitle: 'شاعر العامية الكبرى',
    governorateName: 'قنا',
    governorateId: 'gov-qena',
    biography: 'الخال عبد الرحمن الأبنودي ابن قرية أبنود في قنا، مفيش حد لمس وجع الصعايدة وفرحتهم وقعدتهم على المصطبة قده. قضى أكتر من عشرين سنة يلف القرى والنجوع على رجليه ورا شعراء الربابة علشان يجمع السيرة الهلالية بيتاً بيتاً من صدور الرواة ويحفظ ملحمة بني هلال بصوته للتاريخ. كلماته غناها كبار الفن زي عبد الحليم وشادية ومحمد رشدي ومحمد منير، وعلّم المصريين إزاي الكلمة الصعيدية البسيطة تهز الوجدان.',
    bio: 'الخال عبد الرحمن الأبنودي ابن قرية أبنود في قنا، مفيش حد لمس وجع الصعايدة وفرحتهم وقعدتهم على المصطبة قده. قضى أكتر من عشرين سنة يلف القرى والنجوع على رجليه ورا شعراء الربابة علشان يجمع السيرة الهلالية بيتاً بيتاً من صدور الرواة ويحفظ ملحمة بني هلال بصوته للتاريخ.',
    quote: 'أنا اللي غنيت في حزن الناس وفي فرحهم، صعيدي راسي مرفوعة بطمي النيل وعمري ما اتخليت عن أهلي وناسي.',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 55,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أطلس المأثورات الشعبية وهيئة قصور الثقافة - قنا',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-abdelbaset',
    name: 'الشيخ عبد الباسط عبد الصمد',
    slug: 'sheikh-abdelbaset-abdessamad-qena',
    titleOrRole: 'الحنجرة الذهبية وصوت مكة وسفير القرآن للعالم',
    craftOrSkill: 'تلاوة القرآن الكريم وفنون المقامات الصوتية',
    craftTitle: 'كروان التلاوة القرآنية',
    governorateName: 'قنا',
    governorateId: 'gov-qena',
    biography: 'ابن قرية المراعزة بمركز أرمنت جنوب قنا، صوته كان هبة ربانية نادرة بتسري في الروح وتخشع ليها القلوب. حفظ القرآن وهو طفل صغير في كتاب قريته وتتلمذ على كبار شيوخ القراءات في الصعيد، ولما صوته انطلق من الإذاعة المصرية والحرم المكي سحر العالم كله. سافر لكل قارات الأرض يحمل كتاب الله بصوته اللي جمع بين الشجن الصعيدي الأصيل والنقاء الروحي اللي ملوش مثيل.',
    bio: 'ابن قرية المراعزة بمركز أرمنت جنوب قنا، صوته كان هبة ربانية نادرة بتسري في الروح وتخشع ليها القلوب. انطلق صوته من كتاتيب الصعيد ليموج به العالم الإسلامي خشوعاً وإجلالاً.',
    quote: 'القرآن نزل بالحجاز، وفُهم بالنجف، وقُرئ بمصر بأحلى ما وهب الله من خشوع الصوت الصعيدي.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'نقابة قراء القرآن الكريم - سجل أعلام التلاوة بقنا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-amal-donqol',
    name: 'أمل دنقل (أمير شعراء الرفض)',
    slug: 'amal-donqol-qena',
    titleOrRole: 'أمير شعراء الرفض والكرامة الوطنية',
    craftOrSkill: 'الشعر العربي الحديث وقصيدة التفعيلة المقاومة',
    craftTitle: 'أمير شعراء الرفض',
    governorateName: 'قنا',
    governorateId: 'gov-qena',
    biography: 'محمد أمل فهيم محارب دنقل، وُلد في قرية القلعة بمركز قفط في قنا سنة 1940. الصعيدي النحيل الأسمر اللي كانت كلماته بتهز قلاع الظلم والاستسلام. استلهم شموخ جبال قنا وتراث كليلة ودمنة وجساس والزير سالم عشان يكتب أروع مراثي الكرامة زي «لا تصالح» و«كلمات سبارتاكوس الأخيرة» و«البكاء بين يدي زرقاء اليمامة». علامة فارقة في الضمير العربي وفخر لكل ابن من أبناء الصعيد.',
    bio: 'ابن قرية القلعة بمركز قفط في قنا، الصعيدي الأسمر اللي كتب أروع مراثي الكرامة والرفض، صاحب «لا تصالح» التي أصبحت ميثاق شرف وكرامة لكل الأجيال.',
    quote: 'لا تصالح.. ولو منحوك الذهب، أترى حين أفقأ عينيك ثم أثبت جوهرتين مكانهما.. هل ترى؟ هي أشياء لا تشترى.',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 30,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة العامة لقصور الثقافة - أعلام قفط وقنا',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-hefny-ahmed-hassan',
    name: 'الريس حفني أحمد حسن',
    slug: 'hefny-ahmed-hassan-qena',
    titleOrRole: 'إمبراطور الموال الصعيدي وسلطان فن الواو',
    craftOrSkill: 'الموال الصعيدي المرتجل، الغناء الشعبي، الملاحم الشعبية',
    craftTitle: 'إمبراطور الموال الصعيدي',
    governorateName: 'قنا',
    governorateId: 'gov-qena',
    biography: 'أسطورة الغناء الشعبي الصعيدي، ابن قنا صاحب الحنجرة الفولاذية اللي كانت بتزلزل الساحات والأفراح من أسوان للجيزة. كان معلماً ومرتجلًا عبقرياً في وزن القافية وفن الواو والموال الصعيدي الرباعي والخماسي. اشتهر بروايته لملحمة «شفيقة ومتولي» ومواويل الصبر والجدعنة وأصول الرجولة، وما زال صوته العريض علامة مسجلة للأصالة الصعيدية.',
    bio: 'ابن قنا وإمبراطور الموال الصعيدي وفن الواو، حنجرة فولاذية أطربت الصعيد لعقود بروايات الملاحم الشعبية ومواويل الصبر والكرم الصعيدي.',
    quote: 'الصبر طيب يا باهي الخد والمبسم، والمولى قادر يفك الكرب ويقسم.. خليك على الأصل والجدعنة تِغنم.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أرشيف الموسيقى الشعبية المصرية - فرع قنا والأقصر',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 2. الأقصر (gov-luxor)
  // ==========================================
  {
    id: 'person-ahmed-al-tayeb',
    name: 'فضيلة الإمام الأكبر د. أحمد الطيب',
    slug: 'sheikh-ahmed-el-tayeb-luxor',
    titleOrRole: 'شيخ الأزهر الشريف ورمز الوسطية والسلام العالمي',
    craftOrSkill: 'الفكر الفلسفي الإسلامي، التسامح، والصلح العرفي بالصعيد',
    craftTitle: 'شيخ الأزهر الشريف',
    governorateName: 'الأقصر',
    governorateId: 'gov-luxor',
    biography: 'ابن مدينة القرنة بالبر الغربي للأقصر، وريث الساحة الطيبية الصوفية التاريخية اللي بتفتح أبوابها ليل نهار لكل صاحب حاجة، ومقر أكبر جلسات الصلح العرفي وحقن الدماء بين عائلات وقبائل الصعيد. شخصية عالمية جمعت بين أرقى علوم الفلسفة الغربية والإسلامية وبين التواضع الصعيدي الجم والزهد الحقيقي، حامل راية وثيقة الأخوة الإنسانية والسلام العالمي.',
    bio: 'ابن القرنة بغرب الأقصر، وريث الساحة الطيبية لحقن الدماء وإصلاح ذات البين، وقامة الفكر والوسطية الإسلامية التي يحترمها العالم كله.',
    quote: 'جلسات الصلح وإطفاء نار الفتنة بين الناس مش مجرد واجب اجتماعي، دي روح الصعيد وجوهر ديننا الحنيف.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'مشيخة الأزهر الشريف والساحة الطيبية بالقرنة',
    sourceUrl: 'https://www.azhar.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-yahya-taher',
    name: 'يحيى الطاهر عبد الله',
    slug: 'yahya-taher-abdullah-luxor',
    titleOrRole: 'شاعر القصة القصيرة الصعيدية وأديب الكرنك',
    craftOrSkill: 'القصة القصيرة والرواية وتصوير المجتمع الجنوبي',
    craftTitle: 'أديب الكرنك المجدد',
    governorateName: 'الأقصر',
    governorateId: 'gov-luxor',
    biography: 'ابن قرية الكرنك بالأقصر (1938 - 1981)، ساحر الكلمات اللي كتب القصة القصيرة بلغة تشبه التراتيل الصوفية وأغاني الحصاد الفرعونية. خلّد أساطير ووجع الجنوب في روايته الفذة «الطوق والأسورة» ومجموعاته «الدف والصندوق» و«حكايات للأمير حتى ينام». كان لما يقعد يحكي قصة في قهوة، الناس تسكت تماماً كأنهم مسحورين بصوت راوي الصعيد الحقيقي.',
    bio: 'ابن الكرنك بالأقصر، ساحر القصة القصيرة وصاحب «الطوق والأسورة»، الذي حوّل حزن الصعيد وأساطير نخيله إلى أدب عالمي باهر.',
    quote: 'الحكاية الصعيدية مش كلام بنرصه على ورق، دي دم ونبض وعرق طالع مع طمي النيل في الصيف.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 25,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة العامة لقصور الثقافة - أدباء الأقصر',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-abu-al-haggag',
    name: 'حكاية وسيرة سيدي أبو الحجاج الأقصري',
    slug: 'sidi-abu-al-haggag-luxor',
    titleOrRole: 'سلطان العارفين بالأقصر ورمز المحبة والتآخي الشعبي',
    craftOrSkill: 'التراث الصوفي الشعبي وموكب الدورة والموالد التاريخية',
    craftTitle: 'قطب العارفين بالأقصر',
    governorateName: 'الأقصر',
    governorateId: 'gov-luxor',
    biography: 'الشيخ يوسف بن عبد الرحيم الأقصري (المتوفى 642 هـ)، اللي مسجده معلق ومبني جوه أحضان معبد الأقصر الفرعوني في مشهد تاريخي فريد ملوش مثيل في العالم كله. يعتبره أهالي الأقصر رمزاً للبركة والأمان. مولده السنوي هو أكبر عرس شعبي وتراثي في الأقصر، بيخرج فيه موكب «الدورة» وتشارك فيه قوارب خشبية محمولة على الأكتاف ورجال التحطيب والخيول العربية في ملحمة حب وفرح لا تنتهي.',
    bio: 'سلطان العارفين بالأقصر، مسجده المعلق فوق أعمدة معبد الأقصر يجسد تلاحم الحضارات، ومولده ودورته السنوية هي أبهى احتفالات الجنوب.',
    quote: 'الأقصر بلاد الحضارة والنور.. معبد فرعوني وجواه مسجد وقلوب ناسها عامرة بالمودة والترحيب بالضيف.',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'وزارة السياحة والآثار وتراث الأقصر الصوفي',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'unesco',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 3. أسوان (gov-aswan)
  // ==========================================
  {
    id: 'person-king-mounir',
    name: 'محمد منير (الكينج)',
    slug: 'king-mohamed-mounir-aswan',
    titleOrRole: 'صوت النوبة وسفير الأغنية المصرية المعاصرة للعالم',
    craftOrSkill: 'الغناء النوبي، المزج الموسيقي، وحفظ الهوية الجنوبية',
    craftTitle: 'الكينج وسفير الجنوب',
    governorateName: 'أسوان',
    governorateId: 'gov-aswan',
    biography: 'ابن منشية النوبة بأسوان، الأسمر اللي دخل كل بيت مصري من أول ما غنى «الليلة يا سمرا» و«شبابيك». خرج من جزر وشواطئ نيل أسوان حاملاً السلم الخماسي النوبي الأصيل ودمجه ببراعة مع الجاز والروك العالمي، وعبّر عن هموم الناس وحب الوطن والأرض بطريقة مفيش حد عرف يقلدها. منير مش مجرد مطرب، ده حالة وجدانية كاملة بتختصر دفء الصعيد وطيبة أهل النوبة.',
    bio: 'ابن منشية النوبة بأسوان، الأسمر الذي حمل السلم الخماسي النوبي إلى مسارح العالم ووحّد وجدان ملايين المصريين على عشق الجنوب والحرية.',
    quote: 'بلاد طيبة.. شمسها ناصعة ونيلها حنين، ومهما طوفت في بلاد العالم مفيش ريحة تشبه ريحة طمي أسوان.',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أكاديمية الفنون المصرية وأرشيف الموسيقى النوبية بأسوان',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-el-akkad',
    name: 'عباس محمود العقاد',
    slug: 'abbas-mahmoud-el-akkad-aswan',
    titleOrRole: 'عملاق الفكر والأدب العربي وصاحب العبقريات',
    craftOrSkill: 'الفلسفة، النقد الأدبي، التاريخ الإسلامي، والشعر',
    craftTitle: 'عملاق الفكر العربي',
    governorateName: 'أسوان',
    governorateId: 'gov-aswan',
    biography: 'ابن أسوان العصامي البار (1889 - 1964)، الصعيدي الجبل اللي علّم نفسه بنفسه ومعهوش غير الشهادة الابتدائية لحد ما بقى أضخم عقلية فكرية وأدبية في القرن العشرين. صاحب سلسلة «العبقريات» الإسلامية وأكتر من 100 كتاب أثروا المكتبة العربية. كان معروفاً بكبريائه الصعيدي المهيب وأنفته اللي رفضت الانحناء لأي سلطان، وقبره ومتحفه في وسط أسوان شاهدين على فخر الجنوب بيه.',
    bio: 'ابن أسوان البار وعصامي الفكر الأكبر، صاحب العبقريات الذي واجه ملوكاً وكتب مئات المؤلفات بكبرياء وشموخ الجرانيت الأسواني.',
    quote: 'لا أحب أن أكون كالمسمار يثبت في مكانه، بل كالريح التي تحرك كل راكد وتفتح النوافذ على النور.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'متحف العقاد بأسوان والهيئة العامة للاستعلامات',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-ahmed-mounib',
    name: 'الموسيقار أحمد منيب',
    slug: 'ahmed-mounib-aswan',
    titleOrRole: 'عراب وأب الموسيقى النوبية واللحن الجنوبي الأصيل',
    craftOrSkill: 'التلحين، العزف على العود، وصياغة الألحان النوبية الخماسية',
    craftTitle: 'عراب الموسيقى النوبية',
    governorateName: 'أسوان',
    governorateId: 'gov-aswan',
    biography: 'ابن قرية توماس وعافية بالنوبة بأسوان، الملحن الفذ وعازف العود اللي شكل الوجدان الموسيقي لجنوب مصر. هو اللي اكتشف وصاغ أشهر ألحان محمد منير زي «حدوتة مصرية»، «شجر الليمون»، «يا وعدي عالأيام»، و«شمندورة». كان صوته ولحنه بيحمل شجن التهجير وأمل العودة للنيل وحلاوة البيوت النوبية الملونة بالدفء والبهجة.',
    bio: 'ابن توماس وعافية بأسوان، الأب الروحي للأغنية النوبية الحديثة وصانع أشهر ألحان محمد منير التي خلدت هوية الجنوب الموسيقية.',
    quote: 'النوبة مش مجرد لحن يطرب.. النوبة هي الضحكة الحنينة والحزن الشريف اللي بيطهر قلوب الناس.',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'جمعية إحياء التراث النوبي بأسوان والمعهد العالي للموسيقى العربية',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 4. سوهاج (gov-sohag)
  // ==========================================
  {
    id: 'person-menshawy',
    name: 'الشيخ محمد صديق المنشاوي',
    slug: 'sheikh-mohamed-seddiq-menshawy-sohag',
    titleOrRole: 'الصوت الباكي وقيثارة السماء وسلطان الخشوع',
    craftOrSkill: 'تلاوة القرآن الكريم وتجويده والمقامات الروحانية العميقة',
    craftTitle: 'الصوت الباكي للقرآن',
    governorateName: 'سوهاج',
    governorateId: 'gov-sohag',
    biography: 'ابن مدينة المنشأة بسوهاج (1920 - 1969)، من عائلة قرآنية عريقة طلع منها والده وأخوه الشيخ محمود من كبار القراء. سُمي بـ «الصوت الباكي» لأن تلاوته كانت تنزل على القلوب بالدموع والخشوع الحقيقي، بدون أي تكلف أو استعراض. رفض كل مغريات الرؤساء والملوك وفضل يعيش بسيطاً وخالصاً لكتاب الله، وما زالت تسجيلاته للمصحف المرتل والمجود هي المرجع الأسمى للخشوع الإيماني.',
    bio: 'ابن المنشأة بسوهاج، قيثارة السماء والصوت الباكي الذي يهز القلوب بخشوع إلهي نقي لا يدانيه أحد في تاريخ التلاوة المصرية.',
    quote: 'القرآن كلام الله العزيز، إن خرج من سويداء القلب وصل إلى القلوب، وإن خرج من الحناجر لم يجاوز الآذان.',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 35,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'إذاعة القرآن الكريم من القاهرة وسجل قراء سوهاج',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-tahtawi',
    name: 'الشيخ رفاعة رافع الطهطاوي',
    slug: 'refaa-al-tahtawi-sohag',
    titleOrRole: 'رائد التنوير والترجمة ومؤسس مدرسة الألسن والنهضة الحديثة',
    craftOrSkill: 'الفكر والتنوير والترجمة والنهضة التعليمية وبناء المدارس',
    craftTitle: 'رائد التنوير في مصر الحديثة',
    governorateName: 'سوهاج',
    governorateId: 'gov-sohag',
    biography: 'ابن طهطا بسوهاج (1801 - 1873)، العالم الأزهري الصعيدي الذكي اللي بعته محمد علي باشا إماماً للبعثة المصرية لباريس، فرجع بعقلية نهضوية عظيمة وكتابه الشهير «تخليص الإبريز في تلخيص باريز». أسس مدرسة الألسن، وأشرف على حركة ترجمة آلاف الكتب العلمية، ونادى بتعليم البنات لأول مرة في مصر، ووضع أسس الدولة المصرية الحديثة على مبادئ العدل والمعرفة.',
    bio: 'ابن طهطا بسوهاج، رائد التنوير وصاحب «تخليص الإبريز»، مؤسس مدرسة الألسن وأول من نادى بتعليم الفتيات في الشرق.',
    quote: 'حب الأوطان من الإيمان، والتعليم هو النور الحقيقي اللي بيطرد ظلمات الجهل والفقر عن بلادنا.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة العامة للاستعلامات - رواد الفكر والنهضة المصرية',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-ghitani',
    name: 'الروائي جمال الغيطاني',
    slug: 'gamal-el-ghitani-sohag',
    titleOrRole: 'صاحب «الزيني بركات» وحارس التراث والسرد التاريخي',
    craftOrSkill: 'الرواية، الصحافة الحربية، واستلهام التراث الصوفي والمملوكي',
    craftTitle: 'روائي الذاكرة المصرية',
    governorateName: 'سوهاج',
    governorateId: 'gov-sohag',
    biography: 'ابن قرية جهينة بسوهاج (1945 - 2015)، من أعمق الكتاب اللي حفروا في الهوية المصرية. كان مراسلاً حربياً شجاعاً على الجبهة في حربي الاستنزاف وأكتوبر المجيدة، وأسس جريدة «أخبار الأدب». استلهم التراث الشعبي والمملوكي والتصوف ليكتب تحفته الروائية «الزيني بركات» وسلسلة «دفاتر التدوين». ظل عاشقاً لأصوله السوهاجية ولعمق التاريخ الصعيدي حتى آخر يوم في حياته.',
    bio: 'ابن جهينة بسوهاج، المراسل الحربي الملحمي وصاحب «الزيني بركات»، الذي صاغ أعمق الروايات استلهاماً للتراث الصوفي والمملوكي.',
    quote: 'من ينسى تاريخه يفقد بوصلة حاضره ومستقبله، والصعيد هو الجذر الضارب في أعماق الهوية المصرية.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'اتحاد كتاب مصر وأرشيف أخبار الأدب - سوهاج',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'academic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-george-sidhom',
    name: 'الفنان جورج سيدهم',
    slug: 'george-sidhom-sohag',
    titleOrRole: 'صانع البهجة وفيلسوف الضحكة ومؤسس ثلاثي أضواء المسرح',
    craftOrSkill: 'التمثيل المسرحي والسينمائي وفنون الكوميديا الراقية',
    craftTitle: 'فيلسوف الضحكة والبهجة',
    governorateName: 'سوهاج',
    governorateId: 'gov-sohag',
    biography: 'ابن مدينة جرجا بسوهاج (1938 - 2020)، الفنان المحبوب صاحب الابتسامة الطيبة وخفة الدم الصعيدية الأصيلة. شكّل مع سمير غانم والضيف أحمد فرقة «ثلاثي أضواء المسرح» اللي غيرت شكل الكوميديا والاستعراض في العالم العربي. قدّم روائع مسرحية زي «المتزوجون» بشخصية حنفي الشهيرة، و«موسيقى في الحي الشرقي»، وأفلام سينمائية أسعدت كل الأسر المصرية على مدار أجيال.',
    bio: 'ابن جرجا بسوهاج وأحد أعمدة ثلاثي أضواء المسرح وصاحب شخصية حنفي في «المتزوجون»، فنان رسم الابتسامة بصدق وطيبة ابن الصعيد.',
    quote: 'الضحكة اللي طالعة من القلب هي الدوا اللي بينسي الناس غلب الأيام، والفنان ملوش قيمة بدون حب جمهوره.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'موسوعة السينما والمسرح المصري - الهيئة العامة للاستعلامات',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 5. أسيوط (gov-asyut)
  // ==========================================
  {
    id: 'person-samir-ghanem',
    name: 'الفنان الأسطورة سمير غانم',
    slug: 'samir-ghanem-asyut',
    titleOrRole: 'أسطورة الكوميديا وفطوطة الضحك المصري وأستاذ الارتجال',
    craftOrSkill: 'الكوميديا، التمثيل المسرحي، الفوازير الاستعراضية، وفن الإضحاك الفطري',
    craftTitle: 'أسطورة الضحك والبهجة',
    governorateName: 'أسيوط',
    governorateId: 'gov-asyut',
    biography: 'ابن قرية عرب الأطاولة بمركز الفتح في أسيوط (1937 - 2021)، صانع البهجة الأكبر في تاريخ الفن العربي. كبر في أحضان أسيوط قبل ما يلتحق بكلية الزراعة في الإسكندرية وينطلق لتأسيس ثلاثي أضواء المسرح. أمتع كل بيت عربي بابتكاره لشخصية «فطوطة وسمورة» في فوازير رمضان، ومسرحيات أسطورية زي «أهلاً يا دكتور» و«المتزوجون» و«جحا يحكم المدينة». كان يرتجل على المسرح فيبكي الصالة من كتر الضحك ببراءة وعفوية صعيدية ملهاش مثيل.',
    bio: 'ابن عرب الأطاولة بأسيوط، ملك الارتجال وصانع بهجة فوازير فطوطة، الذي أضحك العالم العربي لأكثر من نصف قرن بعفوية صعيدية لا تتكرر.',
    quote: 'أجمل إحساس في الوجود إنك تشوف ضحكة صافية في عين إنسان كان مهموم ومخنوق.. دي بالدنيا وما فيها.',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 55,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'سجل رواد الفن والمسرح المصري والهيئة العامة لقصور الثقافة بأسيوط',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-suyuti',
    name: 'الإمام جلال الدين السيوطي',
    slug: 'imam-jalal-al-din-al-suyuti-asyut',
    titleOrRole: 'موسوعة الفكر والتراث الإسلامي ومؤرخ الصعيد الأكبر',
    craftOrSkill: 'علوم الحديث والتفسير واللغة وتوثيق التاريخ الإسلامي',
    craftTitle: 'موسوعي التراث الإسلامي',
    governorateName: 'أسيوط',
    governorateId: 'gov-asyut',
    biography: 'فخر أسيوط وعالم الدنيا في القرن العاشر الهجري (1445 - 1505 م)، الإمام عبد الرحمن بن أبي بكر السيوطي. موسوعة تمشي على الأرض، ألف أكتر من 600 مصنف وكتاب في التفسير والحديث والفقه واللغة والتاريخ، أشهرها «الإتقان في علوم القرآن»، «تفسير الجلالين»، و«تاريخ الخلفاء». خلد اسم محافظة أسيوط في أرجاء العالم الإسلامي كله من إسطنبول لمراكش، واعتزل الناس في جزيرة الروضة ليتفرغ للعلم والكتابة.',
    bio: 'عالم الدنيا وموسوعة التراث في القرن العاشر الهجري، ألف أكثر من 600 كتاب ومصنف خلدت اسم أسيوط في كبرى جامعات ومكتبات العالم.',
    quote: 'العلم شجرة طيبة أصلها ثابت وفرعها في السماء، وما نفع علم قط إلا إذا اقترن بالعمل والتقوى.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الأزهر الشريف ومخطوطات دار الكتب المصرية - قسم أسيوط',
    sourceUrl: 'https://www.azhar.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-manfalouti',
    name: 'الأديب مصطفى لطفي المنفلوطي',
    slug: 'mustafa-lutfi-al-manfaluti-asyut',
    titleOrRole: 'رائد الأدب الوجداني وأمير البيان والإنشاء العربي',
    craftOrSkill: 'الأدب الوجداني، المقال الأخلاقي، وتعريب روائع الأدب العالمي',
    craftTitle: 'أمير البيان الوجداني',
    governorateName: 'أسيوط',
    governorateId: 'gov-asyut',
    biography: 'ابن مدينة منفلوط بأسيوط (1876 - 1924)، صاحب أرق قلم وأعذب لغة عربية في مطلع القرن العشرين. اتعلم في الأزهر الشريف وتشرب فصاحة القرآن وبيانه الساحر. كتب مقالاته الشهيرة في كتاب «النظرات» و«العبرات»، وعرّب روايات غربية زي «مجدولين» و«الفضيلة» و«في سبيل التاج» بأسلوب خلاها أبلغ وأجمل من أصولها، وكانت كتاباته تبكي القراء لفرط صدقها ودفاعها عن الفقراء والمظلومين.',
    bio: 'ابن منفلوط بأسيوط، صاحب «النظرات» و«العبرات»، الذي صاغ أرق لغة عربية ومقالات وجدانية دافعت عن الضعفاء والمحرومين.',
    quote: 'إنما الرحمة منجاة.. وما جفت دمعة مظلوم إلا بفضل قسوة قلب غافل، فكونوا للناس رحمة.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 35,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة المصرية العامة للكتاب - أعلام منفلوط وأسيوط',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-deir-al-muharraq',
    name: 'حكاية دير المحرق ورحلة العائلة المقدسة',
    slug: 'deir-al-muharraq-holy-family-asyut',
    titleOrRole: 'رمز البركة والأمان وأطول محطة لجوء للعائلة المقدسة بالصعيد',
    craftOrSkill: 'التراث التاريخي الروحي ومسار العائلة المقدسة والتعايش الإنساني',
    craftTitle: 'حكاية القدس الثانية بالصعيد',
    governorateName: 'أسيوط',
    governorateId: 'gov-asyut',
    biography: 'في سفح جبل قسقام بمركز القوصية بأسيوط، يقع دير المحرق التاريخي، حيث أقامت السيدة مريم العذراء والسيد المسيح عليه السلام ويوسف النجار لمدة 6 أشهر وعشرة أيام، في أطول فترة استقرار لهم على أرض مصر هرباً من بطش هيرودس. كنيسة العذراء الأثرية هناك اتبنت في القرن الأول الميلادي، وتعتبر الكنيسة الوحيدة في العالم اللي دشنها السيد المسيح بيده بحسب التقليد الكنسي، والناس في أسيوط مسلمين ومسيحيين بيعتبروا المكان ده أقدس بقعة وبركة للبلد كلها.',
    bio: 'في جبل قسقام بالقوصية بأسيوط، استقرت العائلة المقدسة لأكثر من ستة أشهر؛ محطة أمان تاريخية يتبارك بها كل أهل الصعيد على مر العصور.',
    quote: 'مباركة مصر وشعبها.. ومن سفح جبل قسقام نبتت أقدم رسائل السلام والأمان في تاريخ الإنسانية.',
    avatarUrl: 'https://images.unsplash.com/photo-1548625361-195fe5787bf4?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1548625361-195fe5787bf4?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'وزارة السياحة والآثار - مسار العائلة المقدسة بدير المحرق',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'unesco',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 6. المنيا (gov-minya) - عروس الصعيد
  // ==========================================
  {
    id: 'person-taha-hussein',
    name: 'د. طه حسين (عميد الأدب العربي)',
    slug: 'dr-taha-hussein-minya',
    titleOrRole: 'عميد الأدب العربي وقاهر الظلام وباعث مجانية التعليم',
    craftOrSkill: 'الأدب العربي، النقد، الفلسفة، وتطوير التعليم المجاني',
    craftTitle: 'عميد الأدب العربي',
    governorateName: 'المنيا',
    governorateId: 'gov-minya',
    biography: 'ابن عزبة الكيلو بمركز مغاغة في المنيا (1889 - 1973)، قاهر ظلام العمى والفقر اللي حوّل محنته لمعجزة تاريخية في كتابه «الأيام». درس في الأزهر وجامعة القاهرة ونال الدكتوراه من جامعة السوربون بباريس. أصبح وزيراً للمعارف وخاض معارك فكرية جبارة لإرساء حرية التفكير، وأصر على أن يكون «التعليم كالماء والهواء حق لكل مواطن مصري»، ففتح أبواب المدارس والجامعات لملايين الفقراء وأبناء الفلاحين في الصعيد والدلتا.',
    bio: 'ابن مغاغة بالمنيا، قاهر الظلام وصاحب «الأيام»، الذي خاض أشرس المعارك التنويرية وجعل التعليم المجاني حقاً مقدساً كالماء والهواء لكل مصري.',
    quote: 'التعليم كالماء والهواء حق لكل مواطن.. ولا يمكن لأمة أن تبني مجداً وهي تحبس عقول أبنائها في ظلمات الجهل.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة العامة للاستعلامات ومتحف طه حسين (رامتان)',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-ammar-sherei',
    name: 'الموسيقار عمار الشريعي',
    slug: 'ammar-al-sherei-minya',
    titleOrRole: 'غواص النغم وعبقري الموسيقى التصويرية والدراما المصرية',
    craftOrSkill: 'التأليف الموسيقي، التلحين، النقد، وعزف الأورج الشرقي',
    craftTitle: 'غواص بحر النغم',
    governorateName: 'المنيا',
    governorateId: 'gov-minya',
    biography: 'ابن مدينة سمالوط بالمنيا (1948 - 2012)، عبقري الألحان اللي اتولد كفيفاً لكن بصيرته الموسيقية شافت أسرار الروح المصرية. صاغ تترات وموسيقى أعظم مسلسلات الدراما زي «رأفت الهجان»، «أرابيسك»، «زيزينيا»، «دموع في عيون وقحة»، و«حديث الصباح والمساء». كان فيلسوفاً موسيقياً بامتياز، وعلم الشعب المصري تذوق النغم من خلال برنامجه الإذاعي الساحر «غواص في بحر النغم».',
    bio: 'ابن سمالوط بالمنيا، عبقري الموسيقى التصويرية وصاحب تترات «رأفت الهجان» و«أرابيسك»، الذي رأى بنور قلبه وموهبته ما لم يره المبصرون.',
    quote: 'المزيكا سر ونبض إنساني بيكلم روحك مباشرة.. مفيش حاجز يقدر يمنع نغمة صادقة طالعة من صميم القلب.',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'معهد الموسيقى العربية وجمعية المؤلفين والملحنين - فرع المنيا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-sanaa-gamil',
    name: 'الفنانة الكبيرة سناء جميل',
    slug: 'sanaa-gamil-minya',
    titleOrRole: 'سيدة التمثيل الصادق وعملاقة المسرح والسينما المصرية',
    craftOrSkill: 'التمثيل التراجيدي والدرامي، المسرح القومي، وفن الأداء السينمائي',
    craftTitle: 'سيدة الأداء الدرامي الصادق',
    governorateName: 'المنيا',
    governorateId: 'gov-minya',
    biography: 'ثريا يوسف عطالله، وُلدت في مركز ملوي بالمنيا (1930 - 2002)، من أعظم ما أنجب الفن المصري في التجسيد الدرامي. هزت العالم بدور «نفيسة» في فيلم «بداية ونهاية» مع المخرج صلاح أبو سيف، وأبدعت في «الزوجة الثانية» و«سواق الأتوبيس» ومسلسل «الراية البيضا» بشخصية فضة المعداوي التي لا تُنسى. تميزت بالصلابة والاعتزاز بالنفس والإخلاص المطلق لخشبة المسرح القومي.',
    bio: 'ابنة ملوي بالمنيا، عملاقة التمثيل الصادق وبطلة «بداية ونهاية» و«الراية البيضا»، فنانة حفرت اسمها بأداء استثنائي يفيض عزة وكبرياء.',
    quote: 'الفن الصادق هو اللي بيحس بيه الغلبان قبل الغني، ومفيش تمثيل حقيقي بدون ما تحط قطعة من روحك في الدور.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أرشيف المسرح القومي والمركز القومي للسينما - أعلام المنيا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-huda-shaarawi',
    name: 'هدى شعراوي (رائدة النهضة النسائية)',
    slug: 'huda-shaarawi-minya',
    titleOrRole: 'رائدة النهضة النسائية والعمل الوطني والاجتماعي في مصر',
    craftOrSkill: 'العمل الوطني، تأسيس الاتحاد النسائي، وحركات التحرر الاجتماعي',
    craftTitle: 'رائدة النهضة النسائية المصرية',
    governorateName: 'المنيا',
    governorateId: 'gov-minya',
    biography: 'نور الهدى محمد سلطان شعراوي، وُلدت بمدينة المنيا سنة 1879، كريمة محمد سلطان باشا رئيس مجلس النواب. قادت مظاهرات ثورة 1919 التاريخية وأسست الاتحاد النسائي المصري للمطالبة بحق المرأة في التعليم الإلزامي والعمل والمشاركة السياسية. خاضت معارك وطنية واجتماعية كبرى من أجل كرامة الإنسان المصري ورفعة الوطن، وتركت أثراً تاريخياً خالداً انطلق من قلب المنيا.',
    bio: 'ابنة المنيا وقائدة مظاهرات 1919 ومؤسسة الاتحاد النسائي المصري، التي دافعت عن حق الفتيات في التعليم والكرامة المجتمعية.',
    quote: 'نهضة مصر لن تكتمل أبداً إلا بنهضة أبنائها وبناتها معاً كتفاً بكتف في ميادين العلم والعمل.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'سجل رواد النهضة المصرية والجمعية التاريخية بالمنيا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 7. بني سويف (gov-bani-suef)
  // ==========================================
  {
    id: 'person-taha-al-fashni',
    name: 'الشيخ طه الفشني',
    slug: 'sheikh-taha-al-fashni-benisuef',
    titleOrRole: 'كروان الإنشاد وسلطان المقامات والتواشيح الدينية النبوية',
    craftOrSkill: 'التواشيح والابتهالات الدينية، تلاوة القرآن، وإتقان المقامات الشرقية',
    craftTitle: 'سلطان التواشيح الدينية',
    governorateName: 'بني سويف',
    governorateId: 'gov-bani-suef',
    biography: 'ابن مركز الفشن ببني سويف (1900 - 1971)، سيد المنشدين وإمام المقرئين وصاحب الصوت الملائكي الفخم اللي دخل الإذاعة المصرية سنة 1937. اشتهر بموشحاته الخالدة زي «حب الحسين»، «ميلاد طه»، و«يا أيها المختار»، وكان أستاذاً كبيراً في المقامات الموسيقية المركبة. صوته في ليالي شهر رمضان وفجر الجمعة كان يملأ البيوت بطمأنينة وخشوع يغسل الهموم عن القلوب.',
    bio: 'ابن الفشن ببني سويف، كروان الإنشاد الديني وصاحب «حب الحسين» و«يا أيها المختار»، الصوت الملائكي الذي أطرب العالم الإسلامي خشوعاً.',
    quote: 'الصوت أمانة وموهبة من الخالق، والمديح في حضرة المصطفى دواء للقلوب وسكينة للأرواح التائهة.',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'إذاعة القرآن الكريم ونقابة قراء بني سويف والمنيا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-busiri',
    name: 'الإمام شرف الدين البوصيري',
    slug: 'imam-al-busiri-benisuef',
    titleOrRole: 'صاحب «قصيدة البردة» المباركة وسيد مادحي المصطفى',
    craftOrSkill: 'الشعر الصوفي، المديح النبوي، وفنون الخط العربي والتصوف',
    craftTitle: 'سيد شعراء المديح النبوي',
    governorateName: 'بني سويف',
    governorateId: 'gov-bani-suef',
    biography: 'عاش وترعرع في بني سويف بقرية بوش (مركز ناصر حالياً)، وخدم في دواوينها الإدارية. كتب أعظم قصيدة مديح نبوي في التاريخ «الكواكب الدرية في مدح خير البرية» المعروفة بـ «البردة» أو «البُرأة»، بعد أن شُفي من شلل نصفي أصابه ببركة نظمه للمدائح النبوية. كُرّمت قصيدته وتُرجمت لعشرات اللغات، وتزينت بأبياتها جدران المساجد والقصور في كل بقاع العالم الإسلامي.',
    bio: 'عاش بقرية بوش ببني سويف وكتب «قصيدة البردة» الخالدة التي أصبحت أشهر وأعذب مدائح الرسول في تاريخ الشعر العربي والإسلامي.',
    quote: 'مولاي صلّ وسلّم دائماً أبداً.. على حبيبك خير الخلق كلهم.. محمد سيد الكونين والثقلين.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'دار الكتب والوثائق القومية - تراث بني سويف الصوفي',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-kahlaoui',
    name: 'الشيخ محمد الكحلاوي (مداح الرسول)',
    slug: 'sheikh-mohamed-al-kahlaoui-benisuef',
    titleOrRole: 'مداح الرسول وشيخ الأغنية الشعبية الدينية البدوية والصعيدية',
    craftOrSkill: 'الإنشاد الصوفي، الغناء البدوي والصعيدي التراثي، والمدائح الشعبية',
    craftTitle: 'مداح الرسول',
    governorateName: 'بني سويف',
    governorateId: 'gov-bani-suef',
    biography: 'من كبار المداحين المصريين وجذوره العائلية مرتبطة بصعيد مصر وبني سويف، ترك الشهرة السينمائية والمسرحية وتفرغ تماماً للمديح النبوي الشعبي وأسس مسجده ومدرسته الصوفية الشهيرة. أغانيه زي «لأجل النبي»، «حب الرسول يابا دواني»، و«عليك سلام الله» بقت النشيد الروحي المحفور في وجدان كل بيت مصري في مواسم الحج والأعياد والمولد النبوي الشريف.',
    bio: 'شيخ الأغنية الدينية الشعبية وصاحب «لأجل النبي»، الذي سخر صوته وروحه لنشر محبة النبي في كل بيوت الصعيد ومصر.',
    quote: 'حب النبي سر الصفا والنجاة، والمديح طاقة نور بتفتح أبواب الخير والبركة في البيوت.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'سجل التراث الإنشادي المصري وجمعية محبي المداحين',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 8. الفيوم (gov-faiyum)
  // ==========================================
  {
    id: 'person-youssef-wahbi',
    name: 'عميد المسرح العربي يوسف وهبي',
    slug: 'youssef-wahbi-faiyum',
    titleOrRole: 'عميد المسرح العربي ورائد التراجيديا والتمثيل الدرامي',
    craftOrSkill: 'التمثيل المسرحي والسينمائي، التأليف، الإخراج، وإدارة الفرق المسرحية',
    craftTitle: 'عميد المسرح العربي',
    governorateName: 'الفيوم',
    governorateId: 'gov-faiyum',
    biography: 'وُلد في مدينة الفيوم سنة 1898، وكان والده عبد الله باشا وهبي مفتشاً كبيراً للري في الفيوم وصاحب مسجد عبد الله وهبي التاريخي هناك. تشرب يوسف وهبي شغفه الفني بين جناين الفيوم ومياه بحر يوسف، وسافر لإيطاليا لدراسة التمثيل، وأسس فرقة «رمسيس» المسرحية التي علمت أجيالاً من عمالقة الفن العربي. صاحب الصرخة المسرحية الشهيرة «يا للهول!» وأعظم من أرسى تقاليد المسرح الأخلاقي والتراجيدي في الشرق.',
    bio: 'ابن الفيوم وعميد المسرح العربي، مؤسس فرقة رمسيس التي أحدثت ثورة في فنون التمثيل والدراما العربية بمسرحياته وأفلامه الخالدة.',
    quote: 'المسرح مدرسة الشعب ومعبد الفن، وما الفن إلا رسالة مقدسة ترفع شأن الإنسان وتغرس فيه حب الفضيلة.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 55,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'المركز القومي للمسرح المصري وتاريخ مسرح رمسيس - الفيوم',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-evelyne-porret',
    name: 'إيفيلين بوريه (سيدة قرية تونس للخزف)',
    slug: 'evelyne-porret-tunis-village-faiyum',
    titleOrRole: 'صانعة معجزة قرية تونس الخزفية ومحولة القرية لعاصمة الفخار العالمية',
    craftOrSkill: 'صناعة الخزف والفخار اليدوي والتدريب الحرفي والتنمية الريفية',
    craftTitle: 'صانعة معجزة قرية تونس الخزفية',
    governorateName: 'الفيوم',
    governorateId: 'gov-faiyum',
    biography: 'فنانة سويسرية زارت قرية تونس المطلة على بحيرة قارون بالفيوم سنة 1965 وعشقت طبيعتها وسحرها الهادئ فقررت الاستقرار فيها لبقية حياتها. أنشأت مدرسة مجانية لتعليم أطفال وشباب القرية فنون تشكيل الخزف اليدوي بمزج طمي مصر بالتقنيات السويسرية، وحوّلت قرية فلاحية بسيطة لأشهر مقصد سياحي وفني عالمي في مصر، يعيش كل بيوتها على فنون الخزف والنحت حتى أصبحت رمزاً حقيقياً للوفاء لأرض الفيوم.',
    bio: 'عشقت الفيوم سنة 1965 وأسست مدرسة الخزف بقرية تونس، محولة قرية ريفية هادئة إلى ملتقى خزفي وفني دولي يقصده زوار العالم.',
    quote: 'طمي مصر فيه روح ساحرة لا توجد في مكان آخر، وأطفال قرية تونس فنانون بالفطرة يحتاجون فقط لمسة حب وثقة.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'جمعية فناني قرية تونس بالفيوم وقطاع الفنون التشكيلية',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'unesco',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-qaroun-lake-legend',
    name: 'حكاية بحيرة وقصر قارون الأسطورية',
    slug: 'legend-of-qaroun-faiyum',
    titleOrRole: 'ملحمة الكنوز والذهب وعبرة التاريخ الخالدة في وجدان الفيوم',
    craftOrSkill: 'التراث الشعبي الأسطوري، السير والحكايات الفلكلورية الشفاهية',
    craftTitle: 'حكاية كنوز قارون الأسطورية',
    governorateName: 'الفيوم',
    governorateId: 'gov-faiyum',
    biography: 'من أقدم وأشهر الحكايات الشعبية المتوارثة على ضفاف بحيرة قارون وقصر قارون بالفيوم، عن قارون وخزائنه التي كانت مفاتيحها تنوء بالعصبة أولي القوة، ولما طغى وبغى خسف الله به وبداره الأرض. يروي صيادو بحيرة قارون وأهالي القرى حكايات متوارثة عن قاع البحيرة ومعبد قصر قارون الذي تتعامد عليه الشمس في ظاهرة فلكية فريدة كل عام يوم 21 ديسمبر، كرمز للعبرة الإنسانية من عواقب الطمع والغرور.',
    bio: 'الحكاية الشعبية الأكثر شهرة في تاريخ الفيوم، عن قارون وخزائنه الغارقة ومعبده الفلكي النادر، درس في التواضع وعمارة الأرض بالعدل.',
    quote: 'الدنيا ظل زائل وخيراتها ملك للي يعمرها بالعدل والرحمة، لا بالكنز والخيلاء.',
    avatarUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أطلس المأثورات الشعبية المصرية - فرع الفيوم والآثار الإسلامية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 9. الوادي الجديد (gov-new-valley)
  // ==========================================
  {
    id: 'person-mostafa-moaz',
    name: 'الفنان التشكيلي مصطفى معاذ',
    slug: 'mostafa-moaz-new-valley',
    titleOrRole: 'فنان الواحات وموثق بيوت الطين ونخيل الصحراء الغربية',
    craftOrSkill: 'الفن التشكيلي، توثيق العمارة البيئية الطينية، والتراث الواحاتي',
    craftTitle: 'فنان الواحات التراثي',
    governorateName: 'الوادي الجديد',
    governorateId: 'gov-new-valley',
    biography: 'ابن واحة الداخلة بالوادي الجديد، الفنان التشكيلي الذي كرس حياته وريشته لرسم سحر الواحات وتاريخها العريق. وثق في لوحاته البيوت الطينية القديمة في مدينة القصر الإسلامية وأزقتها الضيقة وسقوفها المصنوعة من جذوع الدوم والنخيل، ووجوه الواحاتيين السمر الذين صمدوا في وجه قسوة الصحراء. شاركت لوحاته في كبرى المعارض المصرية والدولية ونال جوائز رفيعة تقديراً لحفظه للذاكرة البصرية لأهل الوادي.',
    bio: 'ابن واحة الداخلة، فنان تشكيلي كرس ريشته لتوثيق أزقة مدينة القصر الطينية وحقول النخيل ووجوه أهالي الوادي الجديد الصامدين.',
    quote: 'الواحة مش صحراء جرداء.. الواحة كنز حكايات ودفء إنساني محفوظ في جدران الطين ونخيل الأجداد.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'قطاع الفنون التشكيلية وقصر ثقافة الخارجة والداخلة',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-darb-al-arbaeen',
    name: 'حكاية درب الأربعين وقوافل الجمالة',
    slug: 'darb-al-arbaeen-camel-caravans-new-valley',
    titleOrRole: 'شريان التجارة الأسطوري وملحمة الصمود في الصحراء الكبرى',
    craftOrSkill: 'قصص قوافل الجمالة، علوم الفلك والنجوم الصحراوية، ودلالة الدروب',
    craftTitle: 'ملحمة درب الأربعين الصحراوية',
    governorateName: 'الوادي الجديد',
    governorateId: 'gov-new-valley',
    biography: 'الدرب التاريخي الأسطوري الذي يربط دارفور بالسودان عبر واحات باريس والخارجة بأسيوط، وكانت تقطعه قوافل الجمال في أربعين يوماً محملة بالريش والصمغ العربي والتوابل والأقمشة النادرة. أبطال هذا الطريق كانوا أدلاء الواحات وأصحاب «الدلالة» الذين يحفظون النجوم بالاسم ومسارات الآبار وعلامات الكثبان الرملية، وتوارث أهالي الوادي الجديد ملاحم بطولاتهم في مواجهة العواصف الرملية وحراسة القوافل بأمانة منقطعة النظير.',
    bio: 'طريق القوافل التاريخي الذي قطع الصحراء في 40 يوماً؛ ملحمة صمود وتجارة سطّرها أدلاء وجمالة الواحات بمعرفة فلكية وصبر لا يلين.',
    quote: 'من درب الأربعين اتعلمنا إن الصبر هو زاد الطريق، وإن رمال الصحراء بتكشف معدن الرجال.',
    avatarUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'مركز دراسات الصحراء المصرية وأطلس المأثورات بالوادي الجديد',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-hajj-abdelmonem-kharga',
    name: 'الحاج عبد المنعم الواحاتي (شيخ نساجي الكليم)',
    slug: 'abdelmonem-kilim-master-kharga',
    titleOrRole: 'أسطى الكليم الصوفي اليدوي وحارس النقوش الفراعنية بالواحات',
    craftOrSkill: 'نسيج الكليم والسجاد اليدوي، صباغة الصوف الطبيعي بقشور النباتات',
    craftTitle: 'شيخ نساجي الكليم بالخارجة',
    governorateName: 'الوادي الجديد',
    governorateId: 'gov-new-valley',
    biography: 'شيخ حرفيي نسيج الكليم والسجاد اليدوي في واحة الخارجة، شغال على نوله الخشبي التقليدي بقاله أكتر من 45 سنة. بيستخدم صوف الأغنام الواحاتية الأصيل، ويصبغه بمواد بيئية طبيعية من قشور الرمان والكركم ونباتات الصحراء، وينسج بإتقان نقوش النخيل والجمال والأهرامات التي تعبر عن هوية الوادي الجديد. علّم مئات الفتيات والسيدات الحرفة ليحافظ على بقاء الصنعة التراثية حية ومصدر رزق شريف لأهالي الواحة.',
    bio: 'شيخ نساجي الكليم اليدوي بواحة الخارجة، يغزل بصبر صوف الصحراء المصبوغ طبيعياً لينسج تاريخ الواحات ونخيلها على نوله الخشبي.',
    quote: 'الخيط لما يتنسج بالصبر والمحبة بيعيش مية سنة وأكتر ويفضل لونه زاهي كأنه لسه طالع من النول مبارح.',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'جهاز تنمية المشروعات الصغيرة والحرف التراثية بالوادي الجديد',
    sourceUrl: 'https://www.msmeda.org.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 10. البحر الأحمر (gov-red-sea)
  // ==========================================
  {
    id: 'person-abu-el-hassan-shazly',
    name: 'القطب الصوفي سيدي أبو الحسن الشاذلي',
    slug: 'sidi-abu-al-hassan-al-shadhili-red-sea',
    titleOrRole: 'سلطان الأولياء ومؤسس الطريقة الشاذلية بالصحراء الشرقية',
    craftOrSkill: 'الفكر الصوفي، حزب البحر، والتراث الروحي الإسلامي بالصحراء',
    craftTitle: 'سلطان الأولياء والعارفين',
    governorateName: 'البحر الأحمر',
    governorateId: 'gov-red-sea',
    biography: 'الإمام علي بن عبد الله الشاذلي (593 - 656 هـ)، القطب الصوفي الكبير ومؤسس إحدى أكبر الطرق الصوفية في العالم الإسلامي. وافته المنية في وادي حُميثرة بصحراء عيذاب بالبحر الأحمر وهو متوجه لأداء فريضة الحج. مقامه التاريخي في قلب الجبال الوعرة يقصده مئات الآلاف من الزوار من كل محافظات الصعيد ومصر في موسم الحج من كل عام في تظاهرة محبة وأخوة روحية نادرة، ويشتهر بدعائه الخالد «حزب البحر» الذي حفظه البحارة والمسافرون عبر القرون.',
    bio: 'سلطان الأولياء ومؤسس الطريقة الشاذلية، يرقد مقامه بوادي حُميثرة بصحراء البحر الأحمر ملتقى لمئات آلاف الزوار سنوياً في أبهى تظاهرة روحية.',
    quote: 'عليك بالاستغفار، وكن مع الله ترَ الله معك، واغرس محبة الخير في قلوب الخلق تسعد في الدارين.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'وزارة الأوقاف المصرية وتراث البحر الأحمر الصوفي بوادي حميثرة',
    sourceUrl: 'https://www.awqaf.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-hamed-el-beshari',
    name: 'الريس حامد البشارى (شيخ عازفي الطنبورة)',
    slug: 'hamed-al-beshari-tamboura-red-sea',
    titleOrRole: 'حارس نغم الصحراء الشرقية وسيد آلة الطنبورة بحلايب وشلاتين',
    craftOrSkill: 'عزف آلة الطنبورة الوترية، الغناء البدوي التراثي، وحفظ أشعار الصحراء',
    craftTitle: 'شيخ عازفي الطنبورة البدوية',
    governorateName: 'البحر الأحمر',
    governorateId: 'gov-red-sea',
    biography: 'ابن جبال علبة وصحراء حلايب وشلاتين بالبحر الأحمر، من أخلص وأشهر حراس التراث الموسيقي والشفاهي لقبائل العبابدة والبشارية. يعزف على آلة «الطنبورة» الوترية التراثية المصنوعة من الخشب وجلد الغزال، ويغني بصوته الشجي قصائد البادية عن الكرم، الفراسة، سباقات الهجن، وأسرار النجوم والرياح. يشارك في إحياء ليالي السمر البدوية ومهرجانات التراث ليضمن نقل ألحان الصحراء الشرقية للأجيال الشابة بكل نقاء.',
    bio: 'ابن حلايب وشلاتين وحارس تراث قبائل العبابدة والبشارية، يعزف على آلة الطنبورة ويشدو بأشعار الفراسة والكرم في ليالي الصحراء الشرقية.',
    quote: 'نغم الطنبورة هو صدى الجبال وهدير البحر الأحمر.. لحن ورثناه أباً عن جد ومستحيل يضيع في مهب الريح.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'قصر ثقافة الشلاتين وأطلس المأثورات الشعبية بالبحر الأحمر',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-captain-ibrahim-quseir',
    name: 'الربان عم إبراهيم القصيري (شيخ بحارة القصير)',
    slug: 'captain-ibrahim-quseir-red-sea',
    titleOrRole: 'حارس ذاكرة ميناء القصير التاريخي وسفن الحج والتجارة القديمة',
    craftOrSkill: 'الملاحة الشراعية، صيد الأسماك واللؤلؤ، ورواية تاريخ موانئ البحر الأحمر',
    craftTitle: 'شيخ بحارة القصير التاريخية',
    governorateName: 'البحر الأحمر',
    governorateId: 'gov-red-sea',
    biography: 'شيخ بحارة مدينة القصير أقدم موانئ البحر الأحمر، التي انطلقت منها رحلات الملكة حتشبسوت لبلاد بونت وسفن الحجيج وقوافل التجارة عبر العصور. قضى عم إبراهيم أكثر من 50 عاماً بين أمواج البحر الأحمر، حافظاً لأسماء الشعب المرجانية ومواسم هبوب الرياح الشمالية والجنوبية وأسرار صيد الأسماك واللؤلؤ القديم. يجتمع حوله الزوار والباحثون في مقاهي ميناء القصير ليستمعوا لحكاياته الشيقة عن بطولات البحارة وتاريخ السفن الشراعية.',
    bio: 'شيخ بحارة ميناء القصير، قضى نصف قرن في عرض البحر الأحمر حاملاً أسرار الملاحة الشراعية وقصص سفن الحج والتجارة القديمة.',
    quote: 'البحر الأحمر كريم للّي يصاحبه ويحترمه.. وفي جوفه وأعماقه تاريخ كل أمة عبرت من هنا نحو أرض الحجاز.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 52,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'جمعية الحفاظ على تراث القصير وتاريخ البحر الأحمر الملاحي',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

async function seedWahPeople() {
  const uri = process.env.MONGODB_URI;
  const dbName = process.env.MONGODB_DB || 'Elsa3ed_market';
  if (!uri) {
    console.error('MONGODB_URI is not set');
    process.exit(1);
  }

  const client = new MongoClient(uri);
  try {
    await client.connect();
    const db = client.db(dbName);
    const collection = db.collection('wah_local_people');

    console.log(`Connected to DB: ${dbName}`);
    console.log(`Total authentic figures to insert/update: ${AUTHENTIC_WAH_PEOPLE.length}`);

    // Clean up generic placeholders if any, or replace
    const deleteResult = await collection.deleteMany({
      id: {
        $in: [
          'person-om-hassan',
          'person-am-gad',
          'person-sheikh-fathy',
          'person-hajj-shaaban-palm',
          'person-mabrook-pottery-dakhla'
        ]
      }
    });
    console.log(`Deleted obsolete placeholders: ${deleteResult.deletedCount}`);

    for (const person of AUTHENTIC_WAH_PEOPLE) {
      await collection.updateOne(
        { id: person.id },
        { $set: person },
        { upsert: true }
      );
      console.log(`✓ Upserted: ${person.name} (${person.governorateName}) - ${person.titleOrRole}`);
    }

    const totalCount = await collection.countDocuments();
    console.log(`\n🎉 Total people now in wah_local_people collection: ${totalCount}`);

    // Verify governorate coverage
    const govCoverage = await collection.aggregate([
      { $group: { _id: '$governorateName', count: { $sum: 1 } } },
      { $sort: { count: -1 } }
    ]).toArray();

    console.log('\nGovernorate Coverage:');
    govCoverage.forEach(g => {
      console.log(` - ${g._id}: ${g.count} شخصية`);
    });

  } catch (err: any) {
    console.error('Seeding error:', err);
  } finally {
    await client.close();
  }
}

seedWahPeople();
