import type { LocalPersonDoc } from '../models/types.ts';

export const AUTHENTIC_WAH_PEOPLE: LocalPersonDoc[] = [
  // ==========================================
  // 1. قنا (gov-qena)
  // ==========================================
  {
    id: 'person-abnoudi',
    name: 'عبد الرحمن الأبنودي (الخال)',
    slug: 'abdelrahman-el-abnoudi-qena',
    titleOrRole: 'شاعر العامية الكبرى وحارس السيرة الهلالية',
    craftOrSkill: 'شعر العامية وحفظ التراث الشفاهي الصعيدي',
    governorateName: 'قنا',
    governorateId: 'gov-qena',
    biography: 'الخال عبد الرحمن الأبنودي ابن قرية أبنود في قنا، مفيش حد لمس وجع الصعايدة وفرحتهم وقعدتهم على المصطبة قده. قضى أكتر من عشرين سنة يلف القرى والنجوع على رجليه ورا شعراء الربابة علشان يجمع السيرة الهلالية بيتاً بيتاً من صدور الرواة ويحفظ ملحمة بني هلال بصوته للتاريخ. كلماته غناها كبار الفن زي عبد الحليم وشادية ومحمد رشدي ومحمد منير، وعلّم المصريين إزاي الكلمة الصعيدية البسيطة تهز الوجدان.',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 55,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أطلس المأثورات الشعبية وهيئة قصور الثقافة - قنا',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-abdelbaset',
    name: 'الشيخ عبد الباسط عبد الصمد',
    slug: 'sheikh-abdelbaset-abdessamad-qena',
    titleOrRole: 'الحنجرة الذهبية وصوت مكة وسفير القرآن للعالم',
    craftOrSkill: 'تلاوة القرآن الكريم وفنون المقامات الصوتية',
    governorateName: 'قنا',
    governorateId: 'gov-qena',
    biography: 'ابن قرية المراعزة بمركز أرمنت جنوب قنا، صوته كان هبة ربانية نادرة بتسري في الروح وتخشع ليها القلوب. حفظ القرآن وهو طفل صغير في كتاب قريته وتتلمذ على كبار شيوخ القراءات في الصعيد، ولما صوته انطلق من الإذاعة المصرية والحرم المكي سحر العالم كله. سافر لكل قارات الأرض يحمل كتاب الله بصوته اللي جمع بين الشجن الصعيدي الأصيل والنقاء الروحي اللي ملوش مثيل.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'نقابة قراء القرآن الكريم - سجل أعلام التلاوة بقنا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-amal-donqol',
    name: 'أمل دنقل (أمير شعراء الرفض)',
    slug: 'amal-donqol-qena',
    titleOrRole: 'أمير شعراء الرفض والكرامة الوطنية',
    craftOrSkill: 'الشعر العربي الحديث وقصيدة التفعيلة المقاومة',
    governorateName: 'قنا',
    governorateId: 'gov-qena',
    biography: 'محمد أمل فهيم محارب دنقل، وُلد في قرية القلعة بمركز قفط في قنا سنة 1940. الصعيدي النحيل الأسمر اللي كانت كلماته بتهز قلاع الظلم والاستسلام. استلهم شموخ جبال قنا وتراث كليلة ودمنة وجساس والزير سالم عشان يكتب أروع مراثي الكرامة زي «لا تصالح» و«كلمات سبارتاكوس الأخيرة» و«البكاء بين يدي زرقاء اليمامة». علامة فارقة في الضمير العربي وفخر لكل ابن من أبناء الصعيد.',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 30,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة العامة لقصور الثقافة - أعلام قفط وقنا',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-hefny-ahmed-hassan',
    name: 'الريس حفني أحمد حسن',
    slug: 'hefny-ahmed-hassan-qena',
    titleOrRole: 'إمبراطور الموال الصعيدي وسلطان فن الواو',
    craftOrSkill: 'الموال الصعيدي المرتجل، الغناء الشعبي، الملاحم الشعبية',
    governorateName: 'قنا',
    governorateId: 'gov-qena',
    biography: 'أسطورة الغناء الشعبي الصعيدي، ابن قنا صاحب الحنجرة الفولاذية اللي كانت بتزلزل الساحات والأفراح من أسوان للجيزة. كان معلماً ومرتجلًا عبقرياً في وزن القافية وفن الواو والموال الصعيدي الرباعي والخماسي. اشتهر بروايته لملحمة «شفيقة ومتولي» ومواويل الصبر والجدعنة وأصول الرجولة، وما زال صوته العريض علامة مسجلة للأصالة الصعيدية.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أرشيف الموسيقى الشعبية المصرية - فرع قنا والأقصر',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 2. الأقصر (gov-luxor)
  // ==========================================
  {
    id: 'person-ahmed-al-tayeb',
    name: 'فضيلة الإمام الأكبر د. أحمد الطيب',
    slug: 'sheikh-ahmed-el-tayeb-luxor',
    titleOrRole: 'شيخ الأزهر الشريف ورمز الوسطية والسلام العالمي',
    craftOrSkill: 'الفكر الفلسفي الإسلامي، التسامح، والصلح العرفي بالصعيد',
    governorateName: 'الأقصر',
    governorateId: 'gov-luxor',
    biography: 'ابن مدينة القرنة بالبر الغربي للأقصر، وريث الساحة الطيبية الصوفية التاريخية اللي بتفتح أبوابها ليل نهار لكل صاحب حاجة، ومقر أكبر جلسات الصلح العرفي وحقن الدماء بين عائلات وقبائل الصعيد. شخصية عالمية جمعت بين أرقى علوم الفلسفة الغربية والإسلامية وبين التواضع الصعيدي الجم والزهد الحقيقي، حامل راية وثيقة الأخوة الإنسانية والسلام العالمي.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'مشيخة الأزهر الشريف والساحة الطيبية بالقرنة',
    sourceUrl: 'https://www.azhar.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-yahya-taher',
    name: 'يحيى الطاهر عبد الله',
    slug: 'yahya-taher-abdullah-luxor',
    titleOrRole: 'شاعر القصة القصيرة الصعيدية وأديب الكرنك',
    craftOrSkill: 'القصة القصيرة والرواية وتصوير المجتمع الجنوبي',
    governorateName: 'الأقصر',
    governorateId: 'gov-luxor',
    biography: 'ابن قرية الكرنك بالأقصر (1938 - 1981)، ساحر الكلمات اللي كتب القصة القصيرة بلغة تشبه التراتيل الصوفية وأغاني الحصاد الفرعونية. خلّد أساطير ووجع الجنوب في روايته الفذة «الطوق والأسورة» ومجموعاته «الدف والصندوق» و«حكايات للأمير حتى ينام». كان لما يقعد يحكي قصة في قهوة، الناس تسكت تماماً كأنهم مسحورين بصوت راوي الصعيد الحقيقي.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 25,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة العامة لقصور الثقافة - أدباء الأقصر',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-abu-al-haggag',
    name: 'حكاية وسيرة سيدي أبو الحجاج الأقصري',
    slug: 'sidi-abu-al-haggag-luxor',
    titleOrRole: 'سلطان العارفين بالأقصر ورمز المحبة والتآخي الشعبي',
    craftOrSkill: 'التراث الصوفي الشعبي وموكب الدورة والموالد التاريخية',
    governorateName: 'الأقصر',
    governorateId: 'gov-luxor',
    biography: 'الشيخ يوسف بن عبد الرحيم الأقصري (المتوفى 642 هـ)، اللي مسجده معلق ومبني جوه أحضان معبد الأقصر الفرعوني في مشهد تاريخي فريد ملوش مثيل في العالم كله. يعتبره أهالي الأقصر رمزاً للبركة والأمان. مولده السنوي هو أكبر عرس شعبي وتراثي في الأقصر، بيخرج فيه موكب «الدورة» وتشارك فيه قوارب خشبية محمولة على الأكتاف ورجال التحطيب والخيول العربية في ملحمة حب وفرح لا تنتهي.',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'وزارة السياحة والآثار وتراث الأقصر الصوفي',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'unesco',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 3. أسوان (gov-aswan)
  // ==========================================
  {
    id: 'person-king-mounir',
    name: 'محمد منير (الكينج)',
    slug: 'king-mohamed-mounir-aswan',
    titleOrRole: 'صوت النوبة وسفير الأغنية المصرية المعاصرة للعالم',
    craftOrSkill: 'الغناء النوبي، المزج الموسيقي، وحفظ الهوية الجنوبية',
    governorateName: 'أسوان',
    governorateId: 'gov-aswan',
    biography: 'ابن منشية النوبة بأسوان، الأسمر اللي دخل كل بيت مصري من أول ما غنى «الليلة يا سمرا» و«شبابيك». خرج من جزر وشواطئ نيل أسوان حاملاً السلم الخماسي النوبي الأصيل ودمجه ببراعة مع الجاز والروك العالمي، وعبّر عن هموم الناس وحب الوطن والأرض بطريقة مفيش حد عرف يقلدها. منير مش مجرد مطرب، ده حالة وجدانية كاملة بتختصر دفء الصعيد وطيبة أهل النوبة.',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أكاديمية الفنون المصرية وأرشيف الموسيقى النوبية بأسوان',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-el-akkad',
    name: 'عباس محمود العقاد',
    slug: 'abbas-mahmoud-el-akkad-aswan',
    titleOrRole: 'عملاق الفكر والأدب العربي وصاحب العبقريات',
    craftOrSkill: 'الفلسفة، النقد الأدبي، التاريخ الإسلامي، والشعر',
    governorateName: 'أسوان',
    governorateId: 'gov-aswan',
    biography: 'ابن أسوان العصامي البار (1889 - 1964)، الصعيدي الجبل اللي علّم نفسه بنفسه ومعهوش غير الشهادة الابتدائية لحد ما بقى أضخم عقلية فكرية وأدبية في القرن العشرين. صاحب سلسلة «العبقريات» الإسلامية وأكتر من 100 كتاب أثروا المكتبة العربية. كان معروفاً بكبريائه الصعيدي المهيب وأنفته اللي رفضت الانحناء لأي سلطان، وقبره ومتحفه في وسط أسوان شاهدين على فخر الجنوب بيه.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'متحف العقاد بأسوان والهيئة العامة للاستعلامات',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-ahmed-mounib',
    name: 'الموسيقار أحمد منيب',
    slug: 'ahmed-mounib-aswan',
    titleOrRole: 'عراب وأب الموسيقى النوبية واللحن الجنوبي الأصيل',
    craftOrSkill: 'التلحين، العزف على العود، وصياغة الألحان النوبية الخماسية',
    governorateName: 'أسوان',
    governorateId: 'gov-aswan',
    biography: 'ابن قرية توماس وعافية بالنوبة بأسوان، الملحن الفذ وعازف العود اللي شكل الوجدان الموسيقي لجنوب مصر. هو اللي اكتشف وصاغ أشهر ألحان محمد منير زي «حدوتة مصرية»، «شجر الليمون»، «يا وعدي عالأيام»، و«شمندورة». كان صوته ولحنه بيحمل شجن التهجير وأمل العودة للنيل وحلاوة البيوت النوبية الملونة بالدفء والبهجة.',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'جمعية إحياء التراث النوبي بأسوان والمعهد العالي للموسيقى العربية',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 4. سوهاج (gov-sohag)
  // ==========================================
  {
    id: 'person-menshawy',
    name: 'الشيخ محمد صديق المنشاوي',
    slug: 'sheikh-mohamed-seddiq-menshawy-sohag',
    titleOrRole: 'الصوت الباكي وقيثارة السماء وسلطان الخشوع',
    craftOrSkill: 'تلاوة القرآن الكريم وتجويده والمقامات الروحانية العميقة',
    governorateName: 'سوهاج',
    governorateId: 'gov-sohag',
    biography: 'ابن مدينة المنشأة بسوهاج (1920 - 1969)، من عائلة قرآنية عريقة طلع منها والده وأخوه الشيخ محمود من كبار القراء. سُمي بـ «الصوت الباكي» لأن تلاوته كانت تنزل على القلوب بالدموع والخشوع الحقيقي، بدون أي تكلف أو استعراض. رفض كل مغريات الرؤساء والملوك وفضل يعيش بسيطاً وخالصاً لكتاب الله، وما زالت تسجيلاته للمصحف المرتل والمجود هي المرجع الأسمى للخشوع الإيماني.',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 35,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'إذاعة القرآن الكريم من القاهرة وسجل قراء سوهاج',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-tahtawi',
    name: 'الشيخ رفاعة رافع الطهطاوي',
    slug: 'refaa-al-tahtawi-sohag',
    titleOrRole: 'رائد التنوير والترجمة ومؤسس مدرسة الألسن والنهضة الحديثة',
    craftOrSkill: 'الفكر والتنوير والترجمة والنهضة التعليمية وبناء المدارس',
    governorateName: 'سوهاج',
    governorateId: 'gov-sohag',
    biography: 'ابن طهطا بسوهاج (1801 - 1873)، العالم الأزهري الصعيدي الذكي اللي بعته محمد علي باشا إماماً للبعثة المصرية لباريس، فرجع بعقلية نهضوية عظيمة وكتابه الشهير «تخليص الإبريز في تلخيص باريز». أسس مدرسة الألسن، وأشرف على حركة ترجمة آلاف الكتب العلمية، ونادى بتعليم البنات لأول مرة في مصر، ووضع أسس الدولة المصرية الحديثة على مبادئ العدل والمعرفة.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة العامة للاستعلامات - رواد الفكر والنهضة المصرية',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-ghitani',
    name: 'الروائي جمال الغيطاني',
    slug: 'gamal-el-ghitani-sohag',
    titleOrRole: 'صاحب «الزيني بركات» وحارس التراث والسرد التاريخي',
    craftOrSkill: 'الرواية، الصحافة الحربية، واستلهام التراث الصوفي والمملوكي',
    governorateName: 'سوهاج',
    governorateId: 'gov-sohag',
    biography: 'ابن قرية جهينة بسوهاج (1945 - 2015)، من أعمق الكتاب اللي حفروا في الهوية المصرية. كان مراسلاً حربياً شجاعاً على الجبهة في حربي الاستنزاف وأكتوبر المجيدة، وأسس جريدة «أخبار الأدب». استلهم التراث الشعبي والمملوكي والتصوف ليكتب تحفته الروائية «الزيني بركات» وسلسلة «دفاتر التدوين». ظل عاشقاً لأصوله السوهاجية ولعمق التاريخ الصعيدي حتى آخر يوم في حياته.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'اتحاد كتاب مصر وأرشيف أخبار الأدب - سوهاج',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'academic',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-george-sidhom',
    name: 'الفنان جورج سيدهم',
    slug: 'george-sidhom-sohag',
    titleOrRole: 'صانع البهجة وفيلسوف الضحكة ومؤسس ثلاثي أضواء المسرح',
    craftOrSkill: 'التمثيل المسرحي والسينمائي وفنون الكوميديا الراقية',
    governorateName: 'سوهاج',
    governorateId: 'gov-sohag',
    biography: 'ابن مدينة جرجا بسوهاج (1938 - 2020)، الفنان المحبوب صاحب الابتسامة الطيبة وخفة الدم الصعيدية الأصيلة. شكّل مع سمير غانم والضيف أحمد فرقة «ثلاثي أضواء المسرح» اللي غيرت شكل الكوميديا والاستعراض في العالم العربي. قدّم روائع مسرحية زي «المتزوجون» بشخصية حنفي الشهيرة، و«موسيقى في الحي الشرقي»، وأفلام سينمائية أسعدت كل الأسر المصرية على مدار أجيال.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'موسوعة السينما والمسرح المصري - الهيئة العامة للاستعلامات',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 5. أسيوط (gov-asyut)
  // ==========================================
  {
    id: 'person-samir-ghanem',
    name: 'الفنان الأسطورة سمير غانم',
    slug: 'samir-ghanem-asyut',
    titleOrRole: 'أسطورة الكوميديا وفطوطة الضحك المصري وأستاذ الارتجال',
    craftOrSkill: 'الكوميديا، التمثيل المسرحي، الفوازير الاستعراضية، وفن الإضحاك الفطري',
    governorateName: 'أسيوط',
    governorateId: 'gov-asyut',
    biography: 'ابن قرية عرب الأطاولة بمركز الفتح في أسيوط (1937 - 2021)، صانع البهجة الأكبر في تاريخ الفن العربي. كبر في أحضان أسيوط قبل ما يلتحق بكلية الزراعة في الإسكندرية وينطلق لتأسيس ثلاثي أضواء المسرح. أمتع كل بيت عربي بابتكاره لشخصية «فطوطة وسمورة» في فوازير رمضان، ومسرحيات أسطورية زي «أهلاً يا دكتور» و«المتزوجون» و«جحا يحكم المدينة». كان يرتجل على المسرح فيبكي الصالة من كتر الضحك ببراءة وعفوية صعيدية ملهاش مثيل.',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 55,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'سجل رواد الفن والمسرح المصري والهيئة العامة لقصور الثقافة بأسيوط',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-suyuti',
    name: 'الإمام جلال الدين السيوطي',
    slug: 'imam-jalal-al-din-al-suyuti-asyut',
    titleOrRole: 'موسوعة الفكر والتراث الإسلامي ومؤرخ الصعيد الأكبر',
    craftOrSkill: 'علوم الحديث والتفسير واللغة وتوثيق التاريخ الإسلامي',
    governorateName: 'أسيوط',
    governorateId: 'gov-asyut',
    biography: 'فخر أسيوط وعالم الدنيا في القرن العاشر الهجري (1445 - 1505 م)، الإمام عبد الرحمن بن أبي بكر السيوطي. موسوعة تمشي على الأرض، ألف أكتر من 600 مصنف وكتاب في التفسير والحديث والفقه واللغة والتاريخ، أشهرها «الإتقان في علوم القرآن»، «تفسير الجلالين»، و«تاريخ الخلفاء». خلد اسم محافظة أسيوط في أرجاء العالم الإسلامي كله من إسطنبول لمراكش، واعتزل الناس في جزيرة الروضة ليتفرغ للعلم والكتابة.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الأزهر الشريف ومخطوطات دار الكتب المصرية - قسم أسيوط',
    sourceUrl: 'https://www.azhar.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-manfalouti',
    name: 'الأديب مصطفى لطفي المنفلوطي',
    slug: 'mustafa-lutfi-al-manfaluti-asyut',
    titleOrRole: 'رائد الأدب الوجداني وأمير البيان والإنشاء العربي',
    craftOrSkill: 'الأدب الوجداني، المقال الأخلاقي، وتعريب روائع الأدب العالمي',
    governorateName: 'أسيوط',
    governorateId: 'gov-asyut',
    biography: 'ابن مدينة منفلوط بأسيوط (1876 - 1924)، صاحب أرق قلم وأعذب لغة عربية في مطلع القرن العشرين. اتعلم في الأزهر الشريف وتشرب فصاحة القرآن وبيانه الساحر. كتب مقالاته الشهيرة في كتاب «النظرات» و«العبرات»، وعرّب روايات غربية زي «مجدولين» و«الفضيلة» و«في سبيل التاج» بأسلوب خلاها أبلغ وأجمل من أصولها، وكانت كتاباته تبكي القراء لفرط صدقها ودفاعها عن الفقراء والمظلومين.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 35,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة المصرية العامة للكتاب - أعلام منفلوط وأسيوط',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-deir-al-muharraq',
    name: 'حكاية دير المحرق ورحلة العائلة المقدسة',
    slug: 'deir-al-muharraq-holy-family-asyut',
    titleOrRole: 'رمز البركة والأمان وأطول محطة لجوء للعائلة المقدسة بالصعيد',
    craftOrSkill: 'التراث التاريخي الروحي ومسار العائلة المقدسة والتعايش الإنساني',
    governorateName: 'أسيوط',
    governorateId: 'gov-asyut',
    biography: 'في سفح جبل قسقام بمركز القوصية بأسيوط، يقع دير المحرق التاريخي، حيث أقامت السيدة مريم العذراء والسيد المسيح عليه السلام ويوسف النجار لمدة 6 أشهر وعشرة أيام، في أطول فترة استقرار لهم على أرض مصر هرباً من بطش هيرودس. كنيسة العذراء الأثرية هناك اتبنت في القرن الأول الميلادي، وتعتبر الكنيسة الوحيدة في العالم اللي دشنها السيد المسيح بيده بحسب التقليد الكنسي، والناس في أسيوط مسلمين ومسيحيين بيعتبروا المكان ده أقدس بقعة وبركة للبلد كلها.',
    avatarUrl: 'https://images.unsplash.com/photo-1548625361-195fe5787bf4?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'وزارة السياحة والآثار - مسار العائلة المقدسة بدير المحرق',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'unesco',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 6. المنيا (gov-minya) - عروس الصعيد
  // ==========================================
  {
    id: 'person-taha-hussein',
    name: 'د. طه حسين (عميد الأدب العربي)',
    slug: 'dr-taha-hussein-minya',
    titleOrRole: 'عميد الأدب العربي وقاهر الظلام وباعث مجانية التعليم',
    craftOrSkill: 'الأدب العربي، النقد، الفلسفة، وتطوير التعليم المجاني',
    governorateName: 'المنيا',
    governorateId: 'gov-minya',
    biography: 'ابن عزبة الكيلو بمركز مغاغة في المنيا (1889 - 1973)، قاهر ظلام العمى والفقر اللي حوّل محنته لمعجزة تاريخية في كتابه «الأيام». درس في الأزهر وجامعة القاهرة ونال الدكتوراه من جامعة السوربون بباريس. أصبح وزيراً للمعارف وخاض معارك فكرية جبارة لإرساء حرية التفكير، وأصر على أن يكون «التعليم كالماء والهواء حق لكل مواطن مصري»، ففتح أبواب المدارس والجامعات لملايين الفقراء وأبناء الفلاحين في الصعيد والدلتا.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'الهيئة العامة للاستعلامات ومتحف طه حسين (رامتان)',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-ammar-sherei',
    name: 'الموسيقار عمار الشريعي',
    slug: 'ammar-al-sherei-minya',
    titleOrRole: 'غواص النغم وعبقري الموسيقى التصويرية والدراما المصرية',
    craftOrSkill: 'التأليف الموسيقي، التلحين، النقد، وعزف الأورج الشرقي',
    governorateName: 'المنيا',
    governorateId: 'gov-minya',
    biography: 'ابن مدينة سمالوط بالمنيا (1948 - 2012)، عبقري الألحان اللي اتولد كفيفاً لكن بصيرته الموسيقية شافت أسرار الروح المصرية. صاغ تترات وموسيقى أعظم مسلسلات الدراما زي «رأفت الهجان»، «أرابيسك»، «زيزينيا»، «دموع في عيون وقحة»، و«حديث الصباح والمساء». كان فيلسوفاً موسيقياً بامتياز، وعلم الشعب المصري تذوق النغم من خلال برنامجه الإذاعي الساحر «غواص في بحر النغم».',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'معهد الموسيقى العربية وجمعية المؤلفين والملحنين - فرع المنيا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-sanaa-gamil',
    name: 'الفنانة الكبيرة سناء جميل',
    slug: 'sanaa-gamil-minya',
    titleOrRole: 'سيدة التمثيل الصادق وعملاقة المسرح والسينما المصرية',
    craftOrSkill: 'التمثيل التراجيدي والدرامي، المسرح القومي، وفن الأداء السينمائي',
    governorateName: 'المنيا',
    governorateId: 'gov-minya',
    biography: 'ثريا يوسف عطالله، وُلدت في مركز ملوي بالمنيا (1930 - 2002)، من أعظم ما أنجب الفن المصري في التجسيد الدرامي. هزت العالم بدور «نفيسة» في فيلم «بداية ونهاية» مع المخرج صلاح أبو سيف، وأبدعت في «الزوجة الثانية» و«سواق الأتوبيس» ومسلسل «الراية البيضا» بشخصية فضة المعداوي التي لا تُنسى. تميزت بالصلابة والاعتزاز بالنفس والإخلاص المطلق لخشبة المسرح القومي.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أرشيف المسرح القومي والمركز القومي للسينما - أعلام المنيا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-huda-shaarawi',
    name: 'هدى شعراوي (رائدة النهضة النسائية)',
    slug: 'huda-shaarawi-minya',
    titleOrRole: 'رائدة النهضة النسائية والعمل الوطني والاجتماعي في مصر',
    craftOrSkill: 'العمل الوطني، تأسيس الاتحاد النسائي، وحركات التحرر الاجتماعي',
    governorateName: 'المنيا',
    governorateId: 'gov-minya',
    biography: 'نور الهدى محمد سلطان شعراوي، وُلدت بمدينة المنيا سنة 1879، كريمة محمد سلطان باشا رئيس مجلس النواب. قادت مظاهرات ثورة 1919 التاريخية وأسست الاتحاد النسائي المصري للمطالبة بحق المرأة في التعليم الإلزامي والعمل والمشاركة السياسية. خاضت معارك وطنية واجتماعية كبرى من أجل كرامة الإنسان المصري ورفعة الوطن، وتركت أثراً تاريخياً خالداً انطلق من قلب المنيا.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'سجل رواد النهضة المصرية والجمعية التاريخية بالمنيا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 7. بني سويف (gov-bani-suef)
  // ==========================================
  {
    id: 'person-taha-al-fashni',
    name: 'الشيخ طه الفشني',
    slug: 'sheikh-taha-al-fashni-benisuef',
    titleOrRole: 'كروان الإنشاد وسلطان المقامات والتواشيح الدينية النبوية',
    craftOrSkill: 'التواشيح والابتهالات الدينية، تلاوة القرآن، وإتقان المقامات الشرقية',
    governorateName: 'بني سويف',
    governorateId: 'gov-bani-suef',
    biography: 'ابن مركز الفشن ببني سويف (1900 - 1971)، سيد المنشدين وإمام المقرئين وصاحب الصوت الملائكي الفخم اللي دخل الإذاعة المصرية سنة 1937. اشتهر بموشحاته الخالدة زي «حب الحسين»، «ميلاد طه»، و«يا أيها المختار»، وكان أستاذاً كبيراً في المقامات الموسيقية المركبة. صوته في ليالي شهر رمضان وفجر الجمعة كان يملأ البيوت بطمأنينة وخشوع يغسل الهموم عن القلوب.',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'إذاعة القرآن الكريم ونقابة قراء بني سويف والمنيا',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-busiri',
    name: 'الإمام شرف الدين البوصيري',
    slug: 'imam-al-busiri-benisuef',
    titleOrRole: 'صاحب «قصيدة البردة» المباركة وسيد مادحي المصطفى',
    craftOrSkill: 'الشعر الصوفي، المديح النبوي، وفنون الخط العربي والتصوف',
    governorateName: 'بني سويف',
    governorateId: 'gov-bani-suef',
    biography: 'عاش وترعرع في بني سويف بقرية بوش (مركز ناصر حالياً)، وخدم في دواوينها الإدارية. كتب أعظم قصيدة مديح نبوي في التاريخ «الكواكب الدرية في مدح خير البرية» المعروفة بـ «البردة» أو «البُرأة»، بعد أن شُفي من شلل نصفي أصابه ببركة نظمه للمدائح النبوية. كُرّمت قصيدته وتُرجمت لعشرات اللغات، وتزينت بأبياتها جدران المساجد والقصور في كل بقاع العالم الإسلامي.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'دار الكتب والوثائق القومية - تراث بني سويف الصوفي',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-kahlaoui',
    name: 'الشيخ محمد الكحلاوي (مداح الرسول)',
    slug: 'sheikh-mohamed-al-kahlaoui-benisuef',
    titleOrRole: 'مداح الرسول وشيخ الأغنية الشعبية الدينية البدوية والصعيدية',
    craftOrSkill: 'الإنشاد الصوفي، الغناء البدوي والصعيدي التراثي، والمدائح الشعبية',
    governorateName: 'بني سويف',
    governorateId: 'gov-bani-suef',
    biography: 'من كبار المداحين المصريين وجذوره العائلية مرتبطة بصعيد مصر وبني سويف، ترك الشهرة السينمائية والمسرحية وتفرغ تماماً للمديح النبوي الشعبي وأسس مسجده ومدرسته الصوفية الشهيرة. أغانيه زي «لأجل النبي»، «حب الرسول يابا دواني»، و«عليك سلام الله» بقت النشيد الروحي المحفور في وجدان كل بيت مصري في مواسم الحج والأعياد والمولد النبوي الشريف.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'سجل التراث الإنشادي المصري وجمعية محبي المداحين',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 8. الفيوم (gov-faiyum)
  // ==========================================
  {
    id: 'person-youssef-wahbi',
    name: 'عميد المسرح العربي يوسف وهبي',
    slug: 'youssef-wahbi-faiyum',
    titleOrRole: 'عميد المسرح العربي ورائد التراجيديا والتمثيل الدرامي',
    craftOrSkill: 'التمثيل المسرحي والسينمائي، التأليف، الإخراج، وإدارة الفرق المسرحية',
    governorateName: 'الفيوم',
    governorateId: 'gov-faiyum',
    biography: 'وُلد في مدينة الفيوم سنة 1898، وكان والده عبد الله باشا وهبي مفتشاً كبيراً للري في الفيوم وصاحب مسجد عبد الله وهبي التاريخي هناك. تشرب يوسف وهبي شغفه الفني بين جناين الفيوم ومياه بحر يوسف، وسافر لإيطاليا لدراسة التمثيل، وأسس فرقة «رمسيس» المسرحية التي علمت أجيالاً من عمالقة الفن العربي. صاحب الصرخة المسرحية الشهيرة «يا للهول!» وأعظم من أرسى تقاليد المسرح الأخلاقي والتراجيدي في الشرق.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 55,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'المركز القومي للمسرح المصري وتاريخ مسرح رمسيس - الفيوم',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-evelyne-porret',
    name: 'إيفيلين بوريه (سيدة قرية تونس للخزف)',
    slug: 'evelyne-porret-tunis-village-faiyum',
    titleOrRole: 'صانعة معجزة قرية تونس الخزفية ومحولة القرية لعاصمة الفخار العالمية',
    craftOrSkill: 'صناعة الخزف والفخار اليدوي والتدريب الحرفي والتنمية الريفية',
    governorateName: 'الفيوم',
    governorateId: 'gov-faiyum',
    biography: 'فنانة سويسرية زارت قرية تونس المطلة على بحيرة قارون بالفيوم سنة 1965 وعشقت طبيعتها وسحرها الهادئ فقررت الاستقرار فيها لبقية حياتها. أنشأت مدرسة مجانية لتعليم أطفال وشباب القرية فنون تشكيل الخزف اليدوي بمزج طمي مصر بالتقنيات السويسرية، وحوّلت قرية فلاحية بسيطة لأشهر مقصد سياحي وفني عالمي في مصر، يعيش كل بيوتها على فنون الخزف والنحت حتى أصبحت رمزاً حقيقياً للوفاء لأرض الفيوم.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 50,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'جمعية فناني قرية تونس بالفيوم وقطاع الفنون التشكيلية',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'unesco',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-qaroun-lake-legend',
    name: 'حكاية بحيرة وقصر قارون الأسطورية',
    slug: 'legend-of-qaroun-faiyum',
    titleOrRole: 'ملحمة الكنوز والذهب وعبرة التاريخ الخالدة في وجدان الفيوم',
    craftOrSkill: 'التراث الشعبي الأسطوري، السير والحكايات الفلكلورية الشفاهية',
    governorateName: 'الفيوم',
    governorateId: 'gov-faiyum',
    biography: 'من أقدم وأشهر الحكايات الشعبية المتوارثة على ضفاف بحيرة قارون وقصر قارون بالفيوم، عن قارون وخزائنه التي كانت مفاتيحها تنوء بالعصبة أولي القوة، ولما طغى وبغى خسف الله به وبداره الأرض. يروي صيادو بحيرة قارون وأهالي القرى حكايات متوارثة عن قاع البحيرة ومعبد قصر قارون الذي تتعامد عليه الشمس في ظاهرة فلكية فريدة كل عام يوم 21 ديسمبر، كرمز للعبرة الإنسانية من عواقب الطمع والغرور.',
    avatarUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'أطلس المأثورات الشعبية المصرية - فرع الفيوم والآثار الإسلامية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 9. الوادي الجديد (gov-new-valley)
  // ==========================================
  {
    id: 'person-mostafa-moaz',
    name: 'الفنان التشكيلي مصطفى معاذ',
    slug: 'mostafa-moaz-new-valley',
    titleOrRole: 'فنان الواحات وموثق بيوت الطين ونخيل الصحراء الغربية',
    craftOrSkill: 'الفن التشكيلي، توثيق العمارة البيئية الطينية، والتراث الواحاتي',
    governorateName: 'الوادي الجديد',
    governorateId: 'gov-new-valley',
    biography: 'ابن واحة الداخلة بالوادي الجديد، الفنان التشكيلي الذي كرس حياته وريشته لرسم سحر الواحات وتاريخها العريق. وثق في لوحاته البيوت الطينية القديمة في مدينة القصر الإسلامية وأزقتها الضيقة وسقوفها المصنوعة من جذوع الدوم والنخيل، ووجوه الواحاتيين السمر الذين صمدوا في وجه قسوة الصحراء. شاركت لوحاته في كبرى المعارض المصرية والدولية ونال جوائز رفيعة تقديراً لحفظه للذاكرة البصرية لأهل الوادي.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'قطاع الفنون التشكيلية وقصر ثقافة الخارجة والداخلة',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-darb-al-arbaeen',
    name: 'حكاية درب الأربعين وقوافل الجمالة',
    slug: 'darb-al-arbaeen-camel-caravans-new-valley',
    titleOrRole: 'شريان التجارة الأسطوري وملحمة الصمود في الصحراء الكبرى',
    craftOrSkill: 'قصص قوافل الجمالة، علوم الفلك والنجوم الصحراوية، ودلالة الدروب',
    governorateName: 'الوادي الجديد',
    governorateId: 'gov-new-valley',
    biography: 'الدرب التاريخي الأسطوري الذي يربط دارفور بالسودان عبر واحات باريس والخارجة بأسيوط، وكانت تقطعه قوافل الجمال في أربعين يوماً محملة بالريش والصمغ العربي والتوابل والأقمشة النادرة. أبطال هذا الطريق كانوا أدلاء الواحات وأصحاب «الدلالة» الذين يحفظون النجوم بالاسم ومسارات الآبار وعلامات الكثبان الرملية، وتوارث أهالي الوادي الجديد ملاحم بطولاتهم في مواجهة العواصف الرملية وحراسة القوافل بأمانة منقطعة النظير.',
    avatarUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'مركز دراسات الصحراء المصرية وأطلس المأثورات بالوادي الجديد',
    sourceUrl: 'https://www.sis.gov.eg',
    sourceType: 'academic',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-hajj-abdelmonem-kharga',
    name: 'الحاج عبد المنعم الواحاتي (شيخ نساجي الكليم)',
    slug: 'abdelmonem-kilim-master-kharga',
    titleOrRole: 'أسطى الكليم الصوفي اليدوي وحارس النقوش الفراعنية بالواحات',
    craftOrSkill: 'نسيج الكليم والسجاد اليدوي، صباغة الصوف الطبيعي بقشور النباتات',
    governorateName: 'الوادي الجديد',
    governorateId: 'gov-new-valley',
    biography: 'شيخ حرفيي نسيج الكليم والسجاد اليدوي في واحة الخارجة، شغال على نوله الخشبي التقليدي بقاله أكتر من 45 سنة. بيستخدم صوف الأغنام الواحاتية الأصيل، ويصبغه بمواد بيئية طبيعية من قشور الرمان والكركم ونباتات الصحراء، وينسج بإتقان نقوش النخيل والجمال والأهرامات التي تعبر عن هوية الوادي الجديد. علّم مئات الفتيات والسيدات الحرفة ليحافظ على بقاء الصنعة التراثية حية ومصدر رزق شريف لأهالي الواحة.',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 45,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'جهاز تنمية المشروعات الصغيرة والحرف التراثية بالوادي الجديد',
    sourceUrl: 'https://www.msmeda.org.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },

  // ==========================================
  // 10. البحر الأحمر (gov-red-sea)
  // ==========================================
  {
    id: 'person-abu-el-hassan-shazly',
    name: 'القطب الصوفي سيدي أبو الحسن الشاذلي',
    slug: 'sidi-abu-al-hassan-al-shadhili-red-sea',
    titleOrRole: 'سلطان الأولياء ومؤسس الطريقة الشاذلية بالصحراء الشرقية',
    craftOrSkill: 'الفكر الصوفي، حزب البحر، والتراث الروحي الإسلامي بالصحراء',
    governorateName: 'البحر الأحمر',
    governorateId: 'gov-red-sea',
    biography: 'الإمام علي بن عبد الله الشاذلي (593 - 656 هـ)، القطب الصوفي الكبير ومؤسس إحدى أكبر الطرق الصوفية في العالم الإسلامي. وافته المنية في وادي حُميثرة بصحراء عيذاب بالبحر الأحمر وهو متوجه لأداء فريضة الحج. مقامه التاريخي في قلب الجبال الوعرة يقصده مئات الآلاف من الزوار من كل محافظات الصعيد ومصر في موسم الحج من كل عام في تظاهرة محبة وأخوة روحية نادرة، ويشتهر بدعائه الخالد «حزب البحر» الذي حفظه البحارة والمسافرون عبر القرون.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 60,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'وزارة الأوقاف المصرية وتراث البحر الأحمر الصوفي بوادي حميثرة',
    sourceUrl: 'https://www.awqaf.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-hamed-el-beshari',
    name: 'الريس حامد البشارى (شيخ عازفي الطنبورة)',
    slug: 'hamed-al-beshari-tamboura-red-sea',
    titleOrRole: 'حارس نغم الصحراء الشرقية وسيد آلة الطنبورة بحلايب وشلاتين',
    craftOrSkill: 'عزف آلة الطنبورة الوترية، الغناء البدوي التراثي، وحفظ أشعار الصحراء',
    governorateName: 'البحر الأحمر',
    governorateId: 'gov-red-sea',
    biography: 'ابن جبال علبة وصحراء حلايب وشلاتين بالبحر الأحمر، من أخلص وأشهر حراس التراث الموسيقي والشفاهي لقبائل العبابدة والبشارية. يعزف على آلة «الطنبورة» الوترية التراثية المصنوعة من الخشب وجلد الغزال، ويغني بصوته الشجي قصائد البادية عن الكرم، الفراسة، سباقات الهجن، وأسرار النجوم والرياح. يشارك في إحياء ليالي السمر البدوية ومهرجانات التراث ليضمن نقل ألحان الصحراء الشرقية للأجيال الشابة بكل نقاء.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 40,
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'قصر ثقافة الشلاتين وأطلس المأثورات الشعبية بالبحر الأحمر',
    sourceUrl: 'https://www.moc.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'person-captain-ibrahim-quseir',
    name: 'الربان عم إبراهيم القصيري (شيخ بحارة القصير)',
    slug: 'captain-ibrahim-quseir-red-sea',
    titleOrRole: 'حارس ذاكرة ميناء القصير التاريخي وسفن الحج والتجارة القديمة',
    craftOrSkill: 'الملاحة الشراعية، صيد الأسماك واللؤلؤ، ورواية تاريخ موانئ البحر الأحمر',
    governorateName: 'البحر الأحمر',
    governorateId: 'gov-red-sea',
    biography: 'شيخ بحارة مدينة القصير أقدم موانئ البحر الأحمر، التي انطلقت منها رحلات الملكة حتشبسوت لبلاد بونت وسفن الحجيج وقوافل التجارة عبر العصور. قضى عم إبراهيم أكثر من 50 عاماً بين أمواج البحر الأحمر، حافظاً لأسماء الشعب المرجانية ومواسم هبوب الرياح الشمالية والجنوبية وأسرار صيد الأسماك واللؤلؤ القديم. يجتمع حوله الزوار والباحثون في مقاهي ميناء القصير ليستمعوا لحكاياته الشيقة عن بطولات البحارة وتاريخ السفن الشراعية.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    yearsOfExperience: 52,
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    sourceName: 'جمعية الحفاظ على تراث القصير وتاريخ البحر الأحمر الملاحي',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: new Date().toISOString()
  }
];
