import type {
  GovernorateDoc,
  HeritagePlaceDoc
} from '../models/types.ts';

export const ADDITIONAL_GOVERNORATES: GovernorateDoc[] = [
  {
    id: 'gov-faiyum',
    name: 'الفيوم',
    slug: 'faiyum',
    nickname: 'أرض السواقي والخزف وواحة مصر الخضراء',
    shortIntro: 'واحة التاريخ والجمال الطبيعي، تجمع بين مهد الحضارات المبكرة وسواقي الهدير وبحيرة قارون ومحمية وادي الحيتان المصنفة تراثاً عالمياً لليونسكو.',
    history: 'تعد الفيوم من أقدم بقاع الاستيطان البشري في مصر عبر حضارتي الفيوم (أ) و(ب) منذ العصر الحجري، وازدهرت في عصر الدولة الوسطى حين استصلح ملوك الأسرة 12 بحيرة قارون ونظموا الري ببحر يوسف وأقاموا أهرامات هوارة واللاهون. كما تميزت في العصرين البطلمي والروماني ببورتريهات الفيوم الشهيرة وعمارتها الخزفية الريفية.',
    famousFor: [
      'محمية وادي الحيتان (يونسكو)',
      'سواقي الهدير التاريخية',
      'قرية تونس وفن الخزف',
      'محمية وادي الريان والشلالات',
      'بحيرة قارون وقصر قارون'
    ],
    capitalCity: 'مدينة الفيوم',
    region: 'شمال الصعيد',
    nileSegment: 'بحر يوسف وبحيرة قارون',
    mapCoordinates: { lat: 29.3084, lng: 30.8428 },
    coverImage: 'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    traditionalCraftsIds: ['craft-pottery', 'craft-palm'],
    traditionalFoodIds: ['food-fayesh', 'food-mesh'],
    culturalTraditions: ['مهرجان تونس السنوي للخزف', 'أغاني وسير السواقي', 'صيد الأسماك ببحيرة قارون'],
    status: 'approved',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'gov-red-sea',
    name: 'البحر الأحمر',
    slug: 'red-sea',
    nickname: 'بوابة قوافل الصعيد وحصن القصير التاريخي',
    shortIntro: 'ملتقى صحراء الصعيد الشرقية بشواطئ البحر الأحمر، موطن موانئ قوافل الحج ودرب وادي الحمامات وقلاع الفراعنة والعثمانيين التاريخية في القصير.',
    history: 'ارتبط البحر الأحمر جغرافياً واقتصادياً وتاريخياً بوادي النيل ومحافظات الصعيد (قنا والأقصر وقفط) عبر درب وادي الحمامات ومناجم الذهب والأحجار الكريمة، وميناء القصير القديم (ميناء ساو الفرعوني) الذي انطلقت منه رحلات حتشبسوت لبلاد بونت، وحصن القصير العثماني الذي شيده السلطان سليم الأول لحماية قوافل حجاج الصعيد والتجارة البحرية.',
    famousFor: [
      'قلعة القصير التاريخية',
      'درب قوافل وادي الحمامات',
      'ميناء القصير التراثي',
      'بيوت الحجر المرجاني القديمة'
    ],
    capitalCity: 'مدينة الغردقة (ومدينة القصير التاريخية)',
    region: 'جنوب الصعيد',
    nileSegment: 'دروب وادي الحمامات والبحر الأحمر',
    mapCoordinates: { lat: 26.1070, lng: 34.2800 },
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80'
    ],
    traditionalCraftsIds: ['craft-palm'],
    traditionalFoodIds: [],
    culturalTraditions: ['أهازيج الصيادين والسمسمية', 'رحلات قوافل الحجاج الصعايدة', 'عادات قبائل العبابدة والبشارية'],
    status: 'approved',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const ADDITIONAL_HERITAGE_PLACES: HeritagePlaceDoc[] = [
  // ================= أسوان =================
  {
    id: 'place-kom-ombo',
    title: 'معبد كوم أمبو ومتحف التماسيح',
    slug: 'kom-ombo-temple',
    governorateId: 'gov-aswan',
    governorateName: 'أسوان',
    category: 'temple',
    historicalEra: 'العصر البطلمي والروماني',
    description: 'معبد فريد على هضبة عالية تشرف على النيل مباشرة، يتميز بتصميمه المزدوج النادر المقسم لمحورين متوازيين مكرسين لسوبك إله التمساح وحورس الأكبر، ويضم نقوش الأدوات الطبية الجراحية ومتحفاً للتماسيح المحنطة.',
    history: 'شُيد المعبد في العصر البطلمي في عهد بطليموس السادس وفيلومتور وأكمله الأباطرة الرومان. الموقع كان محطة إستراتيجية على طرق قوافل النوبة ومصائد التماسيح النيلية. يتفرد بنقوش جدارية تجسد أقدم أدوات الجراحة والولادة في العالم القديم كالمشارط والملاقط وميزان الصيدلة، وبجواره مقياس نيل دائري فريد ومتحف التماسيح الذي يضم مومياوات لتماسيح ضخمة كانت تحنط تقديساً لسوبك.',
    significance: 'يعد المعبد المزدوج الوحيد الباقي في العمارة المصرية القديمة بنظام محوري متطابق، ووثيقة أثرية شاهدة على تقدم الطب والجراحة المصرية القديمة.',
    locationName: 'مدينة كوم أمبو، أسوان',
    locationDescription: 'يقع على ربوة مرتفعة مباشرة على الضفة الشرقية لنهر النيل بمدينة كوم أمبو شمال أسوان بنحو 45 كم.',
    visitorTips: 'استمتع بمشاهدة غروب الشمس وانعكاس إضاءة المعبد الليلية على النيل، وخصص وقتاً لزيارة متحف التماسيح المحنطة بجوار بوابة الخروج.',
    coverImage: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 24.4522, lng: 32.9283 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة ونصف لساعتين',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة السياحية',
      visitStatusNote: 'الموقع ومتحف التماسيح مفتوحان يومياً بتذكرة موحدة تشمل المعبد والمتحف.',
      openingHours: 'يومياً من 7:00 ص حتى 9:00 م (مضاء ليلاً)',
      bestTimeToVisit: 'فترة ما بعد العصر حتى المساء لمشاهدة الغروب والإضاءة الليلية الساحرة',
      entryFee: 'وفق لائحة وزارة السياحة والآثار (الدفع بالبطاقات البنكية)',
      reservationRequired: false
    },
    access: {
      description: 'يمكن الوصول بالسيارات والتاكسي عبر طريق أسوان - القاهرة الزراعي، أو عبر الفنادق العائمة (الكروز النيلي) التي ترسو أمام المعبد.',
      transportation: 'متاح سيارات الأجرة من موقف كوم أمبو أو حافلات الرحلات السياحية أو البواخر النيلية'
    },
    address: { governorate: 'أسوان', city: 'كوم أمبو' },
    sourceName: 'وزارة السياحة والآثار المصرية - قطاع الآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-edfu',
    title: 'معبد إدفو العظيم (معبد حورس)',
    slug: 'edfu-temple-horus',
    governorateId: 'gov-aswan',
    governorateName: 'أسوان',
    category: 'temple',
    historicalEra: 'العصر البطلمي',
    description: 'أضخم وأكمل معبد باقٍ بالكامل في العمارة المصرية القديمة بعد الكرنك، شُيد تكريساً للمعبود حورس الإدفوي ويحتفظ بسقفه وصروحه الشاهقة ونقوش الصراع الأسطوري بين حورس وست.',
    history: 'استغرق بناء المعبد نحو 180 عاماً (بين عامي 237 و57 ق.م) بدءاً من عهد بطليموس الثالث وحتى بطليموس الثاني عشر. حفظته رمال الصحراء لقرون حتى اكتشفه عالم الآثار مارييت عام 1860 سليماً بروعة ألوانه وتفاصيل سقوفه ونوافذه الحجرية. يضم صرحاً عملاقاً بارتفاع 36 متراً، وتمثالي حورس الصقر الجرانيتيين الشهيرين، ومقصورة الزورق المقدس وقدس الأقداس بناووسه النادر من الجرانيت الأسود.',
    significance: 'يعد المرجع الأكمل في العالم لهندسة وتفاصيل المعابد المصرية القديمة وطقوسها الدينية اليومية ونصوص أسطورة انتصار الخير.',
    locationName: 'مدينة إدفو، أسوان',
    locationDescription: 'يقع غرب النيل بقلب مدينة إدفو شمال محافظة أسوان بحوالي 100 كم.',
    visitorTips: 'ينصح بالوصول الصباحي المبكر لتجنب الازدحام، وركوب الحنطور التقليدي من مرسى النيل إلى المعبد كتجربة محلية شهيرة.',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 24.9780, lng: 32.8735 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعتين إلى ساعتين ونصف',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة السياحية',
      visitStatusNote: 'المعبد مفتوح بالكامل ويشمل الدخول لجميع القاعات وصالات الأعمدة والبهو المكشوف.',
      openingHours: 'يومياً من 7:00 ص حتى 5:00 م',
      bestTimeToVisit: 'فترة الصباح الباكر من 7:00 حتى 10:00 صباحاً',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار الرسمية المعتمدة',
      reservationRequired: false
    },
    access: {
      description: 'متاح بالقطار أو سيارات الأجرة من أسوان أو الأقصر، كما يمثل محطة توقف أساسية لكافة رحلات الكروز النيلي.',
      transportation: 'قطار الصعيد، ميكروباص من أسوان أو الأقصر، أو حناطير إدفو من المرسى'
    },
    address: { governorate: 'أسوان', city: 'إدفو' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-unfinished-obelisk',
    title: 'المسلة الناقصة ومحاجر الجرانيت بأسوان',
    slug: 'unfinished-obelisk-aswan',
    governorateId: 'gov-aswan',
    governorateName: 'أسوان',
    category: 'historical',
    historicalEra: 'الدولة الحديثة - عهد الملكة حتشبسوت',
    description: 'أضخم مسلة صخرية منحوتة في العالم القديم ما زالت متصلة بالصخر الأم بمحاجر الجرانيت الوردي، تكشف أسرار العبقرية الهندسية للمصريين القدماء في قطع الصخور الصلدة.',
    history: 'شُرع في نحتها بأمر من الملكة حتشبسوت لتنقل إلى معابد الكرنك، ولو اكتملت لبلغ ارتفاعها قرابة 42 متراً ووزنها نحو 1168 طناً لتكون أثقل قطعة حجرية منحوتة في تاريخ البشرية القديم. تسبب ظهور شق مفاجئ في الصخر في التوقف عن فصلها، مما وفر سجلاً أثرياً فريداً يوضح أدوات الحفر بكرات حجر الديوريت واستخدام أوتاد الخشب والماء لفلق الحجارة.',
    significance: 'موقع تعليمي وتوثيقي عالمي لا مثيل له يكشف تقنيات تعدين وهندسة صخور الجرانيت عند الفراعنة.',
    locationName: 'جنوب مدينة أسوان',
    locationDescription: 'تقع في المحاجر الجنوبية القديمة بالقرب من المقابر الفاطمية بمدينة أسوان.',
    visitorTips: 'الصعود يتم عبر ممرات وسلالم خشبية مؤمنة؛ يفضل ارتداء حذاء مريح وكاب واقٍ من الشمس، وأفضل وقت للتصوير هو الصباح.',
    coverImage: 'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 24.0768, lng: 32.8944 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'حوالي ساعة',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة السياحية',
      visitStatusNote: 'الموقع مجهز بمسار مشاة آمن ومركز معلومات ومجسم توضيحي لتقنيات النحت.',
      openingHours: 'يومياً من 7:00 ص حتى 5:00 م',
      bestTimeToVisit: 'الصباح الباكر',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار (الدفع الإلكتروني)',
      reservationRequired: false
    },
    access: {
      description: 'تبعد دقائق معدودة عن وسط مدينة أسوان ومحطة القطار.',
      transportation: 'تاكسي أسوان الداخلي أو الحافلات السياحية'
    },
    address: { governorate: 'أسوان', city: 'أسوان' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-nubian-museum',
    title: 'متحف النوبة بأسوان',
    slug: 'nubian-museum-aswan',
    governorateId: 'gov-aswan',
    governorateName: 'أسوان',
    category: 'museum',
    historicalEra: 'من عصور ما قبل التاريخ حتى العصر الحديث',
    description: 'أيقونة معمارية وثقافية حائزة على جائزة أغاخان للعمارة، يوثق تاريخ وحضارة وتراث بلاد النوبة الإنساني وفنونها وحملة اليونسكو الدولية لإنقاذ آثار النوبة.',
    history: 'افتتح عام 1997 كثمرة لحملة اليونسكو الدولية الكبرى لإنقاذ آثار النوبة من الغرق عقب بناء السد العالي. صممه المعماري المصري محمود الحكيم برؤية تستلهم العمارة النوبية والصخور الجرانيتية؛ يضم المتحف قاعات عرض مكيفة وحديقة متحفية مفتوحة تحاكي البيئة النوبية ومجرى النيل وكهوف العصر الحجري ومجسمات بالحجم الطبيعي للحياة والطقوس النوبية.',
    significance: 'أهم مركز وثائقي وتراثي في إفريقيا لحفظ وتوثيق اللغة والتراث والعمارة النوبية.',
    locationName: 'طريق الفنادق، مدينة أسوان',
    locationDescription: 'يقع على ربوة صخرية بالقرب من فندق كتاراكت القديم والمقابر الفاطمية بمدينة أسوان.',
    visitorTips: 'لا تفوت التجول في الحديقة المتحفية والمغارة الحجرية وقسم العادات والتقاليد الشعبية النوبية.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 24.0792, lng: 32.8893 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعتين إلى ثلاث ساعات',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للجمهور والزوار',
      visitStatusNote: 'المتحف يعمل بفترتين يومياً (صباحية ومسائية) ومجهز بالكامل لذوي الهمم.',
      openingHours: 'يومياً على فترتين: 9:00 ص - 1:00 م ومن 5:00 م - 9:00 م',
      bestTimeToVisit: 'الفترة المسائية للاستمتاع بحديقة المتحف والإضاءة الهادئة',
      entryFee: 'تذاكر وزارة السياحة والآثار (خصم خاص للطلاب المصريين)',
      reservationRequired: false
    },
    access: {
      description: 'يقع في قلب مدينة أسوان بالقرب من كورنيش النيل.',
      transportation: 'متاح بالتاكسي أو سيراً من كورنيش النيل وطريق الفنادق'
    },
    address: { governorate: 'أسوان', city: 'أسوان' },
    sourceName: 'قطاع المتاحف - وزارة السياحة والآثار',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-elephantine',
    title: 'جزيرة إلفنتين ومقياس النيل الأثري',
    slug: 'elephantine-island-nilometer',
    governorateId: 'gov-aswan',
    governorateName: 'أسوان',
    category: 'historical',
    historicalEra: 'من عصور ما قبل الأسرات وحتى العصر الروماني',
    description: 'الجزيرة الخالدة في وسط نيل أسوان وعاصمة الإقليم الأول لمصر القديمة، تحتضن مقاييس النيل الحجرية الرومانية وبقايا معابد خنوم وقريتي سيتي والكوبانية النوبيتين.',
    history: 'كانت الجزيرة تسمى "أبو" (أرض العاج) ونقطة الانطلاق التجارية والعسكرية نحو الجنوب. تضم مقياس النيل الروماني المنحوت في الصخر بدرجاته الـ 90 الشهيرة التي كان الكهنة يسجلون عليها مناسيب فيضان النيل لتحديد الضرائب، وأطلال معبد خنوم وساتت، ومتحف جزيرة إلفنتين القديم.',
    significance: 'أحد أقدم مراكز الحكم والقياس الهيدروليكي في حوض النيل وشاهد على التعايش الحضاري والنوبي.',
    locationName: 'جزيرة إلفنتين، وسط نيل أسوان',
    locationDescription: 'جزيرة نيلية كبرى تواجه كورنيش أسوان وتفصل بين ضفتي النيل.',
    visitorTips: 'الوصول عبر الفلوكة النيلية أو المعدية العامة، وتجول على الأقدام بين الآثار والقرية النوبية.',
    coverImage: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 24.0850, lng: 32.8860 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعتين إلى ثلاث ساعات',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة',
      visitStatusNote: 'المنطقة الأثرية ومقياس النيل بتذاكر الآثار، والقرية النوبية مفتوحة مجاناً للتجول.',
      openingHours: 'يومياً من 8:00 ص حتى 5:00 م',
      bestTimeToVisit: 'عصراً قبل الغروب للاستمتاع برحلة المعدية والنيل',
      entryFee: 'تذاكر الآثار للمنطقة الأثرية + تذكرة رمزية للمعدية النيلية',
      reservationRequired: false
    },
    access: {
      description: 'الوصول فقط عبر نهر النيل بواسطة معدية الأهالي العامة أو المراكب الشراعية (الفلوكة) من الكورنيش.',
      transportation: 'المعدية النيلية من مرسى الكورنيش أو مراكب الفلوكة الشراعية'
    },
    address: { governorate: 'أسوان', city: 'أسوان' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= الأقصر =================
  {
    id: 'place-luxor-temple',
    title: 'معبد الأقصر وطريق الكباش الأثري',
    slug: 'luxor-temple-avenue-sphinxes',
    governorateId: 'gov-luxor',
    governorateName: 'الأقصر',
    category: 'temple',
    historicalEra: 'الدولة الحديثة والعصور اللاحقة',
    description: 'درة طيبة على ضفاف النيل مباشرة، شيده الملك أمنحتب الثالث وأكمله رمسيس الثاني لمواكب عيد الأوبت المقدس، ويرتبط بمعابد الكرنك عبر طريق الكباش الأسطوري المرمم بطول 2.7 كم.',
    history: 'بُني المعبد تقريباً عام 1400 ق.م وكان المحراب الأكبر لتجديد شباب وشريعة الملك وعيد الأوبت الذي ينتقل فيه آمون رع من الكرنك إلى الأقصر. يضم صرح رمسيس الثاني الشامخ ومسلته الوردية الشهيرة وتماثيله العملاقة، وصالة أعمدة أمنحتب الثالث الرائعة، ويعلو جزءاً من جدرانه جامع سيدي أبي الحجاج الأقصري المشيد في العصر الأيوبي في مزيج تاريخي قل نظيره.',
    significance: 'أحد أشهر مواقع التراث العالمي لليونسكو وطريق الكباش المرمم يعد أكبر متحف أثري مفتوح في العالم.',
    locationName: 'كورنيش النيل، وسط مدينة الأقصر',
    locationDescription: 'يقع في قلب مدينة الأقصر بمواجهة النيل مباشرة ونقطة بداية طريق الكباش التاريخي.',
    visitorTips: 'من أروع المعابد التي يمكن زيارتها ليلاً حيث تضاء جدرانه وأعمدته بأنظمة إضاءة احترافية تسحر الألباب.',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 25.6995, lng: 32.6396 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعتان',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة نهاراً وليلاً',
      visitStatusNote: 'المعبد مفتوح حتى العاشرة مساءً وطريق الكباش متاح للتجول.',
      openingHours: 'يومياً من 6:00 ص حتى 10:00 م (مضاء بالكامل ليلاً)',
      bestTimeToVisit: 'فترة ما قبل الغروب والمساء للاستمتاع بالإضاءة البديعة وأجواء الكورنيش',
      entryFee: 'تذاكر معتمدة من وزارة السياحة والآثار (دفع بالفيزا)',
      reservationRequired: false
    },
    access: {
      description: 'يقع بقلب الأقصر، خطوات من محطة القطار وسوق الأقصر السياحي وفنادق الكورنيش.',
      transportation: 'سيراً على الأقدام من وسط المدينة، أو بالتاكسي والحنطور'
    },
    address: { governorate: 'الأقصر', city: 'الأقصر' },
    sourceName: 'وزارة السياحة والآثار المصرية - موقع آثار الأقصر',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-valley-queens',
    title: 'وادي الملكات ومقبرة نفرتاري الأسطورية',
    slug: 'valley-of-the-queens-nefertari',
    governorateId: 'gov-luxor',
    governorateName: 'الأقصر',
    category: 'tomb',
    historicalEra: 'الدولة الحديثة (الأسرات 18 - 20)',
    description: 'الجبانة الملكية للأميرات والملكات في البر الغربي، تحتضن مقبرة الملكة نفرتاري الجميلة (QV66) زوجة رمسيس الثاني، والتي تصنف كأعظم وأدق وأبهى الجداريات الملونة المحفوظة في تاريخ البشرية.',
    history: 'كان يطلق عليه في النصوص القديمة "تا-ست-نفرو" أي مكان الجمال والكمال. يضم ما يزيد عن 90 مقبرة محفورة في باطن الجبل؛ وتعد مقبرة الملكة نفرتاري درة الوادي حيث صُورت الملكة برفقة الآلهة بنقوش بارزة ملونة تحتفظ بنضارتها الأصلية وشفافية ملابسها وحليها الملكية؛ إلى جانب مقابر الأمراء الصغار خع إم واست وآمون حر خبشف.',
    significance: 'مقبرة نفرتاري هي أيقونة الفن التشكيلي المصري القديم ومدرجة على قائمة التراث العالمي لليونسكو.',
    locationName: 'البر الغربي، الأقصر',
    locationDescription: 'يقع في الطرف الجنوبي للجبانة الطيبة بالبر الغربي بالأقصر.',
    visitorTips: 'مقبرة نفرتاري تتطلب تذكرة دخول خاصة ومحددة بوقت للحفاظ على بيئة الألوان داخل المقبرة من الرطوبة.',
    coverImage: 'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 25.7285, lng: 32.5930 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة ونصف لساعتين',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة السياحية',
      visitStatusNote: 'يشمل الوادي 3 مقابر رئيسية عامة، ومقبرة نفرتاري تباع تذكرتها المستقلة بالمركز الرئيسي للزوار.',
      openingHours: 'يومياً من 6:00 ص حتى 5:00 م',
      bestTimeToVisit: 'الصباح الباكر',
      entryFee: 'تذكرة عامة لوادي الملكات + تذكرة خاصة لمقبرة نفرتاري',
      reservationRequired: false
    },
    access: {
      description: 'بالسيارات وحافلات الجولات السياحية عبر كوبري الأقصر العلوي أو معدية الأهالي للبر الغربي.',
      transportation: 'تاكسي البر الغربي أو سيارات الجولات المنظمة'
    },
    address: { governorate: 'الأقصر', city: 'القرنة' },
    sourceName: 'وزارة السياحة والآثار المصرية واليونسكو',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-colossi-memnon',
    title: 'تمثالا ممنون وصرح أمنحتب الثالث',
    slug: 'colossi-of-memnon',
    governorateId: 'gov-luxor',
    governorateName: 'الأقصر',
    category: 'historical',
    historicalEra: 'الدولة الحديثة - الأسرة 18 (عهد أمنحتب الثالث)',
    description: 'عملاقا الحجر الرملي الكوارتزي الشامخان في البر الغربي بارتفاع 18 متراً ووزن 720 طناً للتمثال، كانا يحرسان بوابة المعبد الجنائزي لأمنحتب الثالث واشتهرا بأسطورة غناء الفجر الإغريقية.',
    history: 'نُحت التمثالان حوالي عام 1350 ق.م من كتل صخرية جلبت من محاجر الجبل الأحمر قرب القاهرة الحالية. تهدم المعبد الجنائزي الملحق بزلزال قديم سنة 27 ق.م، وتسبب تصدع التمثال الشمالي في إحداث صفير نغمي مميز عند شروق الشمس أسماه الإغريق والرومان "نشيد ممنون لبطل طروادة". يمثلان اليوم المعلم الترحيبي الأبرز لكل زوار البر الغربي.',
    significance: 'أضخم تمثالين جالسين في مصر القديمة يوثقان تطور النحت الضخم والظواهر الصوتية التاريخية.',
    locationName: 'طريق القرنة السياحي، البر الغربي، الأقصر',
    locationDescription: 'يقعان في الفضاء المفتوح على الطريق الرئيسي المؤدي لوادي الملوك ومعابد البر الغربي.',
    visitorTips: 'المعلم مفتوح في الفضاء العام على الطريق، ولا يتطلب تذاكر؛ ينصح بالتوقف عنده صباحاً للتصوير في ضوء الشروق.',
    coverImage: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 25.7206, lng: 32.6105 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: '30 إلى 45 دقيقة',
    visitInfo: {
      visitStatus: 'public_landmark',
      visitStatusLabel: 'معلم أثري عام مفتوح مجاناً',
      visitStatusNote: 'الموقع مفتوح مباشرة على جانب الطريق السياحي ومتاح للمشاهدة والتصوير مجاناً دون بوابات أو تذاكر.',
      openingHours: 'متاح على مدار 24 ساعة يومياً',
      bestTimeToVisit: 'شروق الشمس والصباح الباكر',
      entryFee: 'مجاناً بالكامل (معلم عام بالطريق المفتوح)',
      reservationRequired: false
    },
    access: {
      description: 'على الطريق الرئيسي المباشر للبر الغربي عند مدخل مدينة القرنة.',
      transportation: 'تاكسي أو حافلة سياحية أو دراجات هوائية من معدية البر الغربي'
    },
    address: { governorate: 'الأقصر', city: 'القرنة' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-medinet-habu',
    title: 'معبد مدينة هابو لرمسيس الثالث',
    slug: 'medinet-habu-temple',
    governorateId: 'gov-luxor',
    governorateName: 'الأقصر',
    category: 'temple',
    historicalEra: 'الدولة الحديثة - الأسرة 20',
    description: 'أفضل معابد البر الغربي حفظاً لألوانه الزاهية وأسواره العسكرية الحصينة، يشتهر ببوابته السورية العالية ونقوشه الغائرة التي توثق حروب رمسيس الثالث ضد شعوب البحر.',
    history: 'شيده الملك رمسيس الثالث كمعبد جنائزي ومركز إداري محصن محاط بأسوار طوب لبن مزدوجة وقصر ملكي. تميزت نقوش جدرانه بنحت شديد العمق أمر به الملك ليضمن عدم محو أسمائه وتخليد انتصاراته، وما زالت الأسقف الملونة في صالة الأعمدة تحتفظ بزرقتها وتفاصيلها وكأنها لُوّنت بالأمس.',
    significance: 'يعد وثيقة تاريخية وعسكرية فريدة لصد هجمات شعوب البحر عن سواحل مصر وحفظ فنون النحت البارز والغائر.',
    locationName: 'مدينة هابو، القرنة، الأقصر',
    locationDescription: 'يقع في الجزء الجنوبي من مقابر ومعابد البر الغربي لمدينة الأقصر.',
    visitorTips: 'ارفع بصرك للأعلى في صالات الأعمدة لرؤية ألوان السماء والنجوم والنسور الملكية المحفوظة ببراعة.',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 25.7198, lng: 32.5999 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة ونصف لساعتين',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة السياحية',
      visitStatusNote: 'المعبد متاح بالكامل للزيارة بجميع أروقته وأبوابه الحصينة.',
      openingHours: 'يومياً من 6:00 ص حتى 5:00 م',
      bestTimeToVisit: 'فترة الصباح أو الظهيرة حين تضيء الشمس نقوش الصالات الداخلية',
      entryFee: 'تذاكر رسمية لوزارة السياحة والآثار',
      reservationRequired: false
    },
    access: {
      description: 'بالقرب من وادي الملكات وتمثالي ممنون بالبر الغربي.',
      transportation: 'سيارات الأجرة أو حافلات الرحلات السياحية بالبر الغربي'
    },
    address: { governorate: 'الأقصر', city: 'القرنة' },
    sourceName: 'وزارة السياحة والآثار المصرية واليونسكو',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-ramesseum',
    title: 'معبد الرامسيوم الجنائزي لرمسيس الثاني',
    slug: 'the-ramesseum-luxor',
    governorateId: 'gov-luxor',
    governorateName: 'الأقصر',
    category: 'temple',
    historicalEra: 'الدولة الحديثة - الأسرة 19',
    description: 'المعبد الجنائزي العظيم الذي خلده الشاعر شيلي بقصيدة "أوزيماندياس"، يحتضن صروح رمسيس الثاني وصوامع الغلال المقبية من الطوب اللبن وبقايا تمثاله العملاق المنهار.',
    history: 'بناه رمسيس الثاني الأكبر تخليداً لاسمه وعبادة المعبود آمون؛ وكان يضم مدرسة للكتاب ومكتبة كبرى تضم آلاف البرديات العلمية وصوامع تخزين الحبوب والغلال المقببة التي لا تزال قائمة منذ أكثر من 3200 عام شاهداً على براعة البناء بالطوب اللبن. وفي فنائه يرقد تمثال رمسيس الجرانيتي الضخم الذي كان يزن قرابة 1000 طن قبل انهياره بزلزال قديم.',
    significance: 'شاهد استثنائي على الهندسة الزراعية والإدارية للدولة الحديثة ومصدر إلهام لأعظم أعمال الأدب العالمي.',
    locationName: 'شمال القرنة، البر الغربي، الأقصر',
    locationDescription: 'يقع بين معبد حتشبسوت ومدينة هابو بالقرب من مقابر النبلاء.',
    visitorTips: 'تمشى خلف المعبد لاستكشاف أروقة صوامع الغلال المقببة المبنية من الطوب اللبن فهي تحفة معمارية مدهشة.',
    coverImage: 'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 25.7278, lng: 32.6106 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعة ونصف',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة السياحية',
      visitStatusNote: 'الموقع مفتوح يومياً بتذاكر وزارة السياحة والآثار.',
      openingHours: 'يومياً من 6:00 ص حتى 5:00 م',
      bestTimeToVisit: 'الصباح الباكر',
      entryFee: 'تذاكر وزارة السياحة والآثار (الدفع الإلكتروني)',
      reservationRequired: false
    },
    access: {
      description: 'عبر طريق معابد البر الغربي بالأقصر.',
      transportation: 'تاكسي البر الغربي أو الدراجات الهوائية'
    },
    address: { governorate: 'الأقصر', city: 'القرنة' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= قنا =================
  {
    id: 'place-youssef-kamal-palace',
    title: 'قصر البرنس يوسف كمال بنجع حمادي',
    slug: 'prince-youssef-kamal-palace',
    governorateId: 'gov-qena',
    governorateName: 'قنا',
    category: 'historical',
    historicalEra: 'أوائل القرن العشرين (1908م)',
    description: 'تحفة معمارية إسلامية وأندلسية وأوروبية نادرة على ضفاف نيل نجع حمادي، شيده البرنس الفنان يوسف كمال مؤسس مدرسة الفنون الجميلة في مصر وسط حدائق خلابة.',
    history: 'أنشئ القصر عام 1908م على يد مهندس إيطالي بتكليف من الأمير يوسف كمال أحد أثرياء أسرة محمد علي وأبرز رواد العمل الخيري والفني. يتكون المجمع من قصر السلاملك وقصر الحرملك واستراحة ومسجد بطراز أندلسي متميز ومئذنة رشيقة، ويتميز بزخارف الأرابيسك والزجاج المعشق بالجبس وأسقف الخشب المجلوبة من أوروبا وحدائق تضم أشجاراً معمرة.',
    significance: 'مسجل كأثر إسلامي وحضاري بارز، ويجسد قمة التمازج بين التراث الإسلامي والطراز الكلاسيكي الحديث.',
    locationName: 'مدينة نجع حمادي، محافظة قنا',
    locationDescription: 'يقع على كورنيش النيل بمدينة نجع حمادي شمال غرب قنا بنحو 55 كم.',
    visitorTips: 'استمتع بالتجول في حدائق القصر ومشاهدة تفاصيل المشربيات والأسقف المذهبة ومقتنيات الأمير.',
    coverImage: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 26.0489, lng: 32.2412 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة ونصف لساعتين',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية',
      visitStatusNote: 'القصر والحدائق التابعة مفتوحة للزوار بإشراف قطاع الآثار الإسلامية والقبطية.',
      openingHours: 'يومياً من 9:00 ص حتى 4:00 م',
      bestTimeToVisit: 'فترة الصباح حتى الواحدة ظهراً',
      entryFee: 'وفق تذاكر الآثار الإسلامية والقبطية الرسمية',
      reservationRequired: false
    },
    access: {
      description: 'بالقرب من محطة سكة حديد نجع حمادي وطريق مصر أسوان الزراعي.',
      transportation: 'تاكسي نجع حمادي الداخلي أو قطار الصعيد'
    },
    address: { governorate: 'قنا', city: 'نجع حمادي' },
    sourceName: 'قطاع الآثار الإسلامية والقبطية - وزارة السياحة والآثار',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-naqada-heritage',
    title: 'مدينة الحرفيين والأديرة التاريخية بنقادة',
    slug: 'naqada-heritage-town',
    governorateId: 'gov-qena',
    governorateName: 'قنا',
    category: 'heritage_village',
    historicalEra: 'عصور ما قبل الأسرات والتراث القبطي والشعبي',
    description: 'مهد حضارات ما قبل الأسرات (نقادة 1 و2 و3) وعاصمة صناعة نسيج "الفركة" اليدوية على الأنوال الخشبية، وموطن أقدم الأديرة القبطية الصحراوية كدير الملاك ميخائيل والأنبا بسنتاؤس.',
    history: 'سجلت نقادة اسمها في تاريخ الحضارة الإنسانية باكتشافات عالم الآثار فلندرز بتري لمقابر وحضارة نقادة التي مهدت لتوحيد مصر القديمة. وظلت عبر التاريخ مركزاً فريداً لصناعة شال "الفركة" المصنوع من خيوط الحرير والكتان المصدر للسودان وإفريقيا، وتحتضن أديرة عتيقة شيدت في القرنين الخامس والسادس الميلادي كدير الملاك ميخائيل ودير الصليب.',
    significance: 'تجمع حي فريد بين أعرق حضارات التاريخ القديم وحرفة نسيج يدوية متوارثة وأديرة تاريخية في حضن النيل والصحراء.',
    locationName: 'مدينة نقادة، جنوب قنا',
    locationDescription: 'تقع على الضفة الغربية لنهر النيل جنوب محافظة قنا وشمال الأقصر بنحو 25 كم.',
    visitorTips: 'احرص على زيارة ورش صناعة الفركة في منازل الحرفيين، والتعرف على دق النول اليدوي واقتناء شال تذكاري أصيل.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 25.9030, lng: 32.7230 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعتين إلى ثلاث ساعات',
    visitInfo: {
      visitStatus: 'public_landmark',
      visitStatusLabel: 'مدينة وقرى حرفية عامة مفتوحة',
      visitStatusNote: 'مدينة نقادة وقراها وورش الأنوال اليدوية مفتوحة للتجول والتسوق المباشر من الحرفيين دون تذاكر دخول، والأديرة مفتوحة للزيارة والصلوات.',
      openingHours: 'يومياً من 9:00 ص حتى 5:00 م',
      bestTimeToVisit: 'فترة الصباح حتى العصر لمشاهدة عمل الأنوال اليدوية',
      entryFee: 'مجاناً للتجول وزيارة الورش والأديرة',
      reservationRequired: false
    },
    access: {
      description: 'متاحة عبر الطريق الغربي الزراعي بين قنا والأقصر أو معديات النيل.',
      transportation: 'سيارات الأجرة (الميكروباص) من قنا أو الأقصر'
    },
    address: { governorate: 'قنا', city: 'نقادة' },
    sourceName: 'الهيئة العامة للاستعلامات ومحافظة قنا',
    sourceUrl: 'http://www.qena.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-qus-al-amri-mosque',
    title: 'المسجد العمري الأثري بقوص ومحطة قوافل الحج',
    slug: 'al-amri-mosque-qus',
    governorateId: 'gov-qena',
    governorateName: 'قنا',
    category: 'mosque',
    historicalEra: 'العصر الفاطمي والأيوبي والمملوكي',
    description: 'درة مدينة قوص عاصمة الصعيد القديمة، يحتضن أحد أقدم ثلاثة منابر خشبية باقية في العالم الإسلامي يعود للعام 550 هـ ومحراباً جصياً فاطمياً بالغ الروعة.',
    history: 'كانت مدينة قوص في العصرين الفاطمي والمملوكي ثاني أعظم مدن مصر بعد القاهرة وملتقى حجاج الصعيد والتجارة المتجهة لميناء عيذاب والبحر الأحمر. والمسجد العمري هو المسجد الجامع للمدينة، ويضم منبراً خشبياً حُفر بأمر الوزير الصالح طلائع بن رزيك عام 550 هـ بزخارف نبوية وهندسية بديعة خالية من المسامير، بالإضافة لمئذنة عتيقة ومقاصير أثرية.',
    significance: 'يعد منبر قوص تحفة خشبية نادرة لا تقدر بثمن في تاريخ الفنون الإسلامية عالمياً.',
    locationName: 'مدينة قوص، جنوب قنا',
    locationDescription: 'يقع في قلب مدينة قوص القديمة شرق النيل جنوب محافظة قنا.',
    visitorTips: 'تأمل دقة حفر المنبر الخشبي الفاطمي والمحراب الجصي في جدار القبلة بهدوء ووقار.',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 25.9185, lng: 32.7628 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعة',
    visitInfo: {
      visitStatus: 'active_institution',
      visitStatusLabel: 'مسجد أثري وصرح ديني نشط',
      visitStatusNote: 'المسجد تقام فيه الصلوات الخمس ومفتوح للمصلين والزوار مجاناً دون تذاكر سياحية تجارية، مع مراعاة أوقات الصلاة والسكينة.',
      openingHours: 'مفتوح طوال اليوم لمواقيت الصلاة ومن 8:00 ص حتى صلاة العشاء',
      bestTimeToVisit: 'بين وقتي الظهر والعصر لمشاهدة الزخارف بنور النهار',
      entryFee: 'مجاناً بالكامل',
      reservationRequired: false
    },
    access: {
      description: 'يقع بوسط مدينة قوص بجوار المحطة وميدان المدينة.',
      transportation: 'قطار الصعيد إلى محطة قوص أو ميكروباص من قنا أو الأقصر'
    },
    address: { governorate: 'قنا', city: 'قوص' },
    sourceName: 'وزارة السياحة والآثار - قطاع الآثار الإسلامية والقبطية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= سوهاج =================
  {
    id: 'place-red-monastery',
    title: 'الدير الأحمر (دير الأنبا بيشوي والأنبا بيجول)',
    slug: 'red-monastery-sohag',
    governorateId: 'gov-sohag',
    governorateName: 'سوهاج',
    category: 'monastery',
    historicalEra: 'القرن الخامس الميلادي (العصر القبطي البيزنطي)',
    description: 'معجزة الفريسكو والرسوم الجدارية الملونة في الشرق الأدنى، يحتضن أروع جداريات قبطية وبيزنطية ملونة محفوظة بالكامل في العالم المسيحي المبكر.',
    history: 'شُيد بالآجر الأحمر في القرن الخامس الميلادي بغرب سوهاج. خضعت كنيسته الأثرية وهيكلها لمشروع ترميم دولي بقيادة مركز البحوث الأمريكي ووزارة الآثار المصرية، كشف عن طبقات متراكبة من اللوحات الجدارية التي صورت السيدة العذراء والرسل والملائكة بألوان طبيعية براقة أبهرت مؤرخي الفنون التشكيلية حول العالم.',
    significance: 'يصنف عالمياً كأحد أهم مواقع الجداريات البيزنطية والقبطية في حوض البحر المتوسط.',
    locationName: 'قرية الجبال الغربية، غرب سوهاج',
    locationDescription: 'يقع غرب مدينة سوهاج بنحو 12 كم على مقربة من الدير الأبيض عند سفح الجبل الغربي.',
    visitorTips: 'تأمل تناسق التيجان الكورنثية والأعمدة الملونة وأعمال الترميم الدقيقة داخل الهيكل الثلاثي.',
    coverImage: 'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 26.5492, lng: 31.6163 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة إلى ساعتين',
    visitInfo: {
      visitStatus: 'active_institution',
      visitStatusLabel: 'دير قبطي عامر وصرح روحي مفتوح',
      visitStatusNote: 'الدير يستقبل الزوار والسائحين والرحلات الدينية يومياً بالمجان مع مراعاة النظام الكنسي والضيافة الرهبانية دون تذاكر تجارية.',
      openingHours: 'يومياً من 8:00 ص حتى 6:00 م',
      bestTimeToVisit: 'فترة الصباح من 9:00 ص حتى 1:00 م',
      entryFee: 'مجاناً بالكامل (صرح ديني وتراثي مفتوح)',
      reservationRequired: false
    },
    access: {
      description: 'بالسيارات عبر الطريق الغربي بسوهاج بالقرب من الدير الأبيض.',
      transportation: 'تاكسي من مدينة سوهاج أو سيارات الرحلات المنظمة'
    },
    address: { governorate: 'سوهاج', city: 'سوهاج', village: 'نجع الدير' },
    sourceName: 'وزارة السياحة والآثار والكنيسة القبطية الأرثوذكسية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-sohag-museum',
    title: 'متحف سوهاج القومي',
    slug: 'sohag-national-museum',
    governorateId: 'gov-sohag',
    governorateName: 'سوهاج',
    category: 'museum',
    historicalEra: 'من عصور ما قبل التاريخ حتى العصر الحديث',
    description: 'صرح متحفي عملاق مصمم على هيئة صرح فرعوني على كورنيش نيل سوهاج، يضم نحو 1000 قطعة أثرية نادرة تروي أمجاد عاصمة الملوك وأبيدوس وتراث أخميم.',
    history: 'افتتح رسمياً عام 2018م ليكون نافذة حضارية كبرى لصعيد مصر. يسلط الضوء على عدة محاور رئيسية كالملكية المصرية القديمة، والتجارة والأسرة، والطب والعبادة، والحرف اليدوية عبر العصور الفرعونية واليونانية الرومانية والقبطية والإسلامية، مع مقتنيات نادرة من أبيدوس وأخميم وتماثيل لميريت آمون والمكتشفات الحديثة.',
    significance: 'أكبر متحف إقليمي في وسط الصعيد ومنارة ثقافية وتعليمية شاملة.',
    locationName: 'كورنيش النيل الشرقي، مدينة سوهاج',
    locationDescription: 'يقع على كورنيش النيل مباشرة في قلب مدينة سوهاج.',
    visitorTips: 'المتحف مريح ومكيف بالكامل ومجهز بأحدث شاشات العرض التفاعلية ويناسب العائلات والأطفال.',
    coverImage: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 26.5620, lng: 31.7050 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعتان',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة نهاراً ومساءً',
      visitStatusNote: 'المتحف يعمل فترتين يومياً ومجهز بمسارات خاصة لذوي الاحتياجات الخاصة.',
      openingHours: 'يومياً: 9:00 ص - 3:00 م ومن 5:00 م - 9:00 م',
      bestTimeToVisit: 'الفترة المسائية للتجول مع نسمات كورنيش النيل',
      entryFee: 'وفق تذاكر قطاع المتاحف بوزارة السياحة والآثار',
      reservationRequired: false
    },
    access: {
      description: 'في قلب كورنيش مدينة سوهاج، قريب من كافة الفنادق والخدمات.',
      transportation: 'تاكسي سوهاج الداخلي أو سيراً على الكورنيش'
    },
    address: { governorate: 'سوهاج', city: 'سوهاج' },
    sourceName: 'قطاع المتاحف - وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-sidi-arif-mosque',
    title: 'مسجد العارف بالله بسوهاج',
    slug: 'sidi-al-arif-mosque-sohag',
    governorateId: 'gov-sohag',
    governorateName: 'سوهاج',
    category: 'mosque',
    historicalEra: 'القرن الثامن الهجري وحتى العصر الحديث',
    description: 'أكبر وأشهر مساجد سوهاج التاريخية ومقصد أهالي الصعيد الروحي، يتألق بمئذنتين رشيقتين وقبة شامخة وزخارف إسلامية بديعة بقلب المدينة القديمة.',
    history: 'يعود تأسيسه للقرن الثامن الهجري للشيخ الصالح العارف بالله إسماعيل بن علي أحد كبار علماء الصوفية. أُعيد بناؤه وتوسعته في عهد الخديوي إسماعيل ثم تجدد عام 1968م؛ ويحتضن ساحة صلاة رخامية فسيحة وأسقفاً خشبية ذات نقوش إسلامية معقدة ومكتبة إسلامية عريقة تجذب رواد العلم وأهالي المحافظة.',
    significance: 'المعلم الديني والروحي الأول لمحافظة سوهاج وقلب الاحتفالات والمناسبات الدينية.',
    locationName: 'ميدان العارف، وسط مدينة سوهاج',
    locationDescription: 'يقع في قلب الميدان التاريخي لمدينة سوهاج بجوار الأسواق التجارية التراثية.',
    visitorTips: 'استمتع بأجواء السكينة وصلاة العصر أو المغرب مع ارتياد الأسواق التراثية المحيطة بالميدان.',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 26.5510, lng: 31.6965 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: '45 دقيقة إلى ساعة',
    visitInfo: {
      visitStatus: 'active_institution',
      visitStatusLabel: 'مسجد جامع وصرح ديني نشط',
      visitStatusNote: 'المسجد مفتوح طوال اليوم للصلوات والذكر وزيارة الساحة والمقام بالمجان دون تذاكر دخول.',
      openingHours: 'مفتوح من صلاة الفجر حتى ما بعد صلاة العشاء',
      bestTimeToVisit: 'بين صلاتي العصر والمغرب',
      entryFee: 'مجاناً بالكامل',
      reservationRequired: false
    },
    access: {
      description: 'يقع في أشهر ميادين سوهاج وسهل الوصول إليه من كافة أرجاء المدينة.',
      transportation: 'تاكسي سوهاج الداخلي وميكروباصات ميدان العارف'
    },
    address: { governorate: 'سوهاج', city: 'سوهاج' },
    sourceName: 'مديرية أوقاف سوهاج ومحافظة سوهاج',
    sourceUrl: 'http://www.sohag.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-akhmeem-handloom',
    title: 'قرية أخميم وورش النسيج والحرير التراثية',
    slug: 'akhmeem-handloom-weaving-heritage',
    governorateId: 'gov-sohag',
    governorateName: 'سوهاج',
    category: 'heritage_village',
    historicalEra: 'من العصر الفرعوني حتى التراث الحديث',
    description: 'مانشستر مصر القديمة وعاصمة النول اليدوي والحرير والكليم الصعيدي، حيث تتوارث العائلات صناعة المنسوجات اليدوية التي كانت تغزل كتان الفراعنة وكسوة الكعبة المشرفة.',
    history: 'اشتهرت أخميم "بانوبوليس" منذ فجر التاريخ بجودة أنسجتها التي وصفها المؤرخون الإغريق والمقريزي بأنها أندر وأثمن المنسوجات. وفي العصرين الفاطمي والمملوكي صُنعت بها كسوة الكعبة المشرفة، وتستمر حتى اليوم عائلات النساجين في تشغيل الأنوال الخشبية اليدوية وتطريز الكوفرتات وشيلان الحرير والكليم الصعيدي الصوفي المتميز بألوانه النباتية الطبيعية.',
    significance: 'المركز التاريخي الأول للنسيج اليدوي الأصيل في مصر ومسجل كحرفة تراثية وطنية.',
    locationName: 'مدينة أخميم، شرق سوهاج',
    locationDescription: 'تقع شرق النيل مباشرة مواجهة لمدينة سوهاج، وتنتشر ورش النول بجمعيات النساجين وحي الورش.',
    visitorTips: 'قم بزيارة جمعيات النسيج بأخميم لمعاينة النول وهو يتحرك بأيدي الحرفيين واقتناء منسوجات قطنية أو حريرية أصلية مباشرة.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 26.5635, lng: 31.7450 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعتين إلى ثلاث ساعات',
    visitInfo: {
      visitStatus: 'public_landmark',
      visitStatusLabel: 'منطقة حرفية وورش تراثية مفتوحة',
      visitStatusNote: 'الورش ومنافذ بيع الجمعيات التعاونية الإنتاجية للنساجين مفتوحة يومياً للجمهور للتجول والشراء المباشر من الحرفيين دون تذاكر.',
      openingHours: 'يومياً من 9:00 ص حتى 5:00 م',
      bestTimeToVisit: 'فترة الصباح لمشاهدة الحرفيين أثناء نسج القطع الفنية',
      entryFee: 'مجاناً للتجول ومشاهدة صناعة النسيج',
      reservationRequired: false
    },
    access: {
      description: 'عبر كوبري أخميم من مدينة سوهاج (10 دقائق بالسيارة).',
      transportation: 'تاكسي أو ميكروباص سوهاج - أخميم'
    },
    address: { governorate: 'سوهاج', city: 'أخميم' },
    sourceName: 'جمعية نساجي أخميم ومحافظة سوهاج',
    sourceUrl: 'http://www.sohag.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= أسيوط =================
  {
    id: 'place-assiut-barrage',
    title: 'قناطر أسيوط التاريخية وممشى النيل',
    slug: 'historic-assiut-barrage',
    governorateId: 'gov-asyut',
    governorateName: 'أسيوط',
    category: 'historical',
    historicalEra: 'أواخر القرن التاسع عشر (1898 - 1902م)',
    description: 'تحفة الهندسة المائية والهيدروليكية المشيدة من صخور الجرانيت الصلد على مجرى النيل بأسيوط لتنظيم ري مليون ونصف فدان وبداية ترعة الإبراهيمية الشهيرة.',
    history: 'شُيدت القناطر القديمة بين عامي 1898 و1902 باشتراك آلاف العمال والمهندسين المصريين، وبنيت بـ 111 عيناً من الحجر الجرانيتي المحلي لتوزيع المياه على محافظات أسيوط والمنيا وبني سويف والفيوم. ومع تشييد قناطر أسيوط الجديدة ومحطتها الكهرومائية، تحول الموقع التاريخي وممشى النيل إلى وجهة تنزه وتأمل تراثية عريقة على ضفاف النيل.',
    significance: 'شاهد استثنائي على عمارة وهندسة الري الكبرى في مصر الحديثة.',
    locationName: 'شمال مدينة أسيوط، على مجرى النيل',
    locationDescription: 'تقطع مجرى النيل وتربط بين ضفتي أسيوط عند مدخل فم ترعة الإبراهيمية.',
    visitorTips: 'استمتع بالمشي على الكورنيش المحيط بها وقت الغروب والتقاط الصور التذكارية لأقواسها الحجرية التاريخية.',
    coverImage: 'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 27.1994, lng: 31.1895 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعة',
    visitInfo: {
      visitStatus: 'public_landmark',
      visitStatusLabel: 'معلم وممشى عام مفتوح مجاناً',
      visitStatusNote: 'الموقع مفتوح كمعلم وممشى نهري عام للجمهور على مدار اليوم دون رسوم أو تذاكر.',
      openingHours: 'متاح على مدار 24 ساعة يومياً',
      bestTimeToVisit: 'فترة الغروب والمساء',
      entryFee: 'مجاناً بالكامل (معلم عام على الكورنيش)',
      reservationRequired: false
    },
    access: {
      description: 'تقع شمال مدينة أسيوط عند نهاية كورنيش النيل.',
      transportation: 'تاكسي أسيوط الداخلي أو سيراً على كورنيش النيل'
    },
    address: { governorate: 'أسيوط', city: 'أسيوط' },
    sourceName: 'وزارة الموارد المائية والري ومحافظة أسيوط',
    sourceUrl: 'http://www.assiut.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-qaysariya-assiut',
    title: 'سوق القيسارية العتيق ومسجد الكاشف بأسيوط',
    slug: 'qaysariya-heritage-bazaar-assiut',
    governorateId: 'gov-asyut',
    governorateName: 'أسيوط',
    category: 'heritage_village',
    historicalEra: 'العصر المملوكي والعثماني',
    description: 'أقدم أسواق الصعيد التراثية ووكالات تجارة درب الأربعين التاريخية، بأزقته المسقوفة بخشب السنديان ومتاجره التراثية للتلي والعطارة ومسجد الكاشف الأثري.',
    history: 'كانت أسيوط نقطة النهاية لقوافل "درب الأربعين" القادمة من دارفور وكردفان بالسودان عبر واحات الوادي الجديد. ويمثل سوق القيسارية الشريان التجاري العتيق في حي غرب أسيوط، ويضم وكالات تاريخية كوكالة شلبي ومحلات حياكة التلي والمنسوجات الصعيدية والعطارة النادرة، ويتوسطه جامع الكاشف الأثري بمئذنته ومنبره المملوكي الخشبي.',
    significance: 'النموذج الحي الأخير للأسواق المسقوفة ووكالات التجارة القديمة بصعيد مصر.',
    locationName: 'حي غرب، مدينة أسيوط القديمة',
    locationDescription: 'يمتد عبر الأزقة التراثية المتفرعة من شارع القيسارية غرب مدينة أسيوط.',
    visitorTips: 'تجول على الأقدام بين دكاكين التلي والعطارة الصعيدية، وتعرف على حكايات كبار التجار عن تجارة القوافل القديمة.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 27.1812, lng: 31.1835 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة ونصف لساعتين',
    visitInfo: {
      visitStatus: 'public_landmark',
      visitStatusLabel: 'سوق تراثي عام وشوارع مفتوحة',
      visitStatusNote: 'السوق دائم الحركة والنشاط من الصباح الباكر حتى المساء ومفتوح مجاناً للتجول والتسوق كشارع عام دون أي تذاكر.',
      openingHours: 'يومياً من 9:00 ص حتى 10:00 م',
      bestTimeToVisit: 'فترة قبل الظهر أو بعد العصر للتجول والتسوق الممتع',
      entryFee: 'مجاناً بالكامل (سوق عام مفتوح)',
      reservationRequired: false
    },
    access: {
      description: 'يقع بحي غرب القديم بالقرب من ميدان المجذوب ومحطة القطار.',
      transportation: 'تاكسي أو سيراً من وسط أسيوط القديمة'
    },
    address: { governorate: 'أسيوط', city: 'أسيوط' },
    sourceName: 'محافظة أسيوط وقطاع الآثار الإسلامية',
    sourceUrl: 'http://www.assiut.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-meir-tombs',
    title: 'مقابر مير الصخرية بالقوصية',
    slug: 'meir-rock-cut-tombs-assiut',
    governorateId: 'gov-asyut',
    governorateName: 'أسيوط',
    category: 'tomb',
    historicalEra: 'الدولتان القديمة والوسطى (الأسرات 6 و12)',
    description: 'مقابر صخرية فريدة منحوتة في الجبل الغربي بالقوصية لحكام الإقليم الـ 14، تتميز بنقوشها الواقعية الصريحة للحياة اليومية والرعاة والصيد وأدق تفاصيل الجسد البشري.',
    history: 'كانت القوصية (كوساي القديمة) عاصمة الإقليم الـ 14 لمصر العليا ومركز عبادة حتحور. نحت حكامها مقابرهم الفارهة في الصخر الجيري للجبل الغربي بقرية مير. تتفرد هذه المقابر بأسلوب فني غير مسبوق في الفن الفرعوني يميل للواقعية التامة حيث صُور الرعاة الهزلى والصيادون وتفاصيل المجاعات والولادة والرقص البهلواني بجوار الألوان الزاهية لمشاهد تقديم القرابين والصيد في البراري.',
    significance: 'مدرسة فنية استثنائية في تاريخ النحت المصري القديم تخرج عن القوالب الرسمية نحو الواقعية المعبرة.',
    locationName: 'قرية مير، مركز القوصية، أسيوط',
    locationDescription: 'تقع على حافة الصحراء الغربية غرب مدينة القوصية شمال محافظة أسيوط بنحو 50 كم.',
    visitorTips: 'الموقع يتطلب صعود درجات سلم بالجبل؛ احرص على ارتداء حذاء مريح واصطحاب مصباح يدوي ومياه شرب.',
    coverImage: 'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 27.4475, lng: 30.7533 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة ونصف لساعتين',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية',
      visitStatusNote: 'الموقع مفتوح بإشراف مفتشي منطقة آثار القوصية وأسيوط.',
      openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
      bestTimeToVisit: 'الصباح الباكر في فصلي الخريف والشتاء',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار الرسمية',
      reservationRequired: false
    },
    access: {
      description: 'بالسيارة عبر طريق أسيوط - ديروط الزراعي حتى القوصية ثم غرباً إلى قرية مير والجبل.',
      transportation: 'سيارة خاصة أو تاكسي من القوصية أو أسيوط'
    },
    address: { governorate: 'أسيوط', city: 'القوصية', village: 'مير' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= المنيا =================
  {
    id: 'place-tuna-el-gebel',
    title: 'تونا الجبل وسراديب الإله تحوت الأسطورية',
    slug: 'tuna-el-gebel-necropolis',
    governorateId: 'gov-minya',
    governorateName: 'المنيا',
    category: 'historical',
    historicalEra: 'العصور المتأخرة والبطلمية والرومانية',
    description: 'جبانة الإقليم الـ 15 وسراديبها الصخرية الهائلة لآلاف مومياوات طيور أبو منجل وقرود البابون المقدسة للإله تحوت، ومقبرة إيزادورا شهيدة الحب والساقية الرومانية بعمق 35 متراً.',
    history: 'كانت تونا الجبل جبانة مدينة الأشمونين الكبرى ومركز عبادة تحوت إله الحكمة والعلوم. تضم سراديب محفورة في باطن الجبل تمتد لكيلومترات كانت تدفن فيها الطيور والحيوانات المقدسة محنطة داخل جرار فخارية وتوابيت حجرية، ومقبرة "بيتوزيريس" الكاهن الأكبر بنقوشها التي تمزج الفن الفرعوني باليوناني، ومقبرة "إيزادورا" الفتاة الرومانية التي غرقت في النيل بدافع العشق وخلد والدها ذكراها بمرثية شعرية يونانية منقوشة على جدار مقبرتها.',
    significance: 'أكبر مجمع سراديب لدفن الكائنات المقدسة في العالم وشاهد على تمازج الحضارتين المصرية واليونانية.',
    locationName: 'غرب ملوي، محافظة المنيا',
    locationDescription: 'تقع على حافة الصحراء الغربية غرب مدينة ملوي بنحو 18 كم.',
    visitorTips: 'استمتع بالتجول داخل سراديب تحوت المضاءة واصطحب مرشداً محلياً للتعرف على قصة مقبرة إيزادورا الشهيرة.',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 27.6105, lng: 30.7380 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعتان',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة السياحية',
      visitStatusNote: 'الموقع والسراديب ومقبرة بيتوزيريس والساقية مفتوحة للزيارة بتذكرة موحدة.',
      openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
      bestTimeToVisit: 'الصباح الباكر',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار (الدفع الإلكتروني)',
      reservationRequired: false
    },
    access: {
      description: 'بالسيارة من مدينة ملوي عبر الطريق الصحراوي الغربي المتفرع.',
      transportation: 'تاكسي من مدينة ملوي أو سيارة سياحية خاصة'
    },
    address: { governorate: 'المنيا', city: 'ملوي' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-ashmunein-malawi',
    title: 'مدينة الأشمونين الأثرية ومتحف ملوي',
    slug: 'el-ashmunein-malawi-museum',
    governorateId: 'gov-minya',
    governorateName: 'المنيا',
    category: 'museum',
    historicalEra: 'من الدولة القديمة حتى العصرين اليوناني والروماني',
    description: 'مدينة الحكمة القديمة "خمون" بتمثالي البابون الجرانيتيين الضخمين وأطلال البازيليكا الرومانية، إلى جانب متحف ملوي الإقليمي الذي يعرض أروع كنوز تونا الجبل وتل العمارنة.',
    history: 'كانت الأشمونين "هرموبوليس ماجنا" عاصمة الإقليم الـ 15 ومهد أسطورة بدء الخلق الثامون المقدس في الديانة المصرية القديمة. يضم الموقع المفتوح تمثالين لقرود البابون من أضخم التماثيل في مصر بارتفاع 4.5 أمتار تقريباً، وبقايا كنيسة بازيليكا رومانية بأعمدة جرانيتية بديعة؛ وعلى بعد دقائق في مدينة ملوي يقع متحف ملوي القومي بعد إعادة تأهيله ليعرض توابيت خشبية نادرة وعملات وتماثيل حلي ومقتنيات تل العمارنة.',
    significance: 'مركز علمي وديني أسطوري في التاريخ المصري القديم يجمع بين الموقع الميداني والمتحف الإقليمي المتكامل.',
    locationName: 'الأشمونين ومدينة ملوي، المنيا',
    locationDescription: 'تقع الأشمونين شمال غرب ملوي بنحو 8 كم، ومتحف ملوي بقلب شارع الجيش بالمدينة.',
    visitorTips: 'ابدأ بزيارة موقع الأشمونين المفتوح ثم اختتم جولتك بمتحف ملوي المكيف لرؤية المقتنيات الأصلية.',
    coverImage: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 27.7810, lng: 30.8035 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعتان إلى ساعتين ونصف',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة',
      visitStatusNote: 'الموقع الأثري المفتوح ومتحف ملوي متاحان للزوار بتذاكر وزارة السياحة والآثار.',
      openingHours: 'يومياً من 9:00 ص حتى 4:00 م',
      bestTimeToVisit: 'فترة الصباح',
      entryFee: 'تذاكر معتمدة من وزارة السياحة والآثار',
      reservationRequired: false
    },
    access: {
      description: 'بالقرب من محطة قطار ملوي وطريق الصعيد الزراعي.',
      transportation: 'تاكسي ملوي أو ميكروباص من مدينة المنيا'
    },
    address: { governorate: 'المنيا', city: 'ملوي', village: 'الأشمونين' },
    sourceName: 'قطاع الآثار والمتاحف - وزارة السياحة والآثار',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-bahnasa',
    title: 'البهنسا (بقيع مصر وأرض الشهداء) ببني مزار',
    slug: 'al-bahnasa-martyrs-cemetery',
    governorateId: 'gov-minya',
    governorateName: 'المنيا',
    category: 'historical',
    historicalEra: 'فجر الإسلام والعصور الإسلامية اللاحقة',
    description: 'مدينة تاريخية كبرى ومركز الفتح الإسلامي في الصعيد، تضم رفات ما يزيد عن 5000 صحابي وتابعي استشهدوا في معارك فتح مصر وتلقب بـ "بقيع مصر" و"أرض الشهداء".',
    history: 'شهدت البهنسا (أوكسيرينخوس القديمة) أشرس معارك الفتح الإسلامي بقيادة قيس بن الحارث وعمرو بن العاص ضد الحاميات الرومانية. استشهد على ثراها ما يقارب 5000 صحابي وتابعي بينهم نحو 70 بدرياً ممن شهدوا غزوة بدر مع النبي ﷺ؛ وتضم اليوم عشرات القباب والأضرحة التاريخية العتيقة كقبة السبعة بنات، وقبة البدريين، ومقام علي الجمام، ومسجد الحسن الصالح، والشجرة النبوية المباركة.',
    significance: 'أقدس البقاع الإسلامية في صعيد مصر ومقصد سياحة دينية وتاريخية يجذب الزوار والباحثين من شتى أنحاء العالم.',
    locationName: 'قرية البهنسا، مركز بني مزار، شمال المنيا',
    locationDescription: 'تقع غرب مدينة بني مزار بنحو 16 كم على حافة الظهير الصحراوي الغربي.',
    visitorTips: 'مكان ذو سكينة روحية عميقة؛ التزم بالوقار وتجول بين قباب الصحابة ومسجد علي الجمام وقبة السبع بنات.',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 28.5325, lng: 30.6650 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعتين إلى ثلاث ساعات',
    visitInfo: {
      visitStatus: 'public_landmark',
      visitStatusLabel: 'مزار ديني وتاريخي مفتوح بالمجان',
      visitStatusNote: 'الموقع والأضرحة والمساجد والجبانة التاريخية مفتوحة للزيارة وقراءة الفاتحة طوال اليوم بالمجان دون بوابات أو تذاكر.',
      openingHours: 'مفتوح يومياً من الصباح الباكر حتى صلاة المغرب',
      bestTimeToVisit: 'صباح يوم الجمعة أو فترة قبل الظهر',
      entryFee: 'مجاناً بالكامل (مزار ديني وروحي مفتوح)',
      reservationRequired: false
    },
    access: {
      description: 'طريق بني مزار - البهنسا المتفرع من طريق الصعيد الزراعي أو الصحراوي الغربي.',
      transportation: 'ميكروباص بني مزار - البهنسا أو سيارات خاصة'
    },
    address: { governorate: 'المنيا', city: 'بني مزار', village: 'البهنسا' },
    sourceName: 'محافظة المنيا وهيئة الآثار الإسلامية والقبطية',
    sourceUrl: 'http://www.elminia.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= بني سويف =================
  {
    id: 'place-ahnasya',
    title: 'منطقة آثار إهناسيا المدينة (هيراكليوبوليس ماجنا)',
    slug: 'ahnasya-herakleopolis-magna',
    governorateId: 'gov-bani-suef',
    governorateName: 'بني سويف',
    category: 'historical',
    historicalEra: 'عصر الانتقال الأول (الأسرتان 9 و10) والعصور اللاحقة',
    description: 'عاصمة مصر القديمة في عصر الأسرتين التاسعة والعاشرة، ومركز عبادة المعبود حريشف، تضم موقعاً أثرياً مفتوحاً لمعابد رمسيس الثاني وأعمدة كورنثية وتيجان جرانيتية.',
    history: 'كانت إهناسيا "حنن-نسو" إحدى أعظم مدن مصر القديمة وعاصمة الدولة خلال عصر الانتقال الأول، ونشأ فيها أدب الحكم والوصايا الخالد كـ "تعاليم خيتي لابنه مري كارع". تضم بقايا معبد ضخم شيده رمسيس الثاني وأعمدة جرانيتية بازيليكية تعود للعصرين الروماني والبيزنطي ومقابر لحكام الإقليم ومتحف إهناسيا المفتوح للآثار الحجرية.',
    significance: 'إحدى العواصم الكبرى في تاريخ مصر القديمة ومهد الفلسفة والأدب الكلاسيكي الفرعوني.',
    locationName: 'مركز إهناسيا، غرب بني سويف',
    locationDescription: 'تقع غرب مدينة بني سويف بنحو 17 كم في قرية أم الكيمان بإهناسيا المدينة.',
    visitorTips: 'استكشف تيجان الأعمدة الجرانيتية المنحوتة بإتقان وتماثيل معبد رمسيس الثاني برفقة مفتشي الآثار.',
    coverImage: 'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.0833, lng: 30.9333 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعة ونصف',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية',
      visitStatusNote: 'الموقع الأثري والمتحف المفتوح يستقبل الزوار بتذاكر وزارة السياحة والآثار.',
      openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
      bestTimeToVisit: 'فترة الصباح',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار المصرية',
      reservationRequired: false
    },
    access: {
      description: 'عبر طريق بني سويف - إهناسيا الزراعي الغربي.',
      transportation: 'ميكروباص أو تاكسي من مدينة بني سويف إلى إهناسيا'
    },
    address: { governorate: 'بني سويف', city: 'إهناسيا', village: 'إهناسيا المدينة' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-beni-suef-museum',
    title: 'متحف آثار بني سويف القومي',
    slug: 'beni-suef-national-museum',
    governorateId: 'gov-bani-suef',
    governorateName: 'بني سويف',
    category: 'museum',
    historicalEra: 'من عصور ما قبل التاريخ حتى العصر الحديث',
    description: 'يقع داخل حديقة النصر بقلب مدينة بني سويف، ويضم سجلاً حياً لتاريخ المحافظة عبر العصور الفرعونية والقبطية والإسلامية ومكتشفات إهناسيا ودشاشة وألباستر سنور.',
    history: 'أنشئ المتحف عام 1997م لتوثيق تاريخ المحافظة عبر العصور التاريخية المختلفة. يضم مقتنيات أثرية فريدة من هرم ميدوم ومقابر أبو صير الملق وإهناسيا ودشاشة، وتوابيت حجرية وخشبية وأواني من رخام الألباستر المستخرج من محاجر كهف سنور ونماذج التراث السويفي الشعبي.',
    significance: 'مستودع الذاكرة الحضارية لشمال الصعيد وعاصمة ملوك الأسرتين التاسعة والعاشرة.',
    locationName: 'حديقة النصر، شارع الجيش، بني سويف',
    locationDescription: 'يقع داخل حديقة النصر التاريخية بقلب مدينة بني سويف بالقرب من محطة القطار.',
    visitorTips: 'نظراً لخضوع مبنى المتحف لمشروع ترميم وتطوير شامل، يرجى الاستعلام من المنطقة الأثرية عن مواعيد إعادة الافتتاح.',
    coverImage: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.0744, lng: 31.0988 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعة',
    visitInfo: {
      visitStatus: 'closed_for_restoration',
      visitStatusLabel: 'مغلق للترميم والتطوير الشامل',
      visitStatusNote: 'تخضع قاعات العرض المتحفي حالياً لأعمال مشروع التطوير والتأهيل الأثري الشامل من قبل وزارة السياحة والآثار، ولا تتوفر تذاكر زيارة داخلية للجمهور حالياً.',
      openingHours: 'مغلق داخلياً للترميم (الحديقة الخارجية متاحة نهاراً)',
      bestTimeToVisit: 'متابعة إعلانات وزارة السياحة والآثار لإعادة الافتتاح',
      entryFee: 'لا توجد تذاكر حالياً نظراً لأعمال التطوير',
      reservationRequired: true
    },
    access: {
      description: 'بوسط مدينة بني سويف بجوار حديقة النصر ومحطة القطار.',
      transportation: 'تاكسي بني سويف أو سيراً من وسط المدينة'
    },
    address: { governorate: 'بني سويف', city: 'بني سويف' },
    sourceName: 'قطاع المتاحف - وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= الفيوم =================
  {
    id: 'place-wadi-al-hitan',
    title: 'محمية وادي الحيتان (موقع تراث طبيعي عالمي لليونسكو)',
    slug: 'wadi-al-hitan-valley-of-whales',
    governorateId: 'gov-faiyum',
    governorateName: 'الفيوم',
    category: 'nature',
    historicalEra: 'عصر الإيوسين (قبل 40 مليون سنة)',
    description: 'أول موقع تراث طبيعي عالمي مدرج بقائمة اليونسكو في مصر، يحتضن مئات الهياكل العظمية الكاملة المتحجرة لحيتان بدائية منقرضة وسط تكوينات صخرية سريالية ومتحف حفريات مغطى.',
    history: 'كان الموقع قبل 40 مليون سنة قاعاً لبحر تيثيس القديم. يضم الوادي مئات الحفريات الفريدة لحوت "باسيلوسورس" و"دورويدون" وتماسيح وأبقار بحر، وتعد الدليل الأهم عالمياً على لغز تطور الحيتان من ثدييات برية تعيش على اليابسة إلى كائنات بحرية لوجود بقايا أطراف خلفية وأقدام صغيرة بأجسادها. يضم الموقع مساراً بيئياً ممهداً في الهواء الطلق ومتحف الحفريات وتغير المناخ الأول في الشرق الأوسط.',
    significance: 'موقع تراث طبيعي عالمي لليونسكو (UNESCO World Heritage Site 2005) ومرجع جيولوجي فريد على كوكب الأرض.',
    locationName: 'محمية وادي الريان، صحراء الفيوم الغربية',
    locationDescription: 'يقع في عمق صحراء وادي الريان جنوب غرب بحيرة قارون بنحو 90 كم من مدينة الفيوم.',
    visitorTips: 'الرحلة تتطلب سيارة دفع رباعي مجهزة (4x4) أو سلوك المدق البيئي الممهد بحذر، واصطحاب مياه وطعام، والمكان من أروع بقاع العالم لمراقبة النجوم ومجرة درب التبانة ليلاً.',
    coverImage: 'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.2700, lng: 30.0430 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'نصف يوم إلى يوم كامل (تخييم مصرح)',
    visitInfo: {
      visitStatus: 'requires_safari_permit',
      visitStatusLabel: 'محمية طبيعية ومسار سفاري مصرح',
      visitStatusNote: 'الزيارة مفتوحة بتذاكر ورسوم محميات وزارة البيئة وتتطلب وسيلة انتقال مناسبة (سيارة دفع رباعي أو رحلة سفاري مرخصة).',
      openingHours: 'يومياً من 8:00 ص حتى 5:00 م (والتخييم الليلي بتصريح مسبق)',
      bestTimeToVisit: 'من شهر أكتوبر حتى أبريل للتمتع بالطقس المعتدل وسماء النجوم الصافية',
      entryFee: 'تذاكر رسوم المحميات الطبيعية لوزارة البيئة المصرية + تذكرة متحف الحفريات',
      reservationRequired: false
    },
    access: {
      description: 'من طريق وادي الريان بالفيوم وصولاً إلى مدق وادي الحيتان الممهد لمسافة 35 كم داخل الصحراء.',
      transportation: 'سيارات الدفع الرباعي 4x4 أو رحلات السفاري المرخصة من القاهرة أو الفيوم'
    },
    address: { governorate: 'الفيوم', city: 'يوسف الصديق' },
    sourceName: 'منظمة اليونسكو وقطاع حماية الطبيعة بوزارة البيئة المصرية',
    sourceUrl: 'https://whc.unesco.org/en/list/1186',
    sourceType: 'unesco',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-tunis-village',
    title: 'قرية تونس التراثية ومتحف الكاريكاتير بالفيوم',
    slug: 'tunis-village-faiyum',
    governorateId: 'gov-faiyum',
    governorateName: 'الفيوم',
    category: 'heritage_village',
    historicalEra: 'العمارة البيئية وفنون الخزف المعاصرة',
    description: 'عاصمة الخزف والفخار الفني الريفي على ضفاف بحيرة قارون، حولتها الفنانة السويسرية إيفيلين بوريه لملتقى فني عالمي بمنازلها الطينية ومتحف الكاريكاتير الأول بالشرق الأوسط.',
    history: 'استقرت الفنانة السويسرية إيفيلين بوريه بالقرية في سبعينيات القرن العشرين وأسست مدرسة تعليم الفخار والخزف لأبناء القرية بالمجان؛ ليتحول أطفال القرية إلى فنانين محترفين تُعرض أعمالهم في معارض باريس ولندن. تتميز القرية بعمارة ريفية بيئية شيدت بالطين والقباب المستوحاة من المعماري حسن فتحي، وأسس بها الفنان محمد عبلة أول متحف للكاريكاتير بالمنطقة العربية.',
    significance: 'النموذج الأنجح في مصر للقرى التراثية البيئية المنتجة للفنون التشكيلية والخزف.',
    locationName: 'قرية تونس، مركز يوسف الصديق، الفيوم',
    locationDescription: 'تقع على ربوة تطل على الطرف الجنوبي لبحيرة قارون وشمال وادي الريان.',
    visitorTips: 'استمتع بتجربة صناعة الخزف بنفسك في إحدى الورش، وتجول على الأقدام أو بالدراجات بين المزارع ومعارض الفنون.',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.4180, lng: 30.5050 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من نصف يوم إلى يوم كامل',
    visitInfo: {
      visitStatus: 'public_landmark',
      visitStatusLabel: 'قرية بيئية وتراثية مفتوحة',
      visitStatusNote: 'القرية مفتوحة للجميع مجاناً للتجول، وورش الخزف والمطاعم البيئية ومتحف الكاريكاتير تقدم خدماتها ومنتجاتها بشكل مستقل دون أي تذاكر لدخول القرية.',
      openingHours: 'يومياً من 9:00 ص حتى غروب الشمس',
      bestTimeToVisit: 'فصل الخريف والربيع، وموسم مهرجان تونس السنوي للخزف',
      entryFee: 'مجاناً للتجول بالقرية (رسوم رمزية اختيارية لورش الخزف والمتحف)',
      reservationRequired: false
    },
    access: {
      description: 'طريق بحيرة قارون السياحي غرباً من مدينة الفيوم (حوالي 45 كم).',
      transportation: 'سيارات خاصة، تاكسي، أو ميكروباص من موقف الفيوم إلى يوسف الصديق وتونس'
    },
    address: { governorate: 'الفيوم', city: 'يوسف الصديق', village: 'تونس' },
    sourceName: 'محافظة الفيوم وقطاع الفنون التشكيلية',
    sourceUrl: 'http://www.fayoum.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-wadi-el-rayan',
    title: 'محمية وادي الريان والشلالات الطبيعية بالفيوم',
    slug: 'wadi-el-rayan-waterfalls-faiyum',
    governorateId: 'gov-faiyum',
    governorateName: 'الفيوم',
    category: 'nature',
    historicalEra: 'محمية طبيعية جيولوجية',
    description: 'المحمية الطبيعية الساحرة التي تحتضن شلالات المياه الطبيعية الوحيدة في مصر التي تربط البحيرة العليا بالبحيرة السفلى وجبل المدورة الشهير وسط الكثبان الرملية الذهبية.',
    history: 'أعلنت محمية طبيعية عام 1989 وتتكون من بحيرتين صناعيتين ناتجتين عن تصريف مياه الصرف الزراعي بالفيوم؛ وتتدفق المياه بينهما عبر مجرى صخري يشكل شلالات وادي الريان الشهيرة بارتفاع يصل لنحو 4 إلى 5 أمتار. تضم المحمية منطقة جبل المدورة الأسطوري بكثبانه الرملية المناسبة للتزلج، وعيون كبريتية طبيعية وموئلاً للغزلان والطيور المهاجرة.',
    significance: 'الواحة المائية الطبيعية الأبرز في صحراء مصر ومقصد سياحة المغامرات والتزلج على الرمال ومراقبة الطيور.',
    locationName: 'جنوب غرب الفيوم',
    locationDescription: 'تقع في منخفض وادي الريان جنوب غرب بحيرة قارون بنحو 40 كم.',
    visitorTips: 'استمتع بركوب الفلوكة الخشبية في البحيرة السفلى عند الشلالات، وجرب صعود جبل المدورة لمشاهدة بانوراما البحيرات.',
    coverImage: 'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.0780, lng: 30.4070 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من 3 إلى 5 ساعات',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'محمية طبيعية مفتوحة للزوار',
      visitStatusNote: 'مفتوحة للجمهور بتذاكر رسوم وزارة البيئة عند بوابة الدخول الرسمية.',
      openingHours: 'يومياً من 8:00 ص حتى 5:00 م',
      bestTimeToVisit: 'فترة الصباح حتى العصر من أكتوبر حتى مايو',
      entryFee: 'تذاكر المحميات الطبيعية لوزارة البيئة المصرية',
      reservationRequired: false
    },
    access: {
      description: 'طريق وادي الريان الإسفلتي المباشر من مدينة الفيوم أو طريق القاهرة - الفيوم الصحراوي.',
      transportation: 'سيارات خاصة أو حافلات الرحلات اليومية'
    },
    address: { governorate: 'الفيوم', city: 'إطسا' },
    sourceName: 'جهاز شؤون البيئة - قطاع حماية الطبيعة بجمهورية مصر العربية',
    sourceUrl: 'http://www.eeaa.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-qasr-qarun',
    title: 'قصر قارون ومعبد ديونيسياس البطلمي',
    slug: 'qasr-qarun-dionysias-temple',
    governorateId: 'gov-faiyum',
    governorateName: 'الفيوم',
    category: 'temple',
    historicalEra: 'العصر البطلمي (القرن الثالث ق.م)',
    description: 'معبد بطلمي فريد مشيد من الحجر الجيري الأصفر على الطرف الغربي لبحيرة قارون، يشتهر بظاهرة فلكية استثنائية وهي تعامد الشمس على قدس أقداسه في صبيحة 21 ديسمبر سنوياً.',
    history: 'شُيد المعبد في العصر البطلمي لعبادة الإله سوبك التمساح والمعبود ديونيسيوس؛ ويتميز بحفظ كامل لجدرانه وسلالم حجرية تقود إلى السطح ودهاليز وغرف سرية. يرتبط بظاهرة فلكية معمارية فريدة تسجل تعامد أشعة شروق الشمس صبيحة يوم 21 ديسمبر من كل عام إيذاناً ببدء الانقلاب الشتوي، ويجذب علماء الفلك والآثار سنوياً لرصد هذه الظاهرة.',
    significance: 'تحفة هندسية وفلكية بطلمية شاهدة على دقة الحسابات الفلكية والمعمارية في الفيوم.',
    locationName: 'قرية قصر قارون، غرب الفيوم',
    locationDescription: 'يقع في أقصى الطرف الغربي لبحيرة قارون شمال غرب محافظة الفيوم بنحو 50 كم.',
    visitorTips: 'احرص على صعود السلم الحجري الداخلي لسطح المعبد لمشاهدة الامتداد الصحراوي وبحيرة قارون من أعلى.',
    coverImage: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.4042, lng: 30.4081 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعة ونصف',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية',
      visitStatusNote: 'المعبد متاح للزيارة السياحية بتذاكر وزارة السياحة والآثار.',
      openingHours: 'يومياً من 8:00 ص حتى 5:00 م',
      bestTimeToVisit: 'الصباح الباكر، وموعد التعامد السنوي صباح 21 ديسمبر',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار الرسمية',
      reservationRequired: false
    },
    access: {
      description: 'عبر طريق بحيرة قارون السياحي غرباً حتى قرية قصر قارون.',
      transportation: 'سيارة خاصة أو تاكسي من مدينة الفيوم أو أبشواي'
    },
    address: { governorate: 'الفيوم', city: 'يوسف الصديق', village: 'قصر قارون' },
    sourceName: 'وزارة السياحة والآثار المصرية ومحافظة الفيوم',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-faiyum-waterwheels',
    title: 'سواقي الهدير التاريخية وميدان السواقي بالفيوم',
    slug: 'historic-faiyum-waterwheels',
    governorateId: 'gov-faiyum',
    governorateName: 'الفيوم',
    category: 'historical',
    historicalEra: 'العصر البطلمي والتراث الشعبي المتوارث',
    description: 'السواقي الهيدروليكية الخشبية العريقة وشعار محافظة الفيوم الرسمي، ترفع مياه بحر يوسف بقوة اندفاع التيار بنظام هندسي فريد دون وقود أو محركات وصوت هديرها العذب.',
    history: 'ابتكر مهندسو العصر البطلمي نظام السواقي الخشبية لرفع وتوزيع مياه بحر يوسف إلى الأراضي الزراعية وفق مستويات الانحدار الطبيعي لوادي الفيوم. تصنع السواقي يدوياً من خشب شجر الجميز والسنط الصلد ويصل قطرها لعدة أمتار وتدور ذاتياً بقوة دفع المياه لتفرغ مياهها في قنوات حجرية، وما تزال سواقي ميدان القارون وميدان السواقي بقلب مدينة الفيوم رمزاً شعبياً تراثياً مفتوحاً للجميع.',
    significance: 'الرمز المعماري والهندسي التراثي الأول لمحافظة الفيوم ونموذج عالمي للهندسة المستدامة النظيفة.',
    locationName: 'ميدان السواقي ومجرى بحر يوسف، قلب مدينة الفيوم',
    locationDescription: 'تتوزع على مجرى بحر يوسف وترعة بحر تنهلا وبميدان السواقي الرئيسي وسط المدينة.',
    visitorTips: 'استمتع بالمشي على ممشى بحر يوسف والجلوس بالمقاهي التراثية المطلة على السواقي للاستماع لصوت هديرها التاريخي.',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.3090, lng: 30.8420 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعة',
    visitInfo: {
      visitStatus: 'public_landmark',
      visitStatusLabel: 'معلم وميدان عام مفتوح مجاناً',
      visitStatusNote: 'الميدان وممشى السواقي مفتوح على مدار 24 ساعة يومياً للجمهور كمعلم عام دون أي رسوم أو تذاكر.',
      openingHours: 'متاح على مدار 24 ساعة يومياً',
      bestTimeToVisit: 'فترة ما بعد العصر والمساء',
      entryFee: 'مجاناً بالكامل (معلم عام وميدان مفتوح)',
      reservationRequired: false
    },
    access: {
      description: 'في قلب مدينة الفيوم بالقرب من محطة السكة الحديد ومقر المحافظة.',
      transportation: 'سيراً من وسط المدينة أو تاكسي الفيوم الداخلي'
    },
    address: { governorate: 'الفيوم', city: 'الفيوم' },
    sourceName: 'محافظة الفيوم والهيئة العامة للاستعلامات',
    sourceUrl: 'http://www.fayoum.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= الوادي الجديد =================
  {
    id: 'place-bagawat-necropolis',
    title: 'جبانة البجوات الأثرية بواحة الخارجة',
    slug: 'al-bagawat-necropolis-kharga',
    governorateId: 'gov-new-valley',
    governorateName: 'الوادي الجديد',
    category: 'tomb',
    historicalEra: 'القرنان الرابع والسابع الميلادي (المسيحية المبكرة)',
    description: 'واحدة من أقدم وأهم الجبانات المسيحية المبكرة في العالم، تضم 263 مزاراً ومقصورة قبابية من الطوب اللبن تزينها أندر اللوحات الجدارية المرسومة لقصص العهد القديم وخروج بني إسرائيل.',
    history: 'لجأ المسيحيون الأوائل لواحة الخارجة هرباً من الاضطهاد الروماني في القرنين الرابع والخامس الميلادي، وأقاموا هذه الجبانة العظيمة خلف جبل طارق شمال الخارجة. وتضم مزارات شهيرة مثل "مزار السلام" الذي يصور السيدة العذراء ونوح وإبراهيم وأيوب بألوان الفريسكو الطبيعية الزاهية، و"مزار الخروج" الذي يجسد مطاردة فرعون لبني إسرائيل في البحر الأحمر، وكنيسة قديمة تعد من أقدم كنائس مصر.',
    significance: 'موقع استثنائي في تاريخ العمارة الجنائزية والفنون القبطية المبكرة في العالم.',
    locationName: 'شمال واحة الخارجة، الوادي الجديد',
    locationDescription: 'تقع خلف معبد هيبس عند سفح جبل طارق شمال مدينة الخارجة بنحو 3 كم.',
    visitorTips: 'اصطحب كشافاً يدوي لتأمل التفاصيل الدقيقة للوحات الجدارية على قباب مزار السلام ومزار الخروج.',
    coverImage: 'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 25.4855, lng: 30.5530 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة ونصف لساعتين',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية',
      visitStatusNote: 'الموقع مفتوح يومياً بإشراف منطقة آثار الوادي الجديد بتذاكر وزارة السياحة والآثار.',
      openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
      bestTimeToVisit: 'فترة الصباح',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار المصرية',
      reservationRequired: false
    },
    access: {
      description: 'على بعد دقائق من معبد هيبس وطريق الخارجة - أسيوط.',
      transportation: 'تاكسي من مدينة الخارجة'
    },
    address: { governorate: 'الوادي الجديد', city: 'الخارجة' },
    sourceName: 'وزارة السياحة والآثار ومحافظة الوادي الجديد',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-dush-temple',
    title: 'معبد وحصن دوش الأثري بواحة باريس',
    slug: 'temple-fortress-of-dush',
    governorateId: 'gov-new-valley',
    governorateName: 'الوادي الجديد',
    category: 'historical',
    historicalEra: 'العصر البطلمي والروماني (عهد دوميتيان وتراجان وحيدريان)',
    description: 'حصن روماني ومعبد حجري شيد لحراسة درب الأربعين وقوافل التجارة في أقصى جنوب واحة باريس، والموقع الأثري الشهير الذي اكتشف فيه الكنز الذهبي "كنز دوش".',
    history: 'شُيد المعبد في العصرين البطلمي والروماني على ربوة استراتيجية تشرف على التقاء دروب القوافل الصحراوية والتجارة القديمة مع السودان وإفريقيا. كرس للإلهين سيرابيس وإيزيس، وحوله حصن عسكري عظيم من الطوب اللبن بأسوار شاهقة وغرف جند وصوامع غلال؛ وفي عام 1989م اكتشفت البعثة الفرنسية كنز دوش الذهبي الشهير (تاج ذهبي وأساور وصفائح نادرة معروضة حالياً بالمتحف المصري بالتحرير).',
    significance: 'أهم حصن وحامية رومانية باقية على مسار درب الأربعين الأسطوري في صعيد مصر الغربي.',
    locationName: 'قرية دوش، مركز باريس، جنوب الوادي الجديد',
    locationDescription: 'يقع جنوب واحة باريس بنحو 23 كم، وجنوب مدينة الخارجة بنحو 115 كم.',
    visitorTips: 'الموقع في قلب الصحراء الشاسعة؛ نسق الرحلة مبكراً مع وسيلة نقل مريحة واصطحب كمية كافية من المياه.',
    coverImage: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 24.5822, lng: 30.7180 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'ساعتان',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية',
      visitStatusNote: 'الموقع مفتوح للزيارة السياحية بتذاكر وزارة السياحة والآثار.',
      openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
      bestTimeToVisit: 'الصباح الباكر في فصل الشتاء',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار',
      reservationRequired: false
    },
    access: {
      description: 'طريق الخارجة - باريس المعبد ثم جنوباً نحو قرية دوش الأثرية.',
      transportation: 'سيارة خاصة أو حافلات الرحلات الاستكشافية من الخارجة'
    },
    address: { governorate: 'الوادي الجديد', city: 'باريس', village: 'دوش' },
    sourceName: 'وزارة السياحة والآثار والمعهد الفرنسي للآثار الشرقية IFAO',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= البحر الأحمر =================
  {
    id: 'place-quseir-fort',
    title: 'قلعة القصير العثمانية وميناء الحجاج والتجارة القديم',
    slug: 'el-quseir-ottoman-fort-port',
    governorateId: 'gov-red-sea',
    governorateName: 'البحر الأحمر',
    category: 'historical',
    historicalEra: 'العصر العثماني (1571م) وما قبله من عصور فرعونية وإسلامية',
    description: 'نهاية درب وادي الحمامات التاريخي وقوافل صعيد مصر، والقلعة الشامخة التي شيدها السلطان سليم الأول عام 1571م لحماية قوافل حجاج الصعيد والتجارة البحرية بمدافعها وأبراجها العتيدة.',
    history: 'تعد مدينة القصير أقدم موانئ البحر الأحمر وتاريخها متصل بالصعيد منذ عهد الفراعنة حين انطلقت رحلات الملكة حتشبسوت لبلاد بونت من ميناء "ساو" بالمدينة عبر درب وادي الحمامات من قفط وقنا. وفي العصر العثماني بنى السلطان سليم الأول القلعة الحصينة عام 1571 لحماية الميناء وتأمين قوافل الحجاج الصعايدة المتجهين للحجاز. وتضم القلعة أطلال الأبراج ومدافع بريطانية وعثمانية ومتحفاً أثرياً يسرد تاريخ قوافل الصحراء وتعدين الفوسفات والبيوت المشيدة بالحجر المرجاني.',
    significance: 'الرابط الجغرافي والتاريخي الأبرز بين صعيد مصر والبحر الأحمر وأعرق قلاع ساحل البحر الأحمر المصرية.',
    locationName: 'وسط مدينة القصير التاريخية، محافظة البحر الأحمر',
    locationDescription: 'تقع على تلة تشرف على ميناء القصير القديم وساحل البحر الأحمر مباشرة.',
    visitorTips: 'استكشف المدافع التاريخية وأبراج المراقبة ثم تمشى في شوارع القصير العتيقة لمشاهدة بيوت الحجر المرجاني والمشربيات الخشبية.',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 26.1070, lng: 34.2800 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة ونصف لساعتين',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية والسياحية',
      visitStatusNote: 'القلعة ومتحفها الأثري مفتوحان يومياً بتذاكر وزارة السياحة والآثار.',
      openingHours: 'يومياً من 9:00 ص حتى 5:00 م',
      bestTimeToVisit: 'فترة الصباح أو العصر قبل الغروب',
      entryFee: 'وفق تذاكر قطاع الآثار الإسلامية والقبطية',
      reservationRequired: false
    },
    access: {
      description: 'بوسط مدينة القصير، وترتبط بمحافظة قنا عبر طريق قنا - سفاجا - القصير أو طريق قفط - القصير.',
      transportation: 'سيارات الأجرة أو حافلات النقل العام أو الجولات السياحية'
    },
    address: { governorate: 'البحر الأحمر', city: 'القصير' },
    sourceName: 'قطاع الآثار الإسلامية والقبطية - وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-hawara-pyramid',
    title: 'هرم هوارة وقصر التيه (لابرنت أمنمحات الثالث)',
    slug: 'hawara-pyramid-labyrinth-faiyum',
    governorateId: 'gov-faiyum',
    governorateName: 'الفيوم',
    category: 'temple',
    historicalEra: 'الدولة الوسطى - الأسرة 12 (عهد أمنمحات الثالث)',
    description: 'هرم الطوب اللبن الشهير للملك أمنمحات الثالث وموقع "قصر التيه" الأسطوري الذي وصفه المؤرخ هيرودوت بأنه يفوق أهرامات الجيزة عجباً بمئات الغرف والممرات المتشابكة.',
    history: 'شيد الملك أمنمحات الثالث (المعروف بني ماعت رع) هرمه الثاني في هوارة بالفيوم لتأمين مقبرته بعد هرم دهشور، مستخدماً نواة من الطوب اللبن المكسو بالحجر الجيري، وابتكر مهندسوه نظام حماية فريد لحجرة الدفن المصنوعة من كتلة كوارتزيتية واحدة تزن 110 أطنان بنظام متاريس رملية معقد. والى الجنوب من الهرم أقيم معبد جنائزي ضخم ذو 3000 حجرة عرف عند اليونان باسم اللابرنت (قصر التيه). وعثر في المقابر المجاورة على أشهر "وجوه الفيوم" الجنائزية الرومانية.',
    significance: 'أعظم مشروعات العمارة الهندسية المائية والدفنية للدولة الوسطى وموقع قصر التيه الأسطوري.',
    locationName: 'قرية هوارة المقطع، جنوب شرق الفيوم',
    locationDescription: 'يقع على بعد 9 كم جنوب شرق مدينة الفيوم عند مدخل ترعة بحر يوسف إلى المنخفض.',
    visitorTips: 'استمتع بمشاهدة مقصورة ابنة الملك "نفروبتاح" المحفورة من الكوارتزيت، وأطلال قصر التيه على مدخل الواحة.',
    coverImage: 'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.2730, lng: 30.8986 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعة إلى ساعة ونصف',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية',
      visitStatusNote: 'المنطقة الأثرية المفتوحة بهوارة تستقبل الزوار بتذاكر وزارة السياحة والآثار، والدخول إلى باطن الهرم مغلق لارتفاع منسوب المياه الجوفية.',
      openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
      bestTimeToVisit: 'فترة الصباح',
      entryFee: 'وفق تذاكر وزارة السياحة والآثار المصرية (الدفع بالبطاقات البنكية)',
      reservationRequired: false
    },
    access: {
      description: 'طريق الفيوم - بني سويف القديم جنوب شرق مدينة الفيوم بنحو 9 كم.',
      transportation: 'سيارة خاصة أو تاكسي من مدينة الفيوم'
    },
    address: { governorate: 'الفيوم', city: 'الفيوم', village: 'هوارة المقطع' },
    sourceName: 'وزارة السياحة والآثار المصرية',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-karanis-kom-aushim',
    title: 'مدينة كرانيس الأثرية ومتحف كوم أوشيم بالفيوم',
    slug: 'karanis-kom-aushim-museum-faiyum',
    governorateId: 'gov-faiyum',
    governorateName: 'الفيوم',
    category: 'museum',
    historicalEra: 'العصر البطلمي والروماني (القرن الثالث ق.م - القرن الخامس الميلادي)',
    description: 'أكبر وأكمل المدن اليونانية والرومانية المحفوظة بصعيد مصر، تضم منازل بطابقين وصوامع غلال حجرية ومعبدين للمعبودين التمساحين، وبجوارها متحف كوم أوشيم الذي يعرض لوحات بورتريهات الفيوم الخالدة.',
    history: 'أسسها بطليموس الثاني فيلادلفوس في القرن الثالث ق.م كمدينة للمحاربين القدامى اليونانيين واستصلاح أراضي الفيوم. صمدت مبانيها الطينية والحجرية لقرون متتالية بفعل جفاف الصحراء، وتضم معبدين مشيدين بالحجر الجيري مكرسين للمعبودين سوبك (بنيفيروس وبيتيوسوخوس)، وحمامات رومانية عامة، ومطاحن ومعاصر زيتون وصوامع غلال ضخمة. ويضم متحف كوم أوشيم المجاور شواهد قبور وتماثيل وبورتريهات الفيوم الشهيرة ونماذج نسيج صوفية وكتانية نادرة.',
    significance: 'المرجع الأثري الأول لدراسة الحياة اليومية والتخطيط العمراني في العصرين البطلمي والروماني بمصر.',
    locationName: 'كوم أوشيم، شمال الفيوم على طريق القاهرة',
    locationDescription: 'تقع على بعد 30 كم شمال مدينة الفيوم عند الكيلو 70 على طريق القاهرة - الفيوم الصحراوي.',
    visitorTips: 'ينصح بالتجول بين أزقة المدينة الرومانية وصوامع الغلال أولاً ثم زيارة صالات متحف كوم أوشيم المكيفة.',
    coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509721434272-b79147e0e708?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 29.5167, lng: 30.9000 },
    isFeatured: false,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعتين إلى ساعتين ونصف',
    visitInfo: {
      visitStatus: 'open',
      visitStatusLabel: 'مفتوح للزيارة الأثرية والمتحفية',
      visitStatusNote: 'الموقع الأثري المكشوف لكرانيس ومتحف كوم أوشيم متاحان يومياً بتذاكر وزارة السياحة والآثار.',
      openingHours: 'يومياً من 9:00 ص حتى 4:00 م',
      bestTimeToVisit: 'فترة الصباح حتى منتصف النهار',
      entryFee: 'وفق لائحة وزارة السياحة والآثار (الدفع بالبطاقات البنكية)',
      reservationRequired: false
    },
    access: {
      description: 'مباشرة على طريق القاهرة - الفيوم الصحراوي عند بوابة كوم أوشيم الصناعية والزراعية.',
      transportation: 'سيارة خاصة أو حافلات وميكروباص طريق القاهرة - الفيوم'
    },
    address: { governorate: 'الفيوم', city: 'طامية', village: 'كوم أوشيم' },
    sourceName: 'قطاع الآثار المصرية والمتاحف - وزارة السياحة والآثار',
    sourceUrl: 'https://egymonuments.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-st-anthony-monastery',
    title: 'دير القديس الأنبا أنطونيوس (أقدم دير مأهول في العالم)',
    slug: 'st-anthony-monastery-red-sea',
    governorateId: 'gov-red-sea',
    governorateName: 'البحر الأحمر',
    category: 'monastery',
    historicalEra: 'القرن الرابع الميلادي (حوالي 356م)',
    description: 'مهد الرهبنة المسيحية في العالم، شُيد في واحة جبل الجلالة بالصحراء الشرقية تكريماً لأب الرهبان أنطونيوس الكبير، ويحتفظ بكنيسة أثرية وجداريات ملونة عتيقة وعين ماء طبيعية تتدفق منذ آلاف السنين.',
    history: 'تأسس الدير في القرن الرابع الميلادي بعد نياحة القديس أنطونيوس الكبير (أبو الرهبان) الذي لجأ إلى مغارة شاهقة بجبل الجلالة القبلي متعبداً في خلوة صامتة. يرتفع الدير كواحة خضراء وسط جبال البحر الأحمر الشاهقة، ويضم كنيسة القديس أنطونيوس الأثرية ذات الرسوم الجدارية البيزنطية والقبطية النادرة التي يعود أقدمها للقرن الثالث عشر الميلادي، وحصناً تاريخياً شُيد لحماية الرهبان من الغارات، ومكتبة مخطوطات قبطية نادرة، وعين ماء جبلية عذبة لا تجف تروي حدائق النخيل والزيتون.',
    significance: 'أقدم دير رهباني مسيحي قائم ومأهول في تاريخ البشرية ومزار عالمي للتراث الروحي والإنساني.',
    locationName: 'جبل الجلالة، واحة الأنبا أنطونيوس، محافظة البحر الأحمر',
    locationDescription: 'يقع في عمق الصحراء الشرقية عند سفح جبل الجلالة القبلي جنوب الزعفرانة بنحو 45 كم، متصلاً بطرق قوافل الصعيد القديمة.',
    visitorTips: 'اصعد درجات السلم الحجري الشاهق لزيارة مغارة الأنبا أنطونيوس في قمة الجبل لمشاهدة مشهد بانورامي ساحر للبحر الأحمر والجبال، والتزم بالوقار ونظام الدير.',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 28.9242, lng: 32.3508 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من ساعتين ونصف إلى 4 ساعات',
    visitInfo: {
      visitStatus: 'active_institution',
      visitStatusLabel: 'دير قبطي عامر وصرح روحي مفتوح',
      visitStatusNote: 'الدير يستقبل الزوار والرحلات الروحية والثقافية مجاناً طوال أيام الأسبوع عدا فترات الخلوة وأيام الصيام الكنسي المقررة، ولا توجد تذاكر تجارية لدخول الدير.',
      openingHours: 'يومياً من 8:00 ص حتى 5:00 م (مع مراعاة مواعيد القداسات الكنسية)',
      bestTimeToVisit: 'فصل الشتاء والربيع (الطقس معتدل في الجبل)',
      entryFee: 'مجاناً بالكامل (صرح ديني وتاريخي عامر)',
      reservationRequired: false
    },
    access: {
      description: 'طريق الكريمات - الزعفرانة أو طريق السويس - الغردقة الساحلي ثم التوجه غرباً 14 كم في مدق أسفلتي مباشر للدير.',
      transportation: 'سيارة خاصة أو حافلات الرحلات المنظمة'
    },
    address: { governorate: 'البحر الأحمر', city: 'رأس غارب' },
    sourceName: 'دير القديس الأنبا أنطونيوس والكنيسة القبطية الأرثوذكسية وقطاع الآثار القبطية',
    sourceUrl: 'https://copticorthodox.church',
    sourceType: 'official',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'place-wadi-el-gemal',
    title: 'محمية وادي الجمال الطبيعية والتاريخية (حوض حماطة وسكيك)',
    slug: 'wadi-el-gemal-national-park',
    governorateId: 'gov-red-sea',
    governorateName: 'البحر الأحمر',
    category: 'nature',
    historicalEra: 'محمية طبيعية وتراث فرعوني وبطلمي وروماني (مناجم الزمرد)',
    description: 'إحدى أروع المحميات المتكاملة في العالم، تمتد من قمم جبال البحر الأحمر حتى أعماق البحر، وتضم مناجم الزمرد القديمة لكليوباترا بجبل سكيك وقرى قبائل العبابدة وشواطئ حماطة البكر وغابات المانجروف.',
    history: 'أعلنت محمية طبيعية بقرار رئيس مجلس الوزراء عام 2003 وتغطي مساحة تفوق 7000 كم² تجمع بين البيئة البرية الصحراوية والجزر البحرية. كانت ممراً لقوافل التجارة القديمة الرابطة بين وادي النيل وموانئ البحر الأحمر، وتحتضن موقع "سكيك" الأثري ومناجم الزمرد الرومانية القديمة (مونس سماراجدوس)، ومعبد أبو غصون المحفور في الصخر، وتعد موطناً أصيلاً لأبناء قبائل العبابدة الذين يحافظون على تراث رعي الإبل ومشروب "الجبنة" التقليدي وفنون العمارة الصحراوية المستدامة.',
    significance: 'متحف بيئي وتراثي حي يجمع بين آثار تعدين الزمرد التاريخية والتنوع البيولوجي النادر والثقافة البدوية الأصيلة.',
    locationName: 'جنوب مرسى علم، محافظة البحر الأحمر',
    locationDescription: 'تقع جنوب مدينة مرسى علم بنحو 45 كم وتضم وادي الجمال الرئيسي وجزر حماطة وشاطئ القلعان.',
    visitorTips: 'استمتع بتناول قهوة "الجبنة" مع شيوخ العبابدة في قرية القلعان، ولا تفوت زيارة غابات المانجروف أو التخييم البيئي المنظم.',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80'
    ],
    coordinates: { lat: 24.6644, lng: 35.0886 },
    isFeatured: true,
    status: 'approved',
    verificationStatus: 'verified',
    visitDuration: 'من 4 ساعات إلى يوم كامل (أو تخييم بيئي)',
    visitInfo: {
      visitStatus: 'requires_safari_permit',
      visitStatusLabel: 'محمية طبيعية وتصريح سفاري بيئي',
      visitStatusNote: 'المحمية مفتوحة للزيارة والرحلات البيئية والغوص؛ والتجول في وديانها الصحراوية ومناجم الزمرد يتطلب سيارات دفع رباعي وتنسيقاً مع مرشدي قبائل العبابدة المعتمدين وسداد رسوم المحميات الطبيعية.',
      openingHours: 'يومياً من شروق الشمس حتى غروبها (والتخييم الليلي بتصريح بيئي مسبق)',
      bestTimeToVisit: 'من أكتوبر حتى مايو',
      entryFee: 'تذاكر رسوم زيارة المحميات الطبيعية الصادرة عن وزارة البيئة المصرية',
      reservationRequired: false
    },
    access: {
      description: 'طريق مرسى علم - برنيس الساحلي المباشر (جنوب مرسى علم بـ 45 كم).',
      transportation: 'سيارات دفع رباعي مجهزة أو حافلات الجولات البيئية المرخصة'
    },
    address: { governorate: 'البحر الأحمر', city: 'مرسى علم' },
    sourceName: 'جهاز شؤون البيئة - قطاع حماية الطبيعة ومحميات البحر الأحمر',
    sourceUrl: 'http://www.eeaa.gov.eg',
    sourceType: 'official_gov',
    researchDate: '2026-09-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
