import { HeritagePlaceDoc } from '@/server/models/types.ts';
import { GovernorateDoc } from '@/src/types';
import dotenv from 'dotenv';
dotenv.config();
import { MongoClient } from 'mongodb';

// =========================================================================
// WAH Cultural Ecosystem - Full Egyptian Arabic Content Migration Script
// النقلة التحريرية الشاملة لكل محتوى منصة «وه» إلى العامية المصرية الطبيعية
// بروح صعيدية أصيلة - خانات الصور فارغة وجاهزة لإضافتها بمعرفتك
// =========================================================================

export const ADDITIONAL_GOVERNORATES: GovernorateDoc[] = [
    {
        id: 'gov-faiyum',
        name: 'الفيوم',
        slug: 'faiyum',
        nickname: 'أرض السواقي والخزف وواحة مصر الخضراء',
        shortIntro: 'الفيوم واحة الخضرة والمية العذبة، سواقي الهدير اللي بتلف من مئات السنين، وبحيرة قارون وشلالات وادي الريان، وقرية تونس وفن الخزف.',
        history: 'الفيوم من أقدم بقاع الاستقرار البشري في مصر بحضارات العصر الحجري، وازدهرت جداً في الدولة الوسطى لما ملوك الأسرة 12 نظموا الري ببحر يوسف وبنوا أهرامات هوارة واللاهون. واشتهرت ببورتريهات الفيوم العالمية في العصر الروماني، ومحمية وادي الحيتان اللي بتوثق بداية خلق الحيتان في بحر تيثيس القديم كأول موقع تراث طبيعي عالمي لليونسكو في مصر.',
        famousFor: [
            'محمية وادي الحيتان (يونسكو)',
            'سواقي الهدير التاريخية',
            'قرية تونس وفن الخزف',
            'محمية وادي الريان والشلالات',
            'بحيرة قارون وقصر قارون'
        ],
        capitalCity: 'مدينة الفيوم',
        region: 'شمال الصعيد',
        nileSegment: 'بحر يوسف وبحيرة قارون',
        mapCoordinates: { lat: 29.3084, lng: 30.8428 },
        coverImage: '',
        gallery: [],
        traditionalCraftsIds: ['craft-pottery', 'craft-palm'],
        traditionalFoodIds: ['food-fayesh', 'food-mesh'],
        culturalTraditions: ['مهرجان تونس السنوي للخزف', 'أغاني وسير السواقي', 'صيد الأسماك ببحيرة قارون'],
        status: 'approved',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'gov-red-sea',
        name: 'البحر الأحمر',
        slug: 'red-sea',
        nickname: 'بوابة قوافل الصعيد وحصن القصير التاريخي',
        shortIntro: 'البحر الأحمر شط الصعيد الشرقي، ميناء القصير التاريخي اللي طلعت منه رحلات حتشبسوت لبونت، ودرب وادي الحمامات وقوافل الحجاج والتجارة.',
        history: 'البحر الأحمر ارتبط بروح وادي النيل ومحافظات الصعيد عبر دروب الصحراء الشرقية زي وادي الحمامات. وميناء القصير هو أقدم ميناء مصري على البحر، منه خرجت التجارة لبلاد بونت، ومنه سافر حجاج الصعيد لمكة عبر قلعة القصير وحصونها القديمة.',
        famousFor: [
            'قلعة القصير التاريخية',
            'درب قوافل وادي الحمامات',
            'ميناء القصير التراثي',
            'بيوت الحجر المرجاني القديمة'
        ],
        capitalCity: 'مدينة الغردقة (ومدينة القصير التاريخية)',
        region: 'جنوب الصعيد',
        nileSegment: 'دروب وادي الحمامات والبحر الأحمر',
        mapCoordinates: { lat: 26.1070, lng: 34.2800 },
        coverImage: '',
        gallery: [],
        traditionalCraftsIds: ['craft-palm'],
        traditionalFoodIds: [],
        culturalTraditions: ['أهازيج الصيادين والسمسمية', 'رحلات قوافل الحجاج الصعايدة', 'عادات قبائل العبابدة والبشارية'],
        status: 'approved',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    }
];

export const ADDITIONAL_HERITAGE_PLACES: HeritagePlaceDoc[] = [
    // ================= أسوان =================
    {
        id: 'place-kom-ombo',
        title: 'معبد كوم أمبو ومتحف التماسيح',
        slug: 'kom-ombo-temple',
        governorateId: 'gov-aswan',
        governorateName: 'أسوان',
        category: 'temple',
        historicalEra: 'العصر البطلمي والروماني',
        description: 'معبد كوم أمبو مبني على ربوة عالية بتطل على النيل بمنظر يخطف العين، والمميز فيه تصميمه المزدوج؛ مقسوم نصين، نص للإله سوبك التمساح والتاني لحورس، وفيه نقوش لأقدم أدوات جراحة وطب في العالم ومتحف لتماسيح النيل المحنطة.',
        history: 'المعبد اتبنى في العصر البطلمي وكمله الرومان في نقطة استراتيجية على النيل كانت مشهورة بتجمع التماسيح. وجنبه مقياس نيل حجري دائري كان الفراعنة بيقيسوا بيه الفيضان عشان يحددوا الضرايب ومواسم الزراعة.',
        significance: 'المعبد الوحيد في مصر اللي مبني بنظام محوري مزدوج، ونقوش الأدوات الجراحية زي الملاقط والمشارط بتأكد قد إيه الطب كان متقدم عند أجدادنا.',
        locationName: 'مدينة كوم أمبو، أسوان',
        locationDescription: 'يقع على ربوة مرتفعة مباشرة على الضفة الشرقية لنهر النيل بمدينة كوم أمبو شمال أسوان بنحو 45 كم.',
        visitorTips: 'أحلى وقت تزوره العصر قبل المغرب، عشان تشوف منظر النيل مع الغروب وإضاءة المعبد بالليل، ومتنساش تعدي على متحف التماسيح جنب البوابة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 24.4522, lng: 32.9283 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة ونصف لساعتين',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة السياحية',
            visitStatusNote: 'الموقع ومتحف التماسيح مفتوحان يومياً بتذكرة موحدة تشمل المعبد والمتحف.',
            openingHours: 'يومياً من 7:00 ص حتى 9:00 م (مضاء ليلاً)',
            bestTimeToVisit: 'فترة ما بعد العصر حتى المساء لمشاهدة الغروب والإضاءة الليلية الساحرة',
            entryFee: 'وفق لائحة وزارة السياحة والآثار (الدفع بالبطاقات البنكية)',
            reservationRequired: false
        },
        access: {
            description: 'يمكن الوصول بالسيارات والتاكسي عبر طريق أسوان - القاهرة الزراعي، أو عبر الفنادق العائمة (الكروز النيلي) التي ترسو أمام المعبد.',
            transportation: 'متاح سيارات الأجرة من موقف كوم أمبو أو حافلات الرحلات السياحية أو البواخر النيلية'
        },
        address: { governorate: 'أسوان', city: 'كوم أمبو' },
        sourceName: 'وزارة السياحة والآثار المصرية - قطاع الآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-edfu',
        title: 'معبد إدفو العظيم (معبد حورس)',
        slug: 'edfu-temple-horus',
        governorateId: 'gov-aswan',
        governorateName: 'أسوان',
        category: 'temple',
        historicalEra: 'العصر البطلمي',
        description: 'معبد إدفو هو أكمل وأجمل معبد فرعوني هتشوفه سليم بكل تفاصيله وسقوفه وصروحه الضخمة. مخصص لحورس إله الصقر، وأول ما تدخل بوابته هتحس بهيبة المكان.',
        history: 'بناء المعبد خد حوالي 180 سنة في عهد البطالمة. فضل مدفون تحت رمال الصعيد وبيوت القرية لمجى سنين، وده اللي حمى نقوشه لحد ما اكتشفه ونضفه عالم الآثار أوجست مارييت في القرن التسعتاشر.',
        significance: 'قيمته إنه أكمل معبد مصري قديم بيشرح طقوس العبادة اليومية للفراعنة، ونصوص معركة حورس على سوره الخارجي بتعتبر أعظم وثيقة دينية مسرحية.',
        locationName: 'مدينة إدفو، أسوان',
        locationDescription: 'يقع غرب النيل بقلب مدينة إدفو شمال محافظة أسوان بحوالي 100 كم.',
        visitorTips: 'روح الصبح بدري، وممكن تاخد حنطور من كورنيش إدفو لحد بوابة المعبد كتجربة لطيفة، والبس جزمة مريحة لأنك هتمشي كتير.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 24.9780, lng: 32.8735 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعتين إلى ساعتين ونصف',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة السياحية',
            visitStatusNote: 'المعبد مفتوح بالكامل ويشمل الدخول لجميع القاعات وصالات الأعمدة والبهو المكشوف.',
            openingHours: 'يومياً من 7:00 ص حتى 5:00 م',
            bestTimeToVisit: 'فترة الصباح الباكر من 7:00 حتى 10:00 صباحاً',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار الرسمية المعتمدة',
            reservationRequired: false
        },
        access: {
            description: 'متاح بالقطار أو سيارات الأجرة من أسوان أو الأقصر، كما يمثل محطة توقف أساسية لكافة رحلات الكروز النيلي.',
            transportation: 'قطار الصعيد، ميكروباص من أسوان أو الأقصر، أو حناطير إدفو من المرسى'
        },
        address: { governorate: 'أسوان', city: 'إدفو' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-unfinished-obelisk',
        title: 'المسلة الناقصة ومحاجر الجرانيت بأسوان',
        slug: 'unfinished-obelisk-aswan',
        governorateId: 'gov-aswan',
        governorateName: 'أسوان',
        category: 'historical',
        historicalEra: 'الدولة الحديثة - عهد الملكة حتشبسوت',
        description: 'المسلة الناقصة في أسوان بتوريك سر من أسرار البناء الفرعوني؛ كتلة جرانيت وردي ضخمة نايمة في الجبل وبتشرح إزاي المصري القديم كان بينحت أضخم حجر بإيده.',
        history: 'الملكة حتشبسوت أمرت بنحت المسلة عشان تتنقل لمعابد الكرنك، ولو كانت كملت كانت هتبقى أضخم مسلة في التاريخ بطول 42 متر ووزن أكتر من 1000 طن، لكن ظهر شرخ في الجرانيت فقرر البنايين يسيبوها مكانها.',
        significance: 'الموقع ورشة فرعونية حية بتكشف لعلماء الآثار تقنيات شق ونحت وتلميع الجرانيت الصلب.',
        locationName: 'جنوب مدينة أسوان',
        locationDescription: 'تقع في المحاجر الجنوبية القديمة بالقرب من المقابر الفاطمية بمدينة أسوان.',
        visitorTips: 'المحجر مكشوف تحت شمس أسوان، البس كاب واشرب مية ومعاك نضارة شمس، واستمتع بالممشى اللي بيلف فوق المسلة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 24.0768, lng: 32.8944 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'حوالي ساعة',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة السياحية',
            visitStatusNote: 'الموقع مجهز بمسار مشاة آمن ومركز معلومات ومجسم توضيحي لتقنيات النحت.',
            openingHours: 'يومياً من 7:00 ص حتى 5:00 م',
            bestTimeToVisit: 'الصباح الباكر',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار (الدفع الإلكتروني)',
            reservationRequired: false
        },
        access: {
            description: 'تبعد دقائق معدودة عن وسط مدينة أسوان ومحطة القطار.',
            transportation: 'تاكسي أسوان الداخلي أو الحافلات السياحية'
        },
        address: { governorate: 'أسوان', city: 'أسوان' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-nubian-museum',
        title: 'متحف النوبة بأسوان',
        slug: 'nubian-museum-aswan',
        governorateId: 'gov-aswan',
        governorateName: 'أسوان',
        category: 'museum',
        historicalEra: 'من عصور ما قبل التاريخ حتى العصر الحديث',
        description: 'افتتح سنة 1997 كثمرة لحملة اليونسكو لإنقاذ آثار النوبة من الغرق. صممه المعماري محمود الحكيم على مدرجات صخرية بتعكس شكل النوبة، ومعروضاته بتنقل الزائر في رحلة تجمع التاريخ والحياة اليومية.',
        history: 'متحف النوبة في أسوان تحفة معمارية واخدة جايزة أغاخان؛ بيوثق تاريخ وثقافة بلاد النوبة من زمان لحد ملحمة إنقاذ الآثار وقت بناء السد العالي.',
        significance: 'أهم صرح بيحفظ التراث واللغة والعادات النوبية، وفيه نماذج بالحجم الطبيعي للبيوت والقرى النوبية وعادات الأفراح.',
        locationName: 'طريق الفنادق، مدينة أسوان',
        locationDescription: 'يقع على ربوة صخرية بالقرب من فندق كتاراكت القديم والمقابر الفاطمية بمدينة أسوان.',
        visitorTips: 'المتحف مكيف ومريح للتجول، وفيه حديقة مفتوحة تحفة فيها قنوات مية وصخور ومقابر قديمة تستاهل تتمشى فيها.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 24.0792, lng: 32.8893 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعتين إلى ثلاث ساعات',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للجمهور والزوار',
            visitStatusNote: 'المتحف يعمل بفترتين يومياً (صباحية ومسائية) ومجهز بالكامل لذوي الهمم.',
            openingHours: 'يومياً على فترتين: 9:00 ص - 1:00 م ومن 5:00 م - 9:00 م',
            bestTimeToVisit: 'الفترة المسائية للاستمتاع بحديقة المتحف والإضاءة الهادئة',
            entryFee: 'تذاكر وزارة السياحة والآثار (خصم خاص للطلاب المصريين)',
            reservationRequired: false
        },
        access: {
            description: 'يقع في قلب مدينة أسوان بالقرب من كورنيش النيل.',
            transportation: 'متاح بالتاكسي أو سيراً من كورنيش النيل وطريق الفنادق'
        },
        address: { governorate: 'أسوان', city: 'أسوان' },
        sourceName: 'قطاع المتاحف - وزارة السياحة والآثار',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-elephantine',
        title: 'جزيرة إلفنتين ومقياس النيل الأثري',
        slug: 'elephantine-island-nilometer',
        governorateId: 'gov-aswan',
        governorateName: 'أسوان',
        category: 'historical',
        historicalEra: 'من عصور ما قبل الأسرات وحتى العصر الروماني',
        description: 'جزيرة إلفنتين في قلب نيل أسوان بروحها الخالدة؛ كانت عاصمة أول إقليم في مصر القديمة، وفيها مقياس النيل الروماني ومعبد خنوم وقريتين نوبيتين هاديتين وسط النخيل.',
        history: 'زمان كان اسمها "أبو" يعني جزيرة الفيل، وكانت أهم نقطة تجارية لحماية حدود مصر الجنوبية. فوق الجزيرة نحت الفراعنة والرومان مقاييس النيل الحجرية عشان يقيسوا بيه الفيضان.',
        significance: 'رمز أثري بيربط حضارة مصر بإفريقيا، ومقياس النيل اللي فيها من أدق المعالم الهيدروليكية.',
        locationName: 'جزيرة إلفنتين، وسط نيل أسوان',
        locationDescription: 'جزيرة نيلية كبرى تواجه كورنيش أسوان وتفصل بين ضفتي النيل.',
        visitorTips: 'عدي ليها بمركب فلوكة أو معدية من كورنيش أسوان برخص التراب، واتمشى في شوارع قرية الكوبانية وسط النخيل والبيوت الملونة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 24.0850, lng: 32.8860 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعتين إلى ثلاث ساعات',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة',
            visitStatusNote: 'المنطقة الأثرية ومقياس النيل بتذاكر الآثار، والقرية النوبية مفتوحة مجاناً للتجول.',
            openingHours: 'يومياً من 8:00 ص حتى 5:00 م',
            bestTimeToVisit: 'عصراً قبل الغروب للاستمتاع برحلة المعدية والنيل',
            entryFee: 'تذاكر الآثار للمنطقة الأثرية + تذكرة رمزية للمعدية النيلية',
            reservationRequired: false
        },
        access: {
            description: 'الوصول فقط عبر نهر النيل بواسطة معدية الأهالي العامة أو المراكب الشراعية (الفلوكة) من الكورنيش.',
            transportation: 'المعدية النيلية من مرسى الكورنيش أو مراكب الفلوكة الشراعية'
        },
        address: { governorate: 'أسوان', city: 'أسوان' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= الأقصر =================
    {
        id: 'place-luxor-temple',
        title: 'معبد الأقصر وطريق الكباش الأثري',
        slug: 'luxor-temple-avenue-sphinxes',
        governorateId: 'gov-luxor',
        governorateName: 'الأقصر',
        category: 'temple',
        historicalEra: 'الدولة الحديثة والعصور اللاحقة',
        description: 'المعبد اتبنى سنة 1400 قبل الميلاد، وكان مقر لموكب ثالوث طيبة وسط احتفالات شعبية. دخلت عليه إضافات من مسلة رمسيس التاني لمقصورة الإسكندر وكنيسة قبطية ومسجد أبو الحجاج.',
        history: 'معبد الأقصر درة البر الشرقي قاعد على شط النيل في قلب المدينة؛ شيده أمنحتب الثالث وكمله رمسيس الثاني عشان مواكب عيد الأوبت، ومربوط بالكرنك بطريق الكباش.',
        significance: 'المعلم الوحيد اللي بيجمع 3400 سنة عبادة وتاريخ متواصل؛ من الفرعوني للروماني والقبطي والإسلامي.',
        locationName: 'كورنيش النيل، وسط مدينة الأقصر',
        locationDescription: 'يقع في قلب مدينة الأقصر بمواجهة النيل مباشرة ونقطة بداية طريق الكباش التاريخي.',
        visitorTips: 'أحسن وقت تزوره بعد المغرب؛ المعبد مضاء بإضاءة ساحرة بتنطق الهيبة والجمال، وبعده اتمشى في طريق الكباش وممشى الكورنيش.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 25.6995, lng: 32.6396 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعتان',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة نهاراً وليلاً',
            visitStatusNote: 'المعبد مفتوح حتى العاشرة مساءً وطريق الكباش متاح للتجول.',
            openingHours: 'يومياً من 6:00 ص حتى 10:00 م (مضاء بالكامل ليلاً)',
            bestTimeToVisit: 'فترة ما قبل الغروب والمساء للاستمتاع بالإضاءة البديعة وأجواء الكورنيش',
            entryFee: 'تذاكر معتمدة من وزارة السياحة والآثار (دفع بالفيزا)',
            reservationRequired: false
        },
        access: {
            description: 'يقع بقلب الأقصر، خطوات من محطة القطار وسوق الأقصر السياحي وفنادق الكورنيش.',
            transportation: 'سيراً على الأقدام من وسط المدينة، أو بالتاكسي والحنطور'
        },
        address: { governorate: 'الأقصر', city: 'الأقصر' },
        sourceName: 'وزارة السياحة والآثار المصرية - موقع آثار الأقصر',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-valley-queens',
        title: 'وادي الملكات ومقبرة نفرتاري الأسطورية',
        slug: 'valley-of-the-queens-nefertari',
        governorateId: 'gov-luxor',
        governorateName: 'الأقصر',
        category: 'tomb',
        historicalEra: 'الدولة الحديثة (الأسرات 18 - 20)',
        description: 'كان بيتسمى "تا-ست-نفرو" مكان الجمال والكمال؛ اختاروه في وادي صحراوي هادي ورا جبل القرنة لحفظ أجساد الملكات، وبيضم أكتر من 90 مقبرة في الصخر.',
        history: 'وادي الملكات في البر الغربي للأقصر هو الجبانة الملكية لأميرات وملكات الفراعنة، وفيه درة مقابر مصر: مقبرة نفرتاري الفاتنة اللي ألوانها لسه منورة كأنها لسه مرسومة.',
        significance: 'مقبرة نفرتاري قمة الإبداع الفني في تاريخ مصر القديمة، ألوانها الزاهية لسه بحالتها الأصلية.',
        locationName: 'البر الغربي، الأقصر',
        locationDescription: 'يقع في الطرف الجنوبي للجبانة الطيبة بالبر الغربي بالأقصر.',
        visitorTips: 'زيارة مقبرة نفرتاري بتحتاج تذكرة خاصة وليها وقت محدد عشان الحفاظ على رطوبتة الألوان، احرص تحجزها بدري.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 25.7285, lng: 32.5930 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة ونصف لساعتين',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة السياحية',
            visitStatusNote: 'يشمل الوادي 3 مقابر رئيسية عامة، ومقبرة نفرتاري تباع تذكرتها المستقلة بالمركز الرئيسي للزوار.',
            openingHours: 'يومياً من 6:00 ص حتى 5:00 م',
            bestTimeToVisit: 'الصباح الباكر',
            entryFee: 'تذكرة عامة لوادي الملكات + تذكرة خاصة لمقبرة نفرتاري',
            reservationRequired: false
        },
        access: {
            description: 'بالسيارات وحافلات الجولات السياحية عبر كوبري الأقصر العلوي أو معدية الأهالي للبر الغربي.',
            transportation: 'تاكسي البر الغربي أو سيارات الجولات المنظمة'
        },
        address: { governorate: 'الأقصر', city: 'القرنة' },
        sourceName: 'وزارة السياحة والآثار المصرية واليونسكو',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-colossi-memnon',
        title: 'تمثالا ممنون وصرح أمنحتب الثالث',
        slug: 'colossi-of-memnon',
        governorateId: 'gov-luxor',
        governorateName: 'الأقصر',
        category: 'historical',
        historicalEra: 'الدولة الحديثة - الأسرة 18 (عهد أمنحتب الثالث)',
        description: 'اتنحتوا سنة 1350 قبل الميلاد لأمنحتب الثالث قدام معبده اللي غمرته مية الفيضان. في العصر الروماني حصل شرخ في التمثال الشمالي فبقى يصفر مع نسيم الصبح، فالرومان افتكروه ممنون بينادي أمه.',
        history: 'تمثالا ممنون عملاقين من الحجر الرملي في بر الأقصر الغربي بارتفاع 18 متر ووزن أكتر من 700 طن للتمثال، حراس صامتين بيستقبلوا اللي يعبر للنيل.',
        significance: 'أضخم تمثالين باقين في مكانهم المفتوح من مصر القديمة، ورمز ارتبط برحلات السياحة عبر العصور.',
        locationName: 'طريق القرنة السياحي، البر الغربي، الأقصر',
        locationDescription: 'يقعان في الفضاء المفتوح على الطريق الرئيسي المؤدي لوادي الملوك ومعابد البر الغربي.',
        visitorTips: 'الموقع مفتوح ومجاني على طريق البر الغربي، تقدر تقف بالعربية أو العجلة وتتصور جنبهم في طريقك لوادي الملوك.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 25.7206, lng: 32.6105 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: '30 إلى 45 دقيقة',
        visitInfo: {
            visitStatus: 'public_landmark',
            visitStatusLabel: 'معلم أثري عام مفتوح مجاناً',
            visitStatusNote: 'الموقع مفتوح مباشرة على جانب الطريق السياحي ومتاح للمشاهدة والتصوير مجاناً دون بوابات أو تذاكر.',
            openingHours: 'متاح على مدار 24 ساعة يومياً',
            bestTimeToVisit: 'شروق الشمس والصباح الباكر',
            entryFee: 'مجاناً بالكامل (معلم عام بالطريق المفتوح)',
            reservationRequired: false
        },
        access: {
            description: 'على الطريق الرئيسي المباشر للبر الغربي عند مدخل مدينة القرنة.',
            transportation: 'تاكسي أو حافلة سياحية أو دراجات هوائية من معدية البر الغربي'
        },
        address: { governorate: 'الأقصر', city: 'القرنة' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-medinet-habu',
        title: 'معبد مدينة هابو لرمسيس الثالث',
        slug: 'medinet-habu-temple',
        governorateId: 'gov-luxor',
        governorateName: 'الأقصر',
        category: 'temple',
        historicalEra: 'الدولة الحديثة - الأسرة 20',
        description: 'رمسيس التاني بنى المعبد كمعبد جنائزي ومركز حكم محصن بأسوار طوب لبن. نقوش جدرانه غائرة عشان محدش يمحوها، وبتسجل معارك الجيش المصري ضد الغزاة.',
        history: 'معبد مدينة هابو لرمسيس الثالث أكتر معابد البر الغربي احتفاظاً بألوانه الأصلية وسقوفه وأسواره العسكرية الضخمة، مشهور ببوابته السورية ونقوش معارك شعوب البحر.',
        significance: 'أحسن مكان في الأقصر تشوف فيه ألوان الفراعنة الزرقا والحمرا والصفرا في سقوف الأعمدة لسه حية كأنها جديدة.',
        locationName: 'مدينة هابو، القرنة، الأقصر',
        locationDescription: 'يقع في الجزء الجنوبي من مقابر ومعابد البر الغربي لمدينة الأقصر.',
        visitorTips: 'المعبد هادي وزحمته قليلة، ارفع عينك تحت السقوف واستمتع بتأمل تفاصيل الألوان والنقوش الغائرة على مهلك.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 25.7198, lng: 32.5999 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة ونصف لساعتين',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة السياحية',
            visitStatusNote: 'المعبد متاح بالكامل للزيارة بجميع أروقته وأبوابه الحصينة.',
            openingHours: 'يومياً من 6:00 ص حتى 5:00 م',
            bestTimeToVisit: 'فترة الصباح أو الظهيرة حين تضيء الشمس نقوش الصالات الداخلية',
            entryFee: 'تذاكر رسمية لوزارة السياحة والآثار',
            reservationRequired: false
        },
        access: {
            description: 'بالقرب من وادي الملكات وتمثالي ممنون بالبر الغربي.',
            transportation: 'سيارات الأجرة أو حافلات الرحلات السياحية بالبر الغربي'
        },
        address: { governorate: 'الأقصر', city: 'القرنة' },
        sourceName: 'وزارة السياحة والآثار المصرية واليونسكو',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-ramesseum',
        title: 'معبد الرامسيوم الجنائزي لرمسيس الثاني',
        slug: 'the-ramesseum-luxor',
        governorateId: 'gov-luxor',
        governorateName: 'الأقصر',
        category: 'temple',
        historicalEra: 'الدولة الحديثة - الأسرة 19',
        description: 'رمسيس التاني شيد الصرح لتخليد اسمه، وكان المجمع بيضم مدرسة لتعليم الكتبة ومكتبة ضخمة وصوامع غلال مبنية بالقباب تكفي آلاف العمال.',
        history: 'الرامسيوم هو المعبد الجنائزي العظيم اللي بناه رمسيس الثاني في طيبة، واشتهر عالمياً بقصيدة شيلي "أوزيماندياس", وفيه بقايا أضخم تمثال جرانيتي واقع على الأرض.',
        significance: 'تحفة العمارة في الدولة الحديثة، وتمثال رمسيس المكسور وزنه لوحده أكتر من 1000 طن وكان معجزة في نقله من أسوان للأقصر.',
        locationName: 'شمال القرنة، البر الغربي، الأقصر',
        locationDescription: 'يقع بين معبد حتشبسوت ومدينة هابو بالقرب من مقابر النبلاء.',
        visitorTips: 'مكان ساحر للتصوير والتأمل، زوره الصبح في هدوء البر الغربي وتفرج على صوامع الطوب اللبن ورا المعبد.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 25.7278, lng: 32.6106 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعة ونصف',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة السياحية',
            visitStatusNote: 'الموقع مفتوح يومياً بتذاكر وزارة السياحة والآثار.',
            openingHours: 'يومياً من 6:00 ص حتى 5:00 م',
            bestTimeToVisit: 'الصباح الباكر',
            entryFee: 'تذاكر وزارة السياحة والآثار (الدفع الإلكتروني)',
            reservationRequired: false
        },
        access: {
            description: 'عبر طريق معابد البر الغربي بالأقصر.',
            transportation: 'تاكسي البر الغربي أو الدراجات الهوائية'
        },
        address: { governorate: 'الأقصر', city: 'القرنة' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= قنا =================
    {
        id: 'place-youssef-kamal-palace',
        title: 'قصر البرنس يوسف كمال بنجع حمادي',
        slug: 'prince-youssef-kamal-palace',
        governorateId: 'gov-qena',
        governorateName: 'قنا',
        category: 'historical',
        historicalEra: 'أوائل القرن العشرين (1908م)',
        description: 'القصر اتبنى سنة 1908 بمهندس إيطالي بتكليف من الأمير يوسف كمال من أثرياء أسرة محمد علي. متصمم بتوليفة ساحرة بين الزخارف الإسلامية ومورسكية وعصر النهضة.',
        history: 'قصر البرنس يوسف كمال بنجع حمادي تحفة معمارية نادرة نايمة على كورنيش نيل قنا؛ بناه البرنس ومؤسس فنون جميلة في حديقة مليانة أشجار نادرة.',
        significance: 'أجمل قصور الصعيد الخديوية الباقية على النيل، وشاهد على عصر النهضة الفنية وحياة أمراء مصر زمان.',
        locationName: 'مدينة نجع حمادي، محافظة قنا',
        locationDescription: 'يقع على كورنيش النيل بمدينة نجع حمادي شمال غرب قنا بنحو 55 كم.',
        visitorTips: 'القصر مرمم ومفتوح للزيارة؛ استمتع بالتجول في قاعات السلاملك والحرملك والحديقة الملكية المطلة على النيل مباشرة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 26.0489, lng: 32.2412 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة ونصف لساعتين',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية',
            visitStatusNote: 'القصر والحدائق التابعة مفتوحة للزوار بإشراف قطاع الآثار الإسلامية والقبطية.',
            openingHours: 'يومياً من 9:00 ص حتى 4:00 م',
            bestTimeToVisit: 'فترة الصباح حتى الواحدة ظهراً',
            entryFee: 'وفق تذاكر الآثار الإسلامية والقبطية الرسمية',
            reservationRequired: false
        },
        access: {
            description: 'بالقرب من محطة سكة حديد نجع حمادي وطريق مصر أسوان الزراعي.',
            transportation: 'تاكسي نجع حمادي الداخلي أو قطار الصعيد'
        },
        address: { governorate: 'قنا', city: 'نجع حمادي' },
        sourceName: 'قطاع الآثار الإسلامية والقبطية - وزارة السياحة والآثار',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-naqada-heritage',
        title: 'مدينة الحرفيين والأديرة التاريخية بنقادة',
        slug: 'naqada-heritage-town',
        governorateId: 'gov-qena',
        governorateName: 'قنا',
        category: 'heritage_village',
        historicalEra: 'عصور ما قبل الأسرات والتراث القبطي والشعبي',
        description: 'نقادة في قنا مهد حضارات ما قبل الأسرات وعاصمة نسيج الفركة. الأجداد صنعوا فيها التاريخ، ولحد النهاردة الورش شغالة بأنوالها.',
        history: 'نقادة سجلت اسمها لما اكتشف بتري مقابر وحضارات نقادة. وفي العصر القبطي والإسلامي بقت مركز للأديرة والنساجين اللي صدروا الشيلان للسودان.',
        significance: 'مركز حي بيجمع بين مهد الحضارة الإنسانية وصناعة نسيج تراثية لسه عايشة بأنوالها في بيوت الأهالي وورشهم.',
        locationName: 'مدينة نقادة، جنوب قنا',
        locationDescription: 'تقع على الضفة الغربية لنهر النيل جنوب محافظة قنا وشمال الأقصر بنحو 25 كم.',
        visitorTips: 'زور ورش الفركة في بيوت المدينة واتفرج على النساجين، ومتفوتش زيارة دير الملاك ميخائيل ودير الصليب غرب المدينة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 25.9030, lng: 32.7230 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعتين إلى ثلاث ساعات',
        visitInfo: {
            visitStatus: 'public_landmark',
            visitStatusLabel: 'مدينة وقرى حرفية عامة مفتوحة',
            visitStatusNote: 'مدينة نقادة وقراها وورش الأنوال اليدوية مفتوحة للتجول والتسوق المباشر من الحرفيين دون تذاكر دخول، والأديرة مفتوحة للزيارة والصلوات.',
            openingHours: 'يومياً من 9:00 ص حتى 5:00 م',
            bestTimeToVisit: 'فترة الصباح حتى العصر لمشاهدة عمل الأنوال اليدوية',
            entryFee: 'مجاناً للتجول وزيارة الورش والأديرة',
            reservationRequired: false
        },
        access: {
            description: 'متاحة عبر الطريق الغربي الزراعي بين قنا والأقصر أو معديات النيل.',
            transportation: 'سيارات الأجرة (الميكروباص) من قنا أو الأقصر'
        },
        address: { governorate: 'قنا', city: 'نقادة' },
        sourceName: 'الهيئة العامة للاستعلامات ومحافظة قنا',
        sourceUrl: 'http://www.qena.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-qus-al-amri-mosque',
        title: 'المسجد العمري الأثري بقوص ومحطة قوافل الحج',
        slug: 'al-amri-mosque-qus',
        governorateId: 'gov-qena',
        governorateName: 'قنا',
        category: 'mosque',
        historicalEra: 'العصر الفاطمي والأيوبي والمملوكي',
        description: 'قوص كانت تاني أهم مدينة في مصر بعد القاهرة وملتقى حجاج الصعيد والتجار. المسجد جدده الوزير الفاطمي الصالح طلائع سنة 550 هجرية وصنع فيه المنبر الفريد.',
        history: 'المسجد العمري الأثري بقوص درة عاصمة الصعيد القديمة؛ بيضم أقدم منبر خشبي محفور ومؤرخ في العالم الإسلامي بالعهد الفاطمي ومئذنة أثرية.',
        significance: 'منبر المسجد العمري تحفة نادرة في تاريخ الفنون والنجارة الإسلامية، والمسجد أقدم جامع أثري باقٍ بقنا.',
        locationName: 'مدينة قوص، جنوب قنا',
        locationDescription: 'يقع في قلب مدينة قوص القديمة شرق النيل جنوب محافظة قنا.',
        visitorTips: 'المسجد مفتوح للصلاة والزيارة في قلب قوص، ادخل وشوف دقة حفر الخشب في المنبر والمحراب واستشعر عبق التاريخ.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 25.9185, lng: 32.7628 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعة',
        visitInfo: {
            visitStatus: 'active_institution',
            visitStatusLabel: 'مسجد أثري وصرح ديني نشط',
            visitStatusNote: 'المسجد تقام فيه الصلوات الخمس ومفتوح للمصلين والزوار مجاناً دون تذاكر سياحية تجارية، مع مراعاة أوقات الصلاة والسكينة.',
            openingHours: 'مفتوح طوال اليوم لمواقيت الصلاة ومن 8:00 ص حتى صلاة العشاء',
            bestTimeToVisit: 'بين وقتي الظهر والعصر لمشاهدة الزخارف بنور النهار',
            entryFee: 'مجاناً بالكامل',
            reservationRequired: false
        },
        access: {
            description: 'يقع بوسط مدينة قوص بجوار المحطة وميدان المدينة.',
            transportation: 'قطار الصعيد إلى محطة قوص أو ميكروباص من قنا أو الأقصر'
        },
        address: { governorate: 'قنا', city: 'قوص' },
        sourceName: 'وزارة السياحة والآثار - قطاع الآثار الإسلامية والقبطية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= سوهاج =================
    {
        id: 'place-red-monastery',
        title: 'الدير الأحمر (دير الأنبا بيشوي والأنبا بيجول)',
        slug: 'red-monastery-sohag',
        governorateId: 'gov-sohag',
        governorateName: 'سوهاج',
        category: 'monastery',
        historicalEra: 'القرن الخامس الميلادي (العصر القبطي البيزنطي)',
        description: 'الدير اتبنى بالآجر الأحمر في القرن الخامس في الجبل بسوهاج وتسمى باسم الأنبا بيشوي وبيجول. خضع لترميم دولي كشف عن طبقات رسوم وأعمدة رخامية أبهرت الخبراء.',
        history: 'الدير الأحمر بسوهاج معجزة الفريسكو والرسوم الجدارية الملونة في الشرق الأوسط؛ كنيسته بتضم أروع جداريات قبطية وبيزنطية لسه محتفظة ببهائها.',
        significance: 'أهم كنيسة بيزنطية وقبطية محتفظة بألوانها وزخارفها في مصر، ومسجل بالقائمة التمهيدية لليونسكو.',
        locationName: 'قرية الجبال الغربية، غرب سوهاج',
        locationDescription: 'يقع غرب مدينة سوهاج بنحو 12 كم على مقربة من الدير الأبيض عند سفح الجبل الغربي.',
        visitorTips: 'الدير قريب من الدير الأبيض غرب سوهاج، زور الاتنين في نفس الجولة واستمتع بهدوء المكان وشرح الرهبان.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 26.5492, lng: 31.6163 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة إلى ساعتين',
        visitInfo: {
            visitStatus: 'active_institution',
            visitStatusLabel: 'دير قبطي عامر وصرح روحي مفتوح',
            visitStatusNote: 'الدير يستقبل الزوار والسائحين والرحلات الدينية يومياً بالمجان مع مراعاة النظام الكنسي والضيافة الرهبانية دون تذاكر تجارية.',
            openingHours: 'يومياً من 8:00 ص حتى 6:00 م',
            bestTimeToVisit: 'فترة الصباح من 9:00 ص حتى 1:00 م',
            entryFee: 'مجاناً بالكامل (صرح ديني وتراثي مفتوح)',
            reservationRequired: false
        },
        access: {
            description: 'بالسيارات عبر الطريق الغربي بسوهاج بالقرب من الدير الأبيض.',
            transportation: 'تاكسي من مدينة سوهاج أو سيارات الرحلات المنظمة'
        },
        address: { governorate: 'سوهاج', city: 'سوهاج', village: 'نجع الدير' },
        sourceName: 'وزارة السياحة والآثار والكنيسة القبطية الأرثوذكسية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-sohag-museum',
        title: 'متحف سوهاج القومي',
        slug: 'sohag-national-museum',
        governorateId: 'gov-sohag',
        governorateName: 'سوهاج',
        category: 'museum',
        historicalEra: 'من عصور ما قبل التاريخ حتى العصر الحديث',
        description: 'المتحف افتتح سنة 2018 كنافذة حضارية لصعيد مصر، بيعرض مقتنيات من حفائر أبيدوس وأخميم، وبيبرز حرف النسيج والتطريز اللي اشتهرت بيها المحافظة.',
        history: 'متحف سوهاج القومي صرح حديث مبني على شكل صرح فرعوني على كورنيش نيل سوهاج؛ بيضم قطع أثرية تحكي قصة ملوك مصر من مينا وسيتي لحد التراث.',
        significance: 'متحف إقليمي متكامل بيجمع آثار سوهاج اللي كانت متفرقة، وتصميمه على النيل بيدي تجربة ثقافية مريحة.',
        locationName: 'كورنيش النيل الشرقي، مدينة سوهاج',
        locationDescription: 'يقع على كورنيش النيل مباشرة في قلب مدينة سوهاج.',
        visitorTips: 'المتحف مكيف ومجهز، ومكانه رائع على الكورنيش الشرقي، ومناسب جداً للعائلات والأطفال.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 26.5620, lng: 31.7050 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعتان',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة نهاراً ومساءً',
            visitStatusNote: 'المتحف يعمل فترتين يومياً ومجهز بمسارات خاصة لذوي الاحتياجات الخاصة.',
            openingHours: 'يومياً: 9:00 ص - 3:00 م ومن 5:00 م - 9:00 م',
            bestTimeToVisit: 'الفترة المسائية للتجول مع نسمات كورنيش النيل',
            entryFee: 'وفق تذاكر قطاع المتاحف بوزارة السياحة والآثار',
            reservationRequired: false
        },
        access: {
            description: 'في قلب كورنيش مدينة سوهاج، قريب من كافة الفنادق والخدمات.',
            transportation: 'تاكسي سوهاج الداخلي أو سيراً على الكورنيش'
        },
        address: { governorate: 'سوهاج', city: 'سوهاج' },
        sourceName: 'قطاع المتاحف - وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-sidi-arif-mosque',
        title: 'مسجد العارف بالله بسوهاج',
        slug: 'sidi-al-arif-mosque-sohag',
        governorateId: 'gov-sohag',
        governorateName: 'سوهاج',
        category: 'mosque',
        historicalEra: 'القرن الثامن الهجري وحتى العصر الحديث',
        description: 'المسجد يرجع للقرن الثامن للشيخ الصالح العارف بالله إسماعيل بن علي من كبار صوفية الصعيد. تم توسيعه وتجديده في العصر الحديث ليكون الصرح الأكبر.',
        history: 'مسجد العارف بالله في سوهاج أكبر مساجد المحافظة ومقصد أهالي الصعيد الروحي؛ بيتميز بمئذنتين رشيقتين وقبة شامخة وزخارف ونقوش مذهبة تملى القلب راحة.',
        significance: 'رمز الروحانية والتسامح في سوهاج، وملتقى الآلاف في ليالي الجمعة والمواسم ومولد سيدي العارف.',
        locationName: 'ميدان العارف، وسط مدينة سوهاج',
        locationDescription: 'يقع في قلب الميدان التاريخي لمدينة سوهاج بجوار الأسواق التجارية التراثية.',
        visitorTips: 'المسجد في قلب ميدان العارف، جنبه أسواق وعطارة والفطير ومخبوزات صعيدية تقدر تتمشى فيها.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 26.5510, lng: 31.6965 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: '45 دقيقة إلى ساعة',
        visitInfo: {
            visitStatus: 'active_institution',
            visitStatusLabel: 'مسجد جامع وصرح ديني نشط',
            visitStatusNote: 'المسجد مفتوح طوال اليوم للصلوات والذكر وزيارة الساحة والمقام بالمجان دون تذاكر دخول.',
            openingHours: 'مفتوح من صلاة الفجر حتى ما بعد صلاة العشاء',
            bestTimeToVisit: 'بين صلاتي العصر والمغرب',
            entryFee: 'مجاناً بالكامل',
            reservationRequired: false
        },
        access: {
            description: 'يقع في أشهر ميادين سوهاج وسهل الوصول إليه من كافة أرجاء المدينة.',
            transportation: 'تاكسي سوهاج الداخلي وميكروباصات ميدان العارف'
        },
        address: { governorate: 'سوهاج', city: 'سوهاج' },
        sourceName: 'مديرية أوقاف سوهاج ومحافظة سوهاج',
        sourceUrl: 'http://www.sohag.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-akhmeem-handloom',
        title: 'قرية أخميم وورش النسيج والحرير التراثية',
        slug: 'akhmeem-handloom-weaving-heritage',
        governorateId: 'gov-sohag',
        governorateName: 'سوهاج',
        category: 'heritage_village',
        historicalEra: 'من العصر الفرعوني حتى التراث الحديث',
        description: 'أخميم اشتهرت بجودة أنسجتها من فجر التاريخ. النساج بيعتمد على حركة رجليه وإيديه وتوافق بصري عشان يمرر المكوك بين خيوط السدى واللحمة.',
        history: 'قرية أخميم وورش النول بسوهاج عاصمة النسيج التراثي والحرير والكليم؛ عائلات بتتوارث القعاد قدام النول الخشبي وتطلع شيلان ومفارش بألوان وزخارف أصيلة.',
        significance: 'من أهم قلاع الحرف اليدوية الحية في مصر، بتحافظ على تراث إنساني عريق بتمسك أسطوات أخميم بصنعتهم.',
        locationName: 'مدينة أخميم، شرق سوهاج',
        locationDescription: 'تقع شرق النيل مباشرة مواجهة لمدينة سوهاج، وتنتشر ورش النول بجمعيات النساجين وحي الورش.',
        visitorTips: 'ادخل البيوت والورش وتكلم مع الأسطوات بنفسك، هيرحبوا بيك ويوروك الشغل وتشتري كليم أو شال أصلي.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 26.5635, lng: 31.7450 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعتين إلى ثلاث ساعات',
        visitInfo: {
            visitStatus: 'public_landmark',
            visitStatusLabel: 'منطقة حرفية وورش تراثية مفتوحة',
            visitStatusNote: 'الورش ومنافذ بيع الجمعيات التعاونية الإنتاجية للنساجين مفتوحة يومياً للجمهور للتجول والشراء المباشر من الحرفيين دون تذاكر.',
            openingHours: 'يومياً من 9:00 ص حتى 5:00 م',
            bestTimeToVisit: 'فترة الصباح لمشاهدة الحرفيين أثناء نسج القطع الفنية',
            entryFee: 'مجاناً للتجول ومشاهدة صناعة النسيج',
            reservationRequired: false
        },
        access: {
            description: 'عبر كوبري أخميم من مدينة سوهاج (10 دقائق بالسيارة).',
            transportation: 'تاكسي أو ميكروباص سوهاج - أخميم'
        },
        address: { governorate: 'سوهاج', city: 'أخميم' },
        sourceName: 'جمعية نساجي أخميم ومحافظة سوهاج',
        sourceUrl: 'http://www.sohag.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= أسيوط =================
    {
        id: 'place-assiut-barrage',
        title: 'قناطر أسيوط التاريخية وممشى النيل',
        slug: 'historic-assiut-barrage',
        governorateId: 'gov-asyut',
        governorateName: 'أسيوط',
        category: 'historical',
        historicalEra: 'أواخر القرن التاسع عشر (1898 - 1902م)',
        description: 'القناطر اتبنت بين 1898 و1902 باشتراك آلاف العمال المصريين، وصممت بـ 111 عينة من جرانيت أسوان عشان تحول حياض الصعيد للري الدائم عبر ترعة الإبراهيمية.',
        history: 'قناطر أسيوط التاريخية تحفة هندسية من جرانيت على نيل أسيوط؛ نظمت ري ملايين الأفدنة الزراعية في الصعيد، وجنبها ممشى نيل سياحي خلاب.',
        significance: 'شاهد على عبقرية الهندسة وبناء مصر الحديثة، ونقطة البداية لأطول ترعة صناعية في العالم (الإبراهيمية).',
        locationName: 'شمال مدينة أسيوط، على مجرى النيل',
        locationDescription: 'تقطع مجرى النيل وتربط بين ضفتي أسيوط عند مدخل فم ترعة الإبراهيمية.',
        visitorTips: 'الممشى السياحي عند القناطر مكان ممتاز للمشي والفسحة العائلية ساعة الغروب، والاستمتاع بمشهد مية النيل وهوا أسيوط.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 27.1994, lng: 31.1895 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعة',
        visitInfo: {
            visitStatus: 'public_landmark',
            visitStatusLabel: 'معلم وممشى عام مفتوح مجاناً',
            visitStatusNote: 'الموقع مفتوح كمعلم وممشى نهري عام للجمهور على مدار اليوم دون رسوم أو تذاكر.',
            openingHours: 'متاح على مدار 24 ساعة يومياً',
            bestTimeToVisit: 'فترة الغروب والمساء',
            entryFee: 'مجاناً بالكامل (معلم عام على الكورنيش)',
            reservationRequired: false
        },
        access: {
            description: 'تقع شمال مدينة أسيوط عند نهاية كورنيش النيل.',
            transportation: 'تاكسي أسيوط الداخلي أو سيراً على كورنيش النيل'
        },
        address: { governorate: 'أسيوط', city: 'أسيوط' },
        sourceName: 'وزارة الموارد المائية والري ومحافظة أسيوط',
        sourceUrl: 'http://www.assiut.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-qaysariya-assiut',
        title: 'سوق القيسارية العتيق ومسجد الكاشف بأسيوط',
        slug: 'qaysariya-heritage-bazaar-assiut',
        governorateId: 'gov-asyut',
        governorateName: 'أسيوط',
        category: 'heritage_village',
        historicalEra: 'العصر المملوكي والعثماني',
        description: 'السوق كان نهاية قوافل "درب الأربعين" اللي جاية من السودان محملة بالعاج والأبنوس والجلود والتوابل لأسيوط. وبيضم وكالات قديمة ومسجد الكاشف وحمام ثابت.',
        history: 'سوق القيسارية في أسيوط أقدم أسواق الصعيد؛ حارات مسقوفة بالخشب العتيق ومحلات عطارة وأقمشة وتلي ونحاس تنقلك لأيام درب الأربعين.',
        significance: 'متحف تجاري حي في قلب أسيوط القديمة، بيحافظ على طابع الأسواق الشرقية ومقايضة النحاس والعطارة والتطريز.',
        locationName: 'حي غرب، مدينة أسيوط القديمة',
        locationDescription: 'يمتد عبر الأزقة التراثية المتفرعة من شارع القيسارية غرب مدينة أسيوط.',
        visitorTips: 'اتمشى على رجلك في الحارات الضيقة، اشتري بهارات نقية وتلي وقماش بلدي، واستمتع بريحة البخور وعمارة الوكالات القديمة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 27.1812, lng: 31.1835 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة ونصف لساعتين',
        visitInfo: {
            visitStatus: 'public_landmark',
            visitStatusLabel: 'سوق تراثي عام وشوارع مفتوحة',
            visitStatusNote: 'السوق دائم الحركة والنشاط من الصباح الباكر حتى المساء ومفتوح مجاناً للتجول والتسوق كشارع عام دون أي تذاكر.',
            openingHours: 'يومياً من 9:00 ص حتى 10:00 م',
            bestTimeToVisit: 'فترة قبل الظهر أو بعد العصر للتجول والتسوق الممتع',
            entryFee: 'مجاناً بالكامل (سوق عام مفتوح)',
            reservationRequired: false
        },
        access: {
            description: 'يقع بحي غرب القديم بالقرب من ميدان المجذوب ومحطة القطار.',
            transportation: 'تاكسي أو سيراً من وسط أسيوط القديمة'
        },
        address: { governorate: 'أسيوط', city: 'أسيوط' },
        sourceName: 'محافظة أسيوط وقطاع الآثار الإسلامية',
        sourceUrl: 'http://www.assiut.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-meir-tombs',
        title: 'مقابر مير الصخرية بالقوصية',
        slug: 'meir-rock-cut-tombs-assiut',
        governorateId: 'gov-asyut',
        governorateName: 'أسيوط',
        category: 'tomb',
        historicalEra: 'الدولتان القديمة والوسطى (الأسرات 6 و12)',
        description: 'الجبانة كانت لأمراء الإقليم الـ 14 لمصر العليا. الفنان كان عنده جرأة فنية؛ رسم الناس الطبيعية بكل أشكالها من غير مبالغة، ورسم صيد الأسماك والرقصات.',
        history: 'مقابر مير في القوصية بأسيوط منحوتة في الجبل الغربي؛ مشهورة بنقوشها الواقعية الصادقة اللي صورت تفاصيل حياة الفلاحين والصيادين والرياضيين زمان.',
        significance: 'أهم مرجع تاريخي لتوثيق الحياة الاجتماعية والطبقات الشعبية في مصر القديمة، وتوضيح ميل فن الصعيد للواقعية والبساطة.',
        locationName: 'قرية مير، مركز القوصية، أسيوط',
        locationDescription: 'تقع على حافة الصحراء الغربية غرب مدينة القوصية شمال محافظة أسيوط بنحو 50 كم.',
        visitorTips: 'الموقع صاعد في الجبل بيطل على منظر ساحر للزراعات والنيل، البس كوتشي مريح واطلع السلالم واستمتع بالنقوش النادرة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 27.4475, lng: 30.7533 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة ونصف لساعتين',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية',
            visitStatusNote: 'الموقع مفتوح بإشراف مفتشي منطقة آثار القوصية وأسيوط.',
            openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
            bestTimeToVisit: 'الصباح الباكر في فصلي الخريف والشتاء',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار الرسمية',
            reservationRequired: false
        },
        access: {
            description: 'بالسيارة عبر طريق أسيوط - ديروط الزراعي حتى القوصية ثم غرباً إلى قرية مير والجبل.',
            transportation: 'سيارة خاصة أو تاكسي من القوصية أو أسيوط'
        },
        address: { governorate: 'أسيوط', city: 'القوصية', village: 'مير' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= المنيا =================
    {
        id: 'place-tuna-el-gebel',
        title: 'تونا الجبل وسراديب الإله تحوت الأسطورية',
        slug: 'tuna-el-gebel-necropolis',
        governorateId: 'gov-minya',
        governorateName: 'المنيا',
        category: 'historical',
        historicalEra: 'العصور المتأخرة والبطلمية والرومانية',
        description: 'الموقع كان الجبانة الرسمية للأشمونين في العصور اليونانية والرومانية. بيضم سراديب محفورة في الصخر لمئات الأمتار لدفن الحيوانات المقدسة، ومعاها مقبرة بيتوزيريس.',
        history: 'تونا الجبل في المنيا مدينة الأسرار والسراديب تحت الأرض؛ كانت جبانة الإله تحوت إله الحكمة، فيها آلاف المومياوات لطيور أبو منجل ومقبرة إيزادورا.',
        significance: 'موقع فريد بيضم أطول نصوص دينية وأدبية من العصر البطلمي، وقصة حب إيزادورا أول شهيدة حب في تاريخ مصر.',
        locationName: 'غرب ملوي، محافظة المنيا',
        locationDescription: 'تقع على حافة الصحراء الغربية غرب مدينة ملوي بنحو 18 كم.',
        visitorTips: 'لازم تزور السراديب تحت الأرض وتشوف إتقان حفر الصخور، ومقبرة إيزادورا، والبس جاكت لأن السراديب بتبقى باردة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 27.6105, lng: 30.7380 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعتان',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة السياحية',
            visitStatusNote: 'الموقع والسراديب ومقبرة بيتوزيريس والساقية مفتوحة للزيارة بتذكرة موحدة.',
            openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
            bestTimeToVisit: 'الصباح الباكر',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار (الدفع الإلكتروني)',
            reservationRequired: false
        },
        access: {
            description: 'بالسيارة من مدينة ملوي عبر الطريق الصحراوي الغربي المتفرع.',
            transportation: 'تاكسي من مدينة ملوي أو سيارة سياحية خاصة'
        },
        address: { governorate: 'المنيا', city: 'ملوي' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-ashmunein-malawi',
        title: 'مدينة الأشمونين الأثرية ومتحف ملوي',
        slug: 'el-ashmunein-malawi-museum',
        governorateId: 'gov-minya',
        governorateName: 'المنيا',
        category: 'museum',
        historicalEra: 'من الدولة القديمة حتى العصرين اليوناني والروماني',
        description: 'الأشمونين كانت عاصمة الإقليم الـ 15 ومهد أسطورة الخلق. في العصر الروماني تحولت لمركز مسيحي كبير واتبنت كنيسة بازيليكا بأعمدة جرانيت وردي صامدة.',
        history: 'مدينة الأشمونين في ملوي بالمنيا مدينة الحكمة "خمون" بتمثالي قرد البابون الجرانيتيين الضخمين وأطلال البازيليكا الرومانية، وجنبها متحف ملوي.',
        significance: 'رمز العلم والمعرفة في التاريخ القديم؛ وتمثالا البابون من أضخم تماثيل الحيوانات المنحوتة في مصر بوزن يتعدى 30 طن.',
        locationName: 'الأشمونين ومدينة ملوي، المنيا',
        locationDescription: 'تقع الأشمونين شمال غرب ملوي بنحو 8 كم، ومتحف ملوي بقلب شارع الجيش بالمدينة.',
        visitorTips: 'الموقع في الفضاء وسط حقول ملوي، اتصور جنب تمثال البابون العملاق وزور متحف ملوي بعد ما اترمم بالكامل.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 27.7810, lng: 30.8035 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعتان إلى ساعتين ونصف',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة',
            visitStatusNote: 'الموقع الأثري المفتوح ومتحف ملوي متاحان للزوار بتذاكر وزارة السياحة والآثار.',
            openingHours: 'يومياً من 9:00 ص حتى 4:00 م',
            bestTimeToVisit: 'فترة الصباح',
            entryFee: 'تذاكر معتمدة من وزارة السياحة والآثار',
            reservationRequired: false
        },
        access: {
            description: 'بالقرب من محطة قطار ملوي وطريق الصعيد الزراعي.',
            transportation: 'تاكسي ملوي أو ميكروباص من مدينة المنيا'
        },
        address: { governorate: 'المنيا', city: 'ملوي', village: 'الأشمونين' },
        sourceName: 'قطاع الآثار والمتاحف - وزارة السياحة والآثار',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-bahnasa',
        title: 'البهنسا (بقيع مصر وأرض الشهداء) ببني مزار',
        slug: 'al-bahnasa-martyrs-cemetery',
        governorateId: 'gov-minya',
        governorateName: 'المنيا',
        category: 'historical',
        historicalEra: 'فجر الإسلام والعصور الإسلامية اللاحقة',
        description: 'البهنسا (أوكسيرينخوس) شهدت معارك الفتح الإسلامي بقيادة قيس بن الحارث وعمرو بن العاص. استشهد على أرضها عدد كبير من الصحابة والتابعين، واتبنت قبورهم مقاصد للزوار.',
        history: 'البهنسا في بني مزار بالمنيا "بقيع مصر" وأرض الشهداء؛ مدينة تاريخية كبرى ومحطة الفتح الإسلامي، فيها أضرحة ومقامات لعشرات الصحابة وسط رمال الصحراء.',
        significance: 'أكبر مجمع لأضرحة وقباب الصحابة في إفريقيا، وموقع عالمي اكتشف فيه آلاف البرديات اليونانية والقبطية والإسلامية.',
        locationName: 'قرية البهنسا، مركز بني مزار، شمال المنيا',
        locationDescription: 'تقع غرب مدينة بني مزار بنحو 16 كم على حافة الظهير الصحراوي الغربي.',
        visitorTips: 'مكان ليه هيبة وروحانية عالية؛ اتجول بين القباب والأضرحة التاريخية وشوف شجرة مريم وبئر المسيح بالمنطقة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 28.5325, lng: 30.6650 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعتين إلى ثلاث ساعات',
        visitInfo: {
            visitStatus: 'public_landmark',
            visitStatusLabel: 'مزار ديني وتاريخي مفتوح بالمجان',
            visitStatusNote: 'الموقع والأضرحة والمساجد والجبانة التاريخية مفتوحة للزيارة وقراءة الفاتحة طوال اليوم بالمجان دون بوابات أو تذاكر.',
            openingHours: 'مفتوح يومياً من الصباح الباكر حتى صلاة المغرب',
            bestTimeToVisit: 'صباح يوم الجمعة أو فترة قبل الظهر',
            entryFee: 'مجاناً بالكامل (مزار ديني وروحي مفتوح)',
            reservationRequired: false
        },
        access: {
            description: 'طريق بني مزار - البهنسا المتفرع من طريق الصعيد الزراعي أو الصحراوي الغربي.',
            transportation: 'ميكروباص بني مزار - البهنسا أو سيارات خاصة'
        },
        address: { governorate: 'المنيا', city: 'بني مزار', village: 'البهنسا' },
        sourceName: 'محافظة المنيا وهيئة الآثار الإسلامية والقبطية',
        sourceUrl: 'http://www.elminia.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= بني سويف =================
    {
        id: 'place-ahnasya',
        title: 'منطقة آثار إهناسيا المدينة (هيراكليوبوليس ماجنا)',
        slug: 'ahnasya-herakleopolis-magna',
        governorateId: 'gov-bani-suef',
        governorateName: 'بني سويف',
        category: 'historical',
        historicalEra: 'عصر الانتقال الأول (الأسرتان 9 و10) والعصور اللاحقة',
        description: 'إهناسيا كانت عاصمة للبلاد في عصر الانتقال الأول، ونشأ فيها أدب زي "شكاوى الفلاح الفصيح". تضم أطلال معابد كبرى للإله حريشف شيدها رمسيس التاني.',
        history: 'منطقة آثار إهناسيا ببني سويف عاصمة مصر في عصر الأسرتين التاسعة والعاشرة؛ مدينة "حنن-نسو" ومركز عبادة حريشف، فيها أطلال معابد ومقابر ملوك الدولة.',
        significance: 'شاهد أثري على عصور التحول السياسي والفكري في مصر القديمة ومهد الأدب الاجتماعي.',
        locationName: 'مركز إهناسيا، غرب بني سويف',
        locationDescription: 'تقع غرب مدينة بني سويف بنحو 17 كم في قرية أم الكيمان بإهناسيا المدينة.',
        visitorTips: 'الموقع مفتوح للتجول بين صالات الأعمدة، قريب من مدينة بني سويف وميدوم، ومناسب لعشاق دراسة تاريخ العواصم القديمة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.0833, lng: 30.9333 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعة ونصف',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية',
            visitStatusNote: 'الموقع الأثري والمتحف المفتوح يستقبل الزوار بتذاكر وزارة السياحة والآثار.',
            openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
            bestTimeToVisit: 'فترة الصباح',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار المصرية',
            reservationRequired: false
        },
        access: {
            description: 'عبر طريق بني سويف - إهناسيا الزراعي الغربي.',
            transportation: 'ميكروباص أو تاكسي من مدينة بني سويف إلى إهناسيا'
        },
        address: { governorate: 'بني سويف', city: 'إهناسيا', village: 'إهناسيا المدينة' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-beni-suef-museum',
        title: 'متحف آثار بني سويف القومي',
        slug: 'beni-suef-national-museum',
        governorateId: 'gov-bani-suef',
        governorateName: 'بني سويف',
        category: 'museum',
        historicalEra: 'من عصور ما قبل التاريخ حتى العصر الحديث',
        description: 'المتحف اتأسس سنة 1997 لتوثيق تاريخ بني سويف كبوابة الصعيد. بيعرض مقتنيات من حفائر إهناسيا ودشاشة وميدوم، ويسلط الضوء على أدوات الزراعة والنسيج.',
        history: 'متحف آثار بني سويف في قلب حديقة النصر؛ بيضم سجلاً لكنوز المحافظة عبر العصور الفرعونية والقبطية والإسلامية، من تماثيل إهناسيا لمقتنيات ميدوم.',
        significance: 'متحف تعليمي وثقافي بيحفظ الهوية الحضارية لبني سويف وتراثها الإقليمي المتنوع.',
        locationName: 'حديقة النصر، شارع الجيش، بني سويف',
        locationDescription: 'يقع داخل حديقة النصر التاريخية بقلب مدينة بني سويف بالقرب من محطة القطار.',
        visitorTips: 'موقعه متميز في حديقة النصر وسهل الوصول ليه، جولة خفيفة ومفيدة جداً للتعرف على آثار المحافظة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.0744, lng: 31.0988 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعة',
        visitInfo: {
            visitStatus: 'closed_for_restoration',
            visitStatusLabel: 'مغلق للترميم والتطوير الشامل',
            visitStatusNote: 'تخضع قاعات العرض المتحفي حالياً لأعمال مشروع التطوير والتأهيل الأثري الشامل من قبل وزارة السياحة والآثار، ولا تتوفر تذاكر زيارة داخلية للجمهور حالياً.',
            openingHours: 'مغلق داخلياً للترميم (الحديقة الخارجية متاحة نهاراً)',
            bestTimeToVisit: 'متابعة إعلانات وزارة السياحة والآثار لإعادة الافتتاح',
            entryFee: 'لا توجد تذاكر حالياً نظراً لأعمال التطوير',
            reservationRequired: true
        },
        access: {
            description: 'بوسط مدينة بني سويف بجوار حديقة النصر ومحطة القطار.',
            transportation: 'تاكسي بني سويف أو سيراً من وسط المدينة'
        },
        address: { governorate: 'بني سويف', city: 'بني سويف' },
        sourceName: 'قطاع المتاحف - وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= الفيوم =================
    {
        id: 'place-wadi-al-hitan',
        title: 'محمية وادي الحيتان (موقع تراث طبيعي عالمي لليونسكو)',
        slug: 'wadi-al-hitan-valley-of-whales',
        governorateId: 'gov-faiyum',
        governorateName: 'الفيوم',
        category: 'nature',
        historicalEra: 'عصر الإيوسين (قبل 40 مليون سنة)',
        description: 'الموقع زمان كان قاع لبحر تيثيس. الحفريات المحفوظة نادرة لأنها بتوثق مرحلة تطور الحيتان من كائنات برية لأربع أرجل لكائنات بحرية زي حوت "باسيلوسورس".',
        history: 'محمية وادي الحيتان بالفيوم أول موقع تراث طبيعي عالمي باليونسكو في مصر؛ متحف جيولوجي في الصحراء بيضم هياكل حيتان متحجرة من 40 مليون سنة.',
        significance: 'أعظم موقع في العالم لدراسة تطور حياة الحيتان وثدييات البحار القديمة وصنفته اليونسكو كموقع استثنائي.',
        locationName: 'محمية وادي الريان، صحراء الفيوم الغربية',
        locationDescription: 'يقع في عمق صحراء وادي الريان جنوب غرب بحيرة قارون بنحو 90 كم من مدينة الفيوم.',
        visitorTips: 'الموقع منظم بمسارات مشي ومتحف مغطى، الأفضل تروحه الصبح بدري بعربية دفع رباعي وتستمتع بمشهد النجوم بالليل.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.2700, lng: 30.0430 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'نصف يوم إلى يوم كامل (تخييم مصرح)',
        visitInfo: {
            visitStatus: 'requires_safari_permit',
            visitStatusLabel: 'محمية طبيعية ومسار سفاري مصرح',
            visitStatusNote: 'الزيارة مفتوحة بتذاكر ورسوم محميات وزارة البيئة وتتطلب وسيلة انتقال مناسبة (سيارة دفع رباعي أو رحلة سفاري مرخصة).',
            openingHours: 'يومياً من 8:00 ص حتى 5:00 م (والتخييم الليلي بتصريح مسبق)',
            bestTimeToVisit: 'من شهر أكتوبر حتى أبريل للتمتع بالطقس المعتدل وسماء النجوم الصافية',
            entryFee: 'تذاكر رسوم المحميات الطبيعية لوزارة البيئة المصرية + تذكرة متحف الحفريات',
            reservationRequired: false
        },
        access: {
            description: 'من طريق وادي الريان بالفيوم وصولاً إلى مدق وادي الحيتان الممهد لمسافة 35 كم داخل الصحراء.',
            transportation: 'سيارات الدفع الرباعي 4x4 أو رحلات السفاري المرخصة من القاهرة أو الفيوم'
        },
        address: { governorate: 'الفيوم', city: 'يوسف الصديق' },
        sourceName: 'منظمة اليونسكو وقطاع حماية الطبيعة بوزارة البيئة المصرية',
        sourceUrl: 'https://whc.unesco.org/en/list/1186',
        sourceType: 'unesco',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-tunis-village',
        title: 'قرية تونس التراثية ومتحف الكاريكاتير بالفيوم',
        slug: 'tunis-village-faiyum',
        governorateId: 'gov-faiyum',
        governorateName: 'الفيوم',
        category: 'heritage_village',
        historicalEra: 'العمارة البيئية وفنون الخزف المعاصرة',
        description: 'الفنانة السويسرية استقرت في القرية وأسست مدرسة لتعليم الأطفال الخزف. بمرور السنين ولاد القرية بقوا فنانين كبار، واتحولت البيوت لورش وجاليريهات ومقصد لعشاق الهدوء.',
        history: 'قرية تونس بالفيوم عاصمة الفخار والخزف والهدوء على شط قارون؛ حولتها الفنانة إيفيلين بوريه لملتقى عالمي لصناع الخزف من ولاد القرية.',
        significance: 'نموذج ملهم للتنمية الريفية المستدامة القائمة على الفن الحرفي والحفاظ على البيئة الطبيعية والعمارة الطينية.',
        locationName: 'قرية تونس، مركز يوسف الصديق، الفيوم',
        locationDescription: 'تقع على ربوة تطل على الطرف الجنوبي لبحيرة قارون وشمال وادي الريان.',
        visitorTips: 'اتمشى في شوارع القرية الترابية الهادية، ادخل ورش الخزف وجرب تشكل طين بنفسك، وزور متحف الكاريكاتير على شط البحيرة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.4180, lng: 30.5050 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من نصف يوم إلى يوم كامل',
        visitInfo: {
            visitStatus: 'public_landmark',
            visitStatusLabel: 'قرية بيئية وتراثية مفتوحة',
            visitStatusNote: 'القرية مفتوحة للجميع مجاناً للتجول، وورش الخزف والمطاعم البيئية ومتحف الكاريكاتير تقدم خدماتها ومنتجاتها بشكل مستقل دون أي تذاكر لدخول القرية.',
            openingHours: 'يومياً من 9:00 ص حتى غروب الشمس',
            bestTimeToVisit: 'فصل الخريف والربيع، وموسم مهرجان تونس السنوي للخزف',
            entryFee: 'مجاناً للتجول بالقرية (رسوم رمزية اختيارية لورش الخزف والمتحف)',
            reservationRequired: false
        },
        access: {
            description: 'طريق بحيرة قارون السياحي غرباً من مدينة الفيوم (حوالي 45 كم).',
            transportation: 'سيارات خاصة، تاكسي، أو ميكروباص من موقف الفيوم إلى يوسف الصديق وتونس'
        },
        address: { governorate: 'الفيوم', city: 'يوسف الصديق', village: 'تونس' },
        sourceName: 'محافظة الفيوم وقطاع الفنون التشكيلية',
        sourceUrl: 'http://www.fayoum.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-wadi-el-rayan',
        title: 'محمية وادي الريان والشلالات الطبيعية بالفيوم',
        slug: 'wadi-el-rayan-waterfalls-faiyum',
        governorateId: 'gov-faiyum',
        governorateName: 'الفيوم',
        category: 'nature',
        historicalEra: 'محمية طبيعية جيولوجية',
        description: 'المنطقة أعلنت محمية سنة 1989 وتتكون من بحيرتين من مية الصرف، وفرق المنسوب هو اللي عمل الشلالات. وتضم المحمية جبل المدورة والطيور المهاجرة.',
        history: 'محمية وادي الريان بالفيوم واحة طبيعية بتضم الشلالات الطبيعية الوحيدة في مصر اللي بتربط بين بحيرتين وسط تلال وكثبان الصحراء.',
        significance: 'بيئة صحراوية ومائية فريدة بتجمع بين عيون الكبريت والكثبان الرملية الناعمة وشلالات المية وحفريات الحيتان.',
        locationName: 'جنوب غرب الفيوم',
        locationDescription: 'تقع في منخفض وادي الريان جنوب غرب بحيرة قارون بنحو 40 كم.',
        visitorTips: 'تقدر تركب فلوكة في بحيرة الشلالات، وتطلع قمة جبل المدورة تاخد صور خيالية، وتجرب التزحلق على الرمال بالكثبان المجاورة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.0780, lng: 30.4070 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من 3 إلى 5 ساعات',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'محمية طبيعية مفتوحة للزوار',
            visitStatusNote: 'مفتوحة للجمهور بتذاكر رسوم وزارة البيئة عند بوابة الدخول الرسمية.',
            openingHours: 'يومياً من 8:00 ص حتى 5:00 م',
            bestTimeToVisit: 'فترة الصباح حتى العصر من أكتوبر حتى مايو',
            entryFee: 'تذاكر المحميات الطبيعية لوزارة البيئة المصرية',
            reservationRequired: false
        },
        access: {
            description: 'طريق وادي الريان الإسفلتي المباشر من مدينة الفيوم أو طريق القاهرة - الفيوم الصحراوي.',
            transportation: 'سيارات خاصة أو حافلات الرحلات اليومية'
        },
        address: { governorate: 'الفيوم', city: 'إطسا' },
        sourceName: 'جهاز شؤون البيئة - قطاع حماية الطبيعة بجمهورية مصر العربية',
        sourceUrl: 'http://www.eeaa.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-qasr-qarun',
        title: 'قصر قارون ومعبد ديونيسياس البطلمي',
        slug: 'qasr-qarun-dionysias-temple',
        governorateId: 'gov-faiyum',
        governorateName: 'الفيوم',
        category: 'temple',
        historicalEra: 'العصر البطلمي (القرن الثالث ق.م)',
        description: 'المعبد اتبنى في العصر البطلمي لعبادة سوبك، ورغم إن العامة سموه "قصر قارون", إلا إنه معبد ديني ملوش علاقة بقارون. بيتميز بحفظ كامل لجدرانه وسلالمه.',
        history: 'قصر قارون بالفيوم معبد بطلمي فريد مبني من الحجر الجيري على طرف بحيرة قارون، مشهور بتعامد الشمس على قدس أقداسه يوم 21 ديسمبر.',
        significance: 'آية في الإتقان المعماري والحسابات الفلكية القديمة اللي وجهت أشعة الشمس للمحراب في يوم محدد، وحصن حرس قوافل الواحات.',
        locationName: 'قرية قصر قارون، غرب الفيوم',
        locationDescription: 'يقع في أقصى الطرف الغربي لبحيرة قارون شمال غرب محافظة الفيوم بنحو 50 كم.',
        visitorTips: 'المعبد كامل السقف، ادخل الصالات والسراديب واطلع السطح عشان تشوف مشهد الصحراء والبحيرة، وحضر احتفالية تعامد الشمس.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.4042, lng: 30.4081 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعة ونصف',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية',
            visitStatusNote: 'المعبد متاح للزيارة السياحية بتذاكر وزارة السياحة والآثار.',
            openingHours: 'يومياً من 8:00 ص حتى 5:00 م',
            bestTimeToVisit: 'الصباح الباكر، وموعد التعامد السنوي صباح 21 ديسمبر',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار الرسمية',
            reservationRequired: false
        },
        access: {
            description: 'عبر طريق بحيرة قارون السياحي غرباً حتى قرية قصر قارون.',
            transportation: 'سيارة خاصة أو تاكسي من مدينة الفيوم أو أبشواي'
        },
        address: { governorate: 'الفيوم', city: 'يوسف الصديق', village: 'قصر قارون' },
        sourceName: 'وزارة السياحة والآثار المصرية ومحافظة الفيوم',
        sourceUrl: 'http://www.egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-faiyum-waterwheels',
        title: 'سواقي الهدير التاريخية وميدان السواقي بالفيوم',
        slug: 'historic-faiyum-waterwheels',
        governorateId: 'gov-faiyum',
        governorateName: 'الفيوم',
        category: 'historical',
        historicalEra: 'العصر البطلمي والتراث الشعبي المتوارث',
        description: 'مهندسو العصر البطلمي ابتكروا نظام السواقي لتوزيع مية بحر يوسف بدون ماكينات. النجارين بيتوارثوا صناعتها من خشب التوت والسنط، وكل ساقية فيها قواديس.',
        history: 'سواقي الهدير بالفيوم السواقي الخشبية العريقة وشعار المحافظة؛ بتلف بقوة مية بحر يوسف من مئات السنين وترفع المية للغيطان بصوت هديرها اللي بيطرب.',
        significance: 'رمز الهوية والعبقرية الهيدروليكية في مصر، ونظام ري بيئي وتراثي فريد ملوش مثيل في العالم.',
        locationName: 'ميدان السواقي ومجرى بحر يوسف، قلب مدينة الفيوم',
        locationDescription: 'تتوزع على مجرى بحر يوسف وترعة بحر تنهلا وبميدان السواقي الرئيسي وسط المدينة.',
        visitorTips: 'زور ميدان السواقي في قلب الفيوم أو اتفرج عليها في القرى، واقعد استمتع بصوت هدير المية والنسيم العليل.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.3090, lng: 30.8420 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعة',
        visitInfo: {
            visitStatus: 'public_landmark',
            visitStatusLabel: 'معلم وميدان عام مفتوح مجاناً',
            visitStatusNote: 'الميدان وممشى السواقي مفتوح على مدار 24 ساعة يومياً للجمهور كمعلم عام دون أي رسوم أو تذاكر.',
            openingHours: 'متاح على مدار 24 ساعة يومياً',
            bestTimeToVisit: 'فترة ما بعد العصر والمساء',
            entryFee: 'مجاناً بالكامل (معلم عام وميدان مفتوح)',
            reservationRequired: false
        },
        access: {
            description: 'في قلب مدينة الفيوم بالقرب من محطة السكة الحديد ومقر المحافظة.',
            transportation: 'سيراً من وسط المدينة أو تاكسي الفيوم الداخلي'
        },
        address: { governorate: 'الفيوم', city: 'الفيوم' },
        sourceName: 'محافظة الفيوم والهيئة العامة للاستعلامات',
        sourceUrl: 'http://www.fayoum.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= الوادي الجديد =================
    {
        id: 'place-bagawat-necropolis',
        title: 'جبانة البجوات الأثرية بواحة الخارجة',
        slug: 'al-bagawat-necropolis-kharga',
        governorateId: 'gov-new-valley',
        governorateName: 'الوادي الجديد',
        category: 'tomb',
        historicalEra: 'القرنان الرابع والسابع الميلادي (المسيحية المبكرة)',
        description: 'المسيحيين الأوائل لجأوا لواحة الخارجة هرباً من اضطهاد الرومان في القرنين الرابع والخامس وعمروا الواحة. جدران المزارات مرسوم عليها ذبح إبراهيم وسفينة نوح.',
        history: 'جبانة البجوات في واحة الخارجة من أقدم المقابر المسيحية في العالم؛ بتضم 263 مزار قبابي بالطوب اللبن وسط الرمال، ورسومات لقصص الأنبياء.',
        significance: 'أهم وثيقة معمارية وفنية تشهد على بزوغ الفن القبطي والعمارة القبابية في العالم، ومسجلة في التمهيدية لليونسكو.',
        locationName: 'شمال واحة الخارجة، الوادي الجديد',
        locationDescription: 'تقع خلف معبد هيبس عند سفح جبل طارق شمال مدينة الخارجة بنحو 3 كم.',
        visitorTips: 'مكان ساحر في الصحراء ورا معبد هيبس، ادخل كنيسة السلام ومزار الخروج وتأمل دقة الرسوم والرموز الإيمانية البسيطة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 25.4855, lng: 30.5530 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة ونصف لساعتين',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية',
            visitStatusNote: 'الموقع مفتوح يومياً بإشراف منطقة آثار الوادي الجديد بتذاكر وزارة السياحة والآثار.',
            openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
            bestTimeToVisit: 'فترة الصباح',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار المصرية',
            reservationRequired: false
        },
        access: {
            description: 'على بعد دقائق من معبد هيبس وطريق الخارجة - أسيوط.',
            transportation: 'تاكسي من مدينة الخارجة'
        },
        address: { governorate: 'الوادي الجديد', city: 'الخارجة' },
        sourceName: 'وزارة السياحة والآثار ومحافظة الوادي الجديد',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-dush-temple',
        title: 'معبد وحصن دوش الأثري بواحة باريس',
        slug: 'temple-fortress-of-dush',
        governorateId: 'gov-new-valley',
        governorateName: 'الوادي الجديد',
        category: 'historical',
        historicalEra: 'العصر البطلمي والروماني (عهد دوميتيان وتراجان وحيدريان)',
        description: 'المعبد اتبنى في العصرين البطلمي والروماني على ربوة عالية كاشفة لدروب القوافل القادمة من السودان، ومحاط بحصن عسكري ضخم من الطوب اللبن متعدد الطوابق.',
        history: 'معبد وحصن دوش في جنوب واحة باريس بالوادي الجديد قلعة رومانية ومعبد حجري شيدوا لحراسة قوافل درب الأربعين، والمكان اللي اتلقى فيه كنز دوش.',
        significance: 'أهم نقطة حراسة تاريخية على مسار درب الأربعين، ومصدر التاج والذهب الملكي المعروض بمتحف الحضارة.',
        locationName: 'قرية دوش، مركز باريس، جنوب الوادي الجديد',
        locationDescription: 'يقع جنوب واحة باريس بنحو 23 كم، وجنوب مدينة الخارجة بنحو 115 كم.',
        visitorTips: 'الموقع في واحة باريس جنوب الخارجة، بيتميز بإطلالة صحراوية مهيبة وتجربة فريدة لاندماج الحجر بالطوب اللبن.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 24.5822, lng: 30.7180 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'ساعتان',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية',
            visitStatusNote: 'الموقع مفتوح للزيارة السياحية بتذاكر وزارة السياحة والآثار.',
            openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
            bestTimeToVisit: 'الصباح الباكر في فصل الشتاء',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار',
            reservationRequired: false
        },
        access: {
            description: 'طريق الخارجة - باريس المعبد ثم جنوباً نحو قرية دوش الأثرية.',
            transportation: 'سيارة خاصة أو حافلات الرحلات الاستكشافية من الخارجة'
        },
        address: { governorate: 'الوادي الجديد', city: 'باريس', village: 'دوش' },
        sourceName: 'وزارة السياحة والآثار والمعهد الفرنسي للآثار الشرقية IFAO',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },

    // ================= البحر الأحمر =================
    {
        id: 'place-quseir-fort',
        title: 'قلعة القصير العثمانية وميناء الحجاج والتجارة القديم',
        slug: 'el-quseir-ottoman-fort-port',
        governorateId: 'gov-red-sea',
        governorateName: 'البحر الأحمر',
        category: 'historical',
        historicalEra: 'العصر العثماني (1571م) وما قبله من عصور فرعونية وإسلامية',
        description: 'مدينة القصير أقدم موانئ البحر الأحمر وتاريخها متصل بالصعيد من أيام الفراعنة. القلعة شيدت سنة 1571 لحماية الحجاج والبضائع لمكة، وشهدت معارك الحملة الفرنسية.',
        history: 'قلعة القصير العثمانية الحصن اللي بناه سليم الأول لحماية ميناء القصير وقوافل حجاج الصعيد والتجارة على البحر الأحمر عند نهاية درب وادي الحمامات.',
        significance: 'أعظم قلعة حربية عثمانية باقية على ساحل البحر الأحمر، وشاهد على ارتباط الصعيد بالبحر ودروب الحج.',
        locationName: 'وسط مدينة القصير التاريخية، محافظة البحر الأحمر',
        locationDescription: 'تقع على تلة تشرف على ميناء القصير القديم وساحل البحر الأحمر مباشرة.',
        visitorTips: 'القلعة في قلب القصير؛ ادخل وزور غرف الحامية والمدافع، واطلع برج المراقبة عشان تشوف منظر بانورامي للبحر وبيوت الحجر المرجاني.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 26.1070, lng: 34.2800 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة ونصف لساعتين',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية والسياحية',
            visitStatusNote: 'القلعة ومتحفها الأثري مفتوحان يومياً بتذاكر وزارة السياحة والآثار.',
            openingHours: 'يومياً من 9:00 ص حتى 5:00 م',
            bestTimeToVisit: 'فترة الصباح أو العصر قبل الغروب',
            entryFee: 'وفق تذاكر قطاع الآثار الإسلامية والقبطية',
            reservationRequired: false
        },
        access: {
            description: 'بوسط مدينة القصير، وترتبط بمحافظة قنا عبر طريق قنا - سفاجا - القصير أو طريق قفط - القصير.',
            transportation: 'سيارات الأجرة أو حافلات النقل العام أو الجولات السياحية'
        },
        address: { governorate: 'البحر الأحمر', city: 'القصير' },
        sourceName: 'قطاع الآثار الإسلامية والقبطية - وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-hawara-pyramid',
        title: 'هرم هوارة وقصر التيه (لابرنت أمنمحات الثالث)',
        slug: 'hawara-pyramid-labyrinth-faiyum',
        governorateId: 'gov-faiyum',
        governorateName: 'الفيوم',
        category: 'temple',
        historicalEra: 'الدولة الوسطى - الأسرة 12 (عهد أمنمحات الثالث)',
        description: 'أمنمحات الثالث بنى هرمه من ملايين قوالب الطوب اللبن وكساه بالحجر الجيري لتأمين مقبرته بنظام هندسي معقد. وبجوار الهرم شيد معبده الجنائزي الضخم "اللابرنت".',
        history: 'هرم هوارة بالفيوم هرم الطوب اللبن للملك أمنمحات الثالث وموقع "قصر التيه" الأسطوري اللي وصفه هيرودوت بأنه معجزة معمارية تفوق أهرامات الجيزة.',
        significance: 'تحفة هندسية من الدولة الوسطى وشاهد على مشروعات استصلاح وتطوير الفيوم الكبرى وقنوات بحر يوسف.',
        locationName: 'قرية هوارة المقطع، جنوب شرق الفيوم',
        locationDescription: 'يقع على بعد 9 كم جنوب شرق مدينة الفيوم عند مدخل ترعة بحر يوسف إلى المنخفض.',
        visitorTips: 'الموقع قريب من مدينة الفيوم؛ تقدر تشوف بقايا الهرم ومصاطب العصر اليوناني وتتخيل عظمة قصر التيه.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.2730, lng: 30.8986 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعة إلى ساعة ونص',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية',
            visitStatusNote: 'المنطقة الأثرية المفتوحة بهوارة تستقبل الزوار بتذاكر وزارة السياحة والآثار، والدخول إلى باطن الهرم مغلق لارتفاع منسوب المياه الجوفية.',
            openingHours: 'يومياً من 8:00 ص حتى 4:00 م',
            bestTimeToVisit: 'فترة الصباح',
            entryFee: 'وفق تذاكر وزارة السياحة والآثار المصرية (الدفع بالبطاقات البنكية)',
            reservationRequired: false
        },
        access: {
            description: 'طريق الفيوم - بني سويف القديم جنوب شرق مدينة الفيوم بنحو 9 كم.',
            transportation: 'سيارة خاصة أو تاكسي من مدينة الفيوم'
        },
        address: { governorate: 'الفيوم', city: 'الفيوم', village: 'هوارة المقطع' },
        sourceName: 'وزارة السياحة والآثار المصرية',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-karanis-kom-aushim',
        title: 'مدينة كرانيس الأثرية ومتحف كوم أوشيم بالفيوم',
        slug: 'karanis-kom-aushim-museum-faiyum',
        governorateId: 'gov-faiyum',
        governorateName: 'الفيوم',
        category: 'museum',
        historicalEra: 'العصر البطلمي والروماني (القرن الثالث ق.م - القرن الخامس الميلادي)',
        description: 'أسسها بطليموس الثاني كمدينة للمحاربين القدامى واستصلاح الأراضي. فضلت عامرة بالحياة أكتر من 800 سنة، وحفظت رمال الصحراء بيوتها وبردياتها بحالة نادرة.',
        history: 'مدينة كرانيس في كوم أوشيم بالفيوم أكبر وأكمل مدينة يونانية ورومانية باقية في الصعيد؛ شوارع ببيوت من طابقين، ومعاصر زيتون، ومعابد للتمساح.',
        significance: 'أكمل نموذج لمدينة رومانية ريفية متكاملة المرافق في مصر، وبتضم معبدين من الحجر الجيري وحمامات عامة.',
        locationName: 'كوم أوشيم، شمال الفيوم على طريق القاهرة',
        locationDescription: 'تقع على بعد 30 كم شمال مدينة الفيوم عند الكيلو 70 على طريق القاهرة - الفيوم الصحراوي.',
        visitorTips: 'ادخل واتمشى جوة البيوت الرومانية واطلع السلالم، وزور متحف كوم أوشيم عند المدخل اللي بيضم بورتريهات الفيوم النادرة.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 29.5167, lng: 30.9000 },
        isFeatured: false,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعتين إلى ساعتين ونص',
        visitInfo: {
            visitStatus: 'open',
            visitStatusLabel: 'مفتوح للزيارة الأثرية والمتحفية',
            visitStatusNote: 'الموقع الأثري المكشوف لكرانيس ومتحف كوم أوشيم متاحان يومياً بتذاكر وزارة السياحة والآثار.',
            openingHours: 'يومياً من 9:00 ص حتى 4:00 م',
            bestTimeToVisit: 'فترة الصباح حتى منتصف النهار',
            entryFee: 'وفق لائحة وزارة السياحة والآثار (الدفع بالبطاقات البنكية)',
            reservationRequired: false
        },
        access: {
            description: 'مباشرة على طريق القاهرة - الفيوم الصحراوي عند بوابة كوم أوشيم الصناعية والزراعية.',
            transportation: 'سيارة خاصة أو حافلات وميكروباص طريق القاهرة - الفيوم'
        },
        address: { governorate: 'الفيوم', city: 'طامية', village: 'كوم أوشيم' },
        sourceName: 'قطاع الآثار المصرية والمتاحف - وزارة السياحة والآثار',
        sourceUrl: 'https://egymonuments.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-st-anthony-monastery',
        title: 'دير القديس الأنبا أنطونيوس (أقدم دير مأهول في العالم)',
        slug: 'st-anthony-monastery-red-sea',
        governorateId: 'gov-red-sea',
        governorateName: 'البحر الأحمر',
        category: 'monastery',
        historicalEra: 'القرن الرابع الميلادي (حوالي 356م)',
        description: 'الدير اتأسس في القرن الرابع في مكان عيشة القديس، وبيضم كنيسة أثرية بأسوار حصينة وينابيع مية عذبة متدفقة من الجبل. وفوق قمة الجبل مغارة الأنبا أنطونيوس.',
        history: 'دير الأنبا أنطونيوس في واحة جبل الجلالة بالصحراء الشرقية أقدم دير مسكون في العالم؛ مهد الرهبنة وتأسيس فكرة التوحد على يد أنطونيوس الكبير.',
        significance: 'المنبع الروحي الأول لكل أديرة ورهبان العالم في الشرق والغرب، وتحفة معمارية روحية في قلب الصحراء.',
        locationName: 'جبل الجلالة، واحة الأنبا أنطونيوس، محافظة البحر الأحمر',
        locationDescription: 'يقع في عمق الصحراء الشرقية عند سفح جبل الجلالة القبلي جنوب الزعفرانة بنحو 45 كم، متصلاً بطرق قوافل الصعيد القديمة.',
        visitorTips: 'لو صحتك تمام، اصعد السلالم الجبلية (1200 درجة) لمغارة القديس واستمتع بإطلالة لا تُنسى على البحر الأحمر، وزور كنيسة الدير.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 28.9242, lng: 32.3508 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من ساعتين ونص إلى 4 ساعات',
        visitInfo: {
            visitStatus: 'active_institution',
            visitStatusLabel: 'دير قبطي عامر وصرح روحي مفتوح',
            visitStatusNote: 'الدير يستقبل الزوار والسائحين والرحلات الدينية يومياً بالمجان مع مراعاة النظام الكنسي والضيافة الرهبانية دون تذاكر تجارية.',
            openingHours: 'يومياً من 8:00 ص حتى 5:00 م (مع مراعاة مواعيد القداسات الكنسية)',
            bestTimeToVisit: 'فصل الشتاء والربيع (الطقس معتدل في الجبل)',
            entryFee: 'مجاناً بالكامل (صرح ديني وتاريخي عامر)',
            reservationRequired: false
        },
        access: {
            description: 'طريق الكريمات - الزعفرانة أو طريق السويس - الغردقة الساحلي ثم التوجه غرباً 14 كم في مدق أسفلتي مباشر للدير.',
            transportation: 'سيارة خاصة أو حافلات الرحلات المنظمة'
        },
        address: { governorate: 'البحر الأحمر', city: 'رأس غارب' },
        sourceName: 'دير القديس الأنبا أنطونيوس والكنيسة القبطية الأرثوذكسية وقطاع الآثار القبطية',
        sourceUrl: 'https://copticorthodox.church',
        sourceType: 'official',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 'place-wadi-el-gemal',
        title: 'محمية وادي الجمال الطبيعية والتاريخية (حوض حماطة وسكيك)',
        slug: 'wadi-el-gemal-national-park',
        governorateId: 'gov-red-sea',
        governorateName: 'البحر الأحمر',
        category: 'nature',
        historicalEra: 'محمية طبيعية وتراث فرعوني وبطلمي وروماني (مناجم الزمرد)',
        description: 'المحمية تغطي مساحة 7000 كم² تجمع البر والبحر. كانت قديماً مركز "مناجم كليوباترا" لاستخراج الزمرد والأحجار عبر دروب وادي الجمال لموانئ النيل، وبيعيش فيها العبابدة.',
        history: 'محمية وادي الجمال بالبحر الأحمر أروع المحميات الطبيعية والتاريخية؛ بتمتد من جبال البحر الأحمر للشعاب المرجانية، وبتضم مناجم الزمرد الرومانية وقبائل العبابدة.',
        significance: 'تجمع فريد بين الآثار الرومانية، والشواطئ البكر، والبيئة البحرية الغنية بالدلافين، والتراث الإنساني لقبائل الصحراء.',
        locationName: 'جنوب مرسى علم، محافظة البحر الأحمر',
        locationDescription: 'تقع جنوب مدينة مرسى علم بنحو 45 كم وتضم وادي الجمال الرئيسي وجزر حماطة وشاطئ القلعان.',
        visitorTips: 'استمتع برحلة سفاري مع دليل من العبابدة، وشوف شاطئ حنكوراة الشهير برماله البيضا، ومارس الغوص والسنوركلينج في خليج القلعان.',
        coverImage: '',
        gallery: [],
        coordinates: { lat: 24.6644, lng: 35.0886 },
        isFeatured: true,
        status: 'approved',
        verificationStatus: 'verified',
        visitDuration: 'من 4 ساعات إلى يوم كامل (أو تخييم بيئي)',
        visitInfo: {
            visitStatus: 'requires_safari_permit',
            visitStatusLabel: 'محمية طبيعية وتصريح سفاري بيئي',
            visitStatusNote: 'المحمية مفتوحة للزيارة والرحلات البيئية والغوص؛ والتجول في وديانها الصحراوية ومناجم الزمرد يتطلب سيارات دفع رباعي وتنسيقاً مع مرشدي قبائل العبابدة المعتمدين وسداد رسوم المحميات الطبيعية.',
            openingHours: 'يومياً من شروق الشمس حتى غروبها (والتخييم الليلي بتصريح بيئي مسبق)',
            bestTimeToVisit: 'من أكتوبر حتى مايو',
            entryFee: 'تذاكر رسوم زيارة المحميات الطبيعية الصادرة عن وزارة البيئة المصرية',
            reservationRequired: false
        },
        access: {
            description: 'طريق مرسى علم - برنيس الساحلي المباشر (جنوب مرسى علم بـ 45 كم).',
            transportation: 'سيارات دفع رباعي مجهزة أو حافلات الجولات البيئية المرخصة'
        },
        address: { governorate: 'البحر الأحمر', city: 'مرسى علم' },
        sourceName: 'جهاز شؤون البيئة - قطاع حماية الطبيعة ومحميات البحر الأحمر',
        sourceUrl: 'http://www.eeaa.gov.eg',
        sourceType: 'official_gov',
        researchDate: '2026-09-01',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    }
];